// POČETAK FAJLA: src/DemoData/frenchMassiveData.js
import { generateAiImage } from './v8AiVision.js'; // 🔥 Povezano na centralni AI mozak

const BAKES = ["Baguette Tradition", "Pain de Campagne", "Brioche", "Croissant", "Pain au Chocolat", "Pain aux Raisins", "Chausson aux Pommes", "Gougères", "Quiche Lorraine", "Quiche aux Poireaux", "Quiche au Saumon", "Pissaladière", "Flamiche aux Poireaux", "Tourte Lorraine", "Feuilleté au Fromage", "Croque Monsieur", "Croque Madame"];
const MEATS = ["Boeuf Bourguignon", "Coq au Vin", "Blanquette de Veau", "Confit de Canard", "Magret de Canard", "Cassoulet", "Pot-au-Feu", "Steak au Poivre", "Steak Frites", "Entrecôte Bordelaise", "Filet de Boeuf Rossini", "Navarin d’Agneau", "Gigot d’Agneau", "Lapin à la Moutarde", "Poulet Basquaise", "Poulet Vallée d’Auge", "Choucroute Garnie", "Andouillette Grillée", "Saucisse de Toulouse", "Hachis Parmentier"];
const SEAFOOD = ["Bouillabaisse", "Sole Meunière", "Moules Marinières", "Moules à la Crème", "Coquilles Saint-Jacques", "Brandade de Morue", "Matelote de Poisson", "Truite Amandine", "Saumon à l’Oseille", "Cabillaud à la Provençale", "Dorade au Four", "Loup de Mer Grillé", "Homard Thermidor", "Bisque de Homard", "Huîtres Gratinées", "Crevettes Flambées", "Escargots de Mer", "Plateau de Fruits de Mer"];
const SOUPS = ["Soupe à l’Oignon Gratinée", "Bouillabaisse", "Bisque de Homard", "Potage Parmentier", "Vichyssoise", "Soupe au Pistou", "Garbure", "Velouté de Champignons", "Velouté de Potiron", "Soupe de Poireaux et Pommes de Terre", "Soupe de Poissons", "Consommé de Boeuf", "Petite Marmite", "Soupe de Lentilles", "Soupe de Châtaignes"];
const APPETIZERS = ["Escargots de Bourgogne", "Foie Gras", "Pâté de Campagne", "Pâté en Croûte", "Terrine de Canard", "Rillettes de Porc", "Rillettes de Canard", "Oeufs Mimosa", "Oeufs en Meurette", "Salade Lyonnaise", "Salade Niçoise", "Salade de Chèvre Chaud", "Asperges à la Hollandaise", "Poireaux Vinaigrette", "Artichauts à la Vinaigrette", "Tartare de Saumon", "Steak Tartare", "Carpaccio de Saint-Jacques"];
const SIDES = ["Ratatouille", "Gratin Dauphinois", "Pommes Anna", "Pommes Boulangères", "Pommes Duchesse", "Pommes Dauphine", "Pommes Frites", "Pommes Sarladaises", "Aligot", "Purée de Pommes de Terre", "Haricots Verts à l’Ail", "Petits Pois à la Française", "Endives Braisées", "Champignons à la Crème", "Carottes Vichy", "Tian de Légumes", "Gratin de Courgettes", "Gratin de Chou-Fleur"];
const EGGS_CHEESE = ["Omelette aux Fines Herbes", "Omelette aux Champignons", "Omelette au Fromage", "Oeufs Cocotte", "Oeufs en Meurette", "Soufflé au Fromage", "Soufflé au Roquefort", "Tartiflette", "Raclette", "Fondue Savoyarde", "Croque Monsieur", "Croque Madame", "Gratin de Reblochon", "Camembert Rôti", "Chèvre Chaud"];
const REGIONAL = ["Cassoulet", "Choucroute Garnie", "Tartiflette", "Raclette", "Fondue Savoyarde", "Aligot", "Truffade", "Pissaladière", "Socca", "Galette Bretonne", "Crêpe Complète", "Ficelle Picarde", "Flamiche aux Poireaux", "Potée Auvergnate", "Garbure", "Axoa de Veau", "Poulet Basquaise", "Baeckeoffe", "Andouillette de Troyes", "Quenelles de Brochet"];
const SANDWICHES = ["Croque Monsieur", "Croque Madame", "Jambon-Beurre", "Sandwich Parisien", "Pan Bagnat", "Galette Complète", "Galette Saucisse", "Crêpe au Jambon et Fromage", "Crêpe au Sucre", "Crêpe au Citron", "Crêpe Suzette", "Socca", "Pissaladière", "Beignet de Courgette", "Gougères", "Quiche Lorraine", "Tarte Flambée"];
const DESSERTS = ["Crème Brûlée", "Crème Caramel", "Mousse au Chocolat", "Profiteroles", "Éclairs au Chocolat", "Éclairs au Café", "Paris-Brest", "Mille-Feuille", "Tarte Tatin", "Tarte au Citron", "Tarte au Citron Meringuée", "Tarte aux Fraises", "Tarte aux Pommes", "Clafoutis aux Cerises", "Crêpes Suzette", "Île Flottante", "Baba au Rhum", "Madeleines", "Financiers", "Macarons", "Canelés de Bordeaux", "Kouign-Amann", "Far Breton", "Opéra Cake", "Saint-Honoré", "Religieuse", "Fraisier", "Charlotte aux Fraises", "Mont-Blanc", "Galette des Rois", "Pain d’Épices", "Bugnes", "Beignets", "Palmiers"];

const RAW_FRENCH_ITEMS = [
  ...APPETIZERS.map((name, idx) => ({ category: "Hors d'Œuvres & Starters", name, price: "18.00", desc: `A delicate and refined ${name}, offering the perfect prelude to an exceptional French culinary experience.`, img: generateAiImage(name, "premium French haute cuisine"), isSignature: name === "Escargots de Bourgogne" || name === "Foie Gras" })),
  ...SOUPS.map((name, idx) => ({ category: "Soupes & Traditional Stews", name, price: "14.00", desc: `Rich, aromatic ${name}, simmered to perfection using classical techniques and rich culinary heritage.`, img: generateAiImage(name, "premium French haute cuisine"), isSignature: name === "Soupe à l’Oignon Gratinée" })),
  ...MEATS.map((name, idx) => ({ category: "Viandes & Classic Meats", name, price: "34.00", desc: `Masterfully slow-cooked ${name}, elegantly plated with a reduction of exquisite regional wine and fresh herbs.`, img: generateAiImage(name, "premium French haute cuisine"), isSignature: name === "Boeuf Bourguignon" || name === "Coq au Vin" })),
  ...SEAFOOD.map((name, idx) => ({ category: "Poissons & Fruits de Mer", name, price: "38.00", desc: `Wild-caught ${name}, elegantly prepared with classical French butter sauces and delicate seasonings.`, img: generateAiImage(name, "premium French haute cuisine"), isSignature: name === "Bouillabaisse" })),
  ...REGIONAL.map((name, idx) => ({ category: "Spécialités Régionales", name, price: "26.00", desc: `An authentic, heritage-rich ${name}, honoring the rustic and beloved culinary traditions of the French countryside.`, img: generateAiImage(name, "premium French haute cuisine"), isSignature: false })),
  ...EGGS_CHEESE.map((name, idx) => ({ category: "Œufs & Fromages Affinés", name, price: "16.00", desc: `A rich and comforting ${name}, masterfully crafted with premium artisan cheeses and farm-fresh ingredients.`, img: generateAiImage(name, "premium French haute cuisine"), isSignature: false })),
  ...SIDES.map((name, idx) => ({ category: "Garnitures & Sides", name, price: "9.00", desc: `Beautifully prepared ${name}, showcasing vibrant seasonal produce and elevated traditional techniques.`, img: generateAiImage(name, "premium French haute cuisine"), isSignature: name === "Gratin Dauphinois" })),
  ...BAKES.map((name, idx) => ({ category: "Boulangerie & Savory Bakes", name, price: "8.00", desc: `Freshly baked artisan ${name}, featuring a golden, flaky crust and a deeply comforting, buttery interior.`, img: generateAiImage(name, "premium French haute cuisine"), isSignature: false })),
  ...SANDWICHES.map((name, idx) => ({ category: "Crêpes & Café Classics", name, price: "12.00", desc: `A flawless, gourmet ${name}, combining authentic Parisian flavors with modern culinary elegance.`, img: generateAiImage(name, "premium French haute cuisine"), isSignature: false })),
  ...DESSERTS.map((name, idx) => ({ category: "Pâtisserie & Desserts", name, price: "11.00", desc: `A decadent, masterfully crafted ${name}, serving as the ultimate sweet finale to your dining experience.`, img: generateAiImage(name, "premium French haute cuisine"), isSignature: name === "Crème Brûlée" || name === "Macarons" }))
];

export const FRENCH_MASSIVE_MENU = {
  restaurantName: "La Maison de l'Élégance",
  themeColor: "#a855f7", // V8 Purple
  currency: "€",
  items: RAW_FRENCH_ITEMS
};
// KRAJ FAJLA