// POČETAK FAJLA: src/DemoData/globalStreetFoodData.js

// 🔥 BAZA SIGURNIH HD SLIKA (BEZ AI HALUCINACIJA I GREŠAKA) 🔥
const SAFE_IMAGE_POOLS = {
  latin: [
    "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1613514785940-daed07799d9b?auto=format&fit=crop&w=800&q=80"
  ],
  middleEast: [
    "https://images.unsplash.com/photo-1593504049359-74330189a345?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80"
  ],
  africa: [
    "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1582285514681-30d8804cbff8?auto=format&fit=crop&w=800&q=80"
  ],
  indian: [
    "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1601050690597-df0568a70950?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1589301760014-d929f39ce9b1?auto=format&fit=crop&w=800&q=80"
  ],
  eastAsian: [
    "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1582450871972-ab5ca641643d?auto=format&fit=crop&w=800&q=80"
  ],
  seAsian: [
    "https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1626804475297-41607ea0af5f?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80"
  ],
  europe: [
    "https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1600803907087-f56d462fd26b?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80"
  ],
  balkans: [
    "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=800&q=80"
  ],
  naAmerica: [
    "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1610440042657-612c34d95e9f?auto=format&fit=crop&w=800&q=80"
  ],
  sweets: [
    "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1514517220017-8ce97a34a7b6?auto=format&fit=crop&w=800&q=80"
  ]
};

const getSafeImage = (poolName, index) => {
  const pool = SAFE_IMAGE_POOLS[poolName] || SAFE_IMAGE_POOLS.naAmerica;
  return pool[index % pool.length];
};

export const GLOBAL_STREET_MENU = { 
  restaurantName: "Supreme Fast Food", 
  themeColor: "#ef4444", 
  currency: "$", 
  items: [
    // --- 1. LATIN AMERICA & CARIBBEAN ---
    { category: "Latin America & Caribbean", name: "Tacos al Pastor", price: "9.50", desc: "Marinated spit-roasted pork with sweet pineapple and onions on a fresh corn tortilla.", img: getSafeImage("latin", 0), isSignature: true },
    { category: "Latin America & Caribbean", name: "Tacos de Asada", price: "10.00", desc: "Classic tacos packed with juicy grilled beef steak and fresh salsa.", img: getSafeImage("latin", 1), isSignature: true },
    { category: "Latin America & Caribbean", name: "Tacos de Birria", price: "11.00", desc: "Famous tacos with meat stewed in a rich, spiced broth, served with consommé.", img: getSafeImage("latin", 2), isSignature: true },
    { category: "Latin America & Caribbean", name: "Quesabirria", price: "12.00", desc: "An extremely juicy fusion of a quesadilla and tacos de birria with melted cheese.", img: getSafeImage("latin", 3), isSignature: true },
    { category: "Latin America & Caribbean", name: "Elote", price: "6.00", desc: "Mexican street corn smothered in mayonnaise, cheese, lime, and chili powder.", img: getSafeImage("latin", 4), isSignature: false },
    { category: "Latin America & Caribbean", name: "Esquites", price: "6.50", desc: "Corn off the cob served in a cup with the same delicious toppings as elote.", img: getSafeImage("latin", 5), isSignature: false },
    { category: "Latin America & Caribbean", name: "Tamales", price: "8.00", desc: "Corn dough wrapped and steamed in a corn husk, filled with savory meat.", img: getSafeImage("latin", 6), isSignature: false },
    { category: "Latin America & Caribbean", name: "Gorditas", price: "9.00", desc: "Thick, fried cornmeal pockets stuffed with cheese, meat, and salsa.", img: getSafeImage("latin", 7), isSignature: false },
    { category: "Latin America & Caribbean", name: "Sopes", price: "8.50", desc: "Thick corn tortillas with pinched edges, topped with beans and garnishes.", img: getSafeImage("latin", 8), isSignature: false },
    { category: "Latin America & Caribbean", name: "Tostadas", price: "7.00", desc: "Crispy baked tortilla layered with rich toppings and salsa.", img: getSafeImage("latin", 9), isSignature: false },
    { category: "Latin America & Caribbean", name: "Quesadillas", price: "8.50", desc: "Classic tortillas stuffed with melting Mexican cheese.", img: getSafeImage("latin", 10), isSignature: false },
    { category: "Latin America & Caribbean", name: "Cemitas", price: "12.00", desc: "Puebla-style sandwich on a sesame seed bun, loaded with breaded meat and avocado.", img: getSafeImage("latin", 11), isSignature: true },
    { category: "Latin America & Caribbean", name: "Pambazos", price: "11.00", desc: "Mexican sandwich with bread dipped in red guajillo sauce and fried.", img: getSafeImage("latin", 12), isSignature: false },
    { category: "Latin America & Caribbean", name: "Churros", price: "6.50", desc: "Extremely stretchy sweet cane deep-fried and coated with cinnamon sugar.", img: getSafeImage("sweets", 13), isSignature: true },
    { category: "Latin America & Caribbean", name: "Arepas", price: "9.00", desc: "Colombian and Venezuelan grilled cornmeal cakes, split and stuffed.", img: getSafeImage("latin", 14), isSignature: true },
    { category: "Latin America & Caribbean", name: "Arepa Reina Pepiada", price: "11.50", desc: "Iconic Venezuelan arepa filled with a creamy chicken and avocado salad.", img: getSafeImage("latin", 15), isSignature: true },
    { category: "Latin America & Caribbean", name: "Arepa de Queso", price: "9.50", desc: "Classic arepa stuffed to the brim with melting white cheese.", img: getSafeImage("latin", 16), isSignature: false },
    { category: "Latin America & Caribbean", name: "Empanadas", price: "7.50", desc: "Golden fried turnovers filled with savory meat, potatoes, or cheese.", img: getSafeImage("latin", 17), isSignature: false },
    { category: "Latin America & Caribbean", name: "Choripán", price: "10.00", desc: "Argentinian street food classic: grilled chorizo in a crusty bread roll with chimichurri.", img: getSafeImage("latin", 18), isSignature: true },
    { category: "Latin America & Caribbean", name: "Lomito", price: "13.00", desc: "A massive Argentinian steak sandwich loaded with tomatoes, onions, and fried eggs.", img: getSafeImage("latin", 19), isSignature: true },
    { category: "Latin America & Caribbean", name: "Chivito", price: "14.50", desc: "Uruguay's national dish: a towering sandwich with sliced steak, mozzarella, ham, and bacon.", img: getSafeImage("latin", 20), isSignature: true },
    { category: "Latin America & Caribbean", name: "Salchipapas", price: "8.50", desc: "Peruvian street food staple: french fries topped with pan-fried beef sausages.", img: getSafeImage("latin", 21), isSignature: false },
    { category: "Latin America & Caribbean", name: "Anticuchos", price: "11.00", desc: "Popular Peruvian grilled skewers, traditionally made from marinated beef heart.", img: getSafeImage("latin", 22), isSignature: true },
    { category: "Latin America & Caribbean", name: "Papa Rellena", price: "9.00", desc: "Peruvian stuffed potato croquette filled with seasoned ground beef and deep-fried.", img: getSafeImage("latin", 23), isSignature: false },
    { category: "Latin America & Caribbean", name: "Picarones", price: "7.00", desc: "Peruvian sweet potato and squash doughnuts served with sweet syrup.", img: getSafeImage("sweets", 24), isSignature: false },
    { category: "Latin America & Caribbean", name: "Ceviche Cups", price: "12.00", desc: "Fresh raw fish cured in citrus juices, served in a portable street-style cup.", img: getSafeImage("latin", 25), isSignature: true },
    { category: "Latin America & Caribbean", name: "Patacones", price: "8.00", desc: "Twice-fried green plantain slices, often topped with meat or cheese.", img: getSafeImage("latin", 26), isSignature: false },
    { category: "Latin America & Caribbean", name: "Tequeños", price: "8.50", desc: "Venezuelan fried breaded cheese sticks, the ultimate party snack.", img: getSafeImage("latin", 27), isSignature: false },
    { category: "Latin America & Caribbean", name: "Cachapas", price: "10.00", desc: "Sweet fresh corn pancakes from Venezuela, folded over handmade cheese.", img: getSafeImage("latin", 28), isSignature: true },
    { category: "Latin America & Caribbean", name: "Coxinha", price: "8.00", desc: "Brazilian teardrop-shaped chicken croquettes, crispy outside and creamy inside.", img: getSafeImage("latin", 29), isSignature: true },
    { category: "Latin America & Caribbean", name: "Pastel de Feira", price: "7.50", desc: "Brazilian deep-fried thin crust pies with assorted savory fillings.", img: getSafeImage("latin", 30), isSignature: false },
    { category: "Latin America & Caribbean", name: "Pão de Queijo", price: "6.00", desc: "Warm and chewy Brazilian cheese bread balls made from cassava flour.", img: getSafeImage("latin", 31), isSignature: true },
    { category: "Latin America & Caribbean", name: "Acarajé", price: "9.50", desc: "Bahian deep-fried black-eyed pea fritters stuffed with shrimp paste (vatapá).", img: getSafeImage("latin", 32), isSignature: true },
    { category: "Latin America & Caribbean", name: "Tapioca Crepes", price: "8.00", desc: "Brazilian gluten-free crepes made from tapioca flour, filled sweet or savory.", img: getSafeImage("latin", 33), isSignature: false },
    { category: "Latin America & Caribbean", name: "Espetinho", price: "7.00", desc: "Brazilian street barbecue skewers, featuring various cuts of beef or chicken.", img: getSafeImage("latin", 34), isSignature: false },
    { category: "Latin America & Caribbean", name: "Kibe", price: "8.50", desc: "Brazilian-Lebanese deep-fried beef and bulgur wheat croquettes.", img: getSafeImage("latin", 35), isSignature: false },
    { category: "Latin America & Caribbean", name: "Hot Dog Brasileiro", price: "10.00", desc: "An over-the-top Brazilian hot dog loaded with corn, peas, potato sticks, and cheese.", img: getSafeImage("latin", 36), isSignature: true },

    // --- 2. MIDDLE EAST & NORTH AFRICA ---
    { category: "Middle East & North Africa", name: "Gyros", price: "9.00", desc: "Greek street food classic: shaved meat served in a pita with tzatziki and fries.", img: getSafeImage("middleEast", 0), isSignature: true },
    { category: "Middle East & North Africa", name: "Souvlaki Pita", price: "9.50", desc: "Grilled meat skewers wrapped in a warm pita bread with fresh vegetables.", img: getSafeImage("middleEast", 1), isSignature: true },
    { category: "Middle East & North Africa", name: "Koulouri", price: "4.50", desc: "Greek circular bread ring encrusted heavily with sesame seeds.", img: getSafeImage("middleEast", 2), isSignature: false },
    { category: "Middle East & North Africa", name: "Loukoumades", price: "6.50", desc: "Bite-sized Greek sweet honey puffs, deep-fried to golden perfection.", img: getSafeImage("sweets", 3), isSignature: false },
    { category: "Middle East & North Africa", name: "Spanakopita", price: "7.00", desc: "Greek savory pastry filled with spinach and feta cheese in flaky phyllo.", img: getSafeImage("middleEast", 4), isSignature: false },
    { category: "Middle East & North Africa", name: "Tiropita", price: "7.00", desc: "Traditional Greek cheese pie layered with crispy phyllo dough.", img: getSafeImage("middleEast", 5), isSignature: false },
    { category: "Middle East & North Africa", name: "Döner Kebab", price: "10.50", desc: "Turkish shaved meat served in bread or flatbread with crisp salad.", img: getSafeImage("middleEast", 6), isSignature: true },
    { category: "Middle East & North Africa", name: "Tavuk Döner", price: "9.50", desc: "Chicken döner kebab, light, juicy, and perfectly spiced.", img: getSafeImage("middleEast", 7), isSignature: false },
    { category: "Middle East & North Africa", name: "Tantuni", price: "11.00", desc: "Spicy julienned meat fried with cotton-seed oil, served in a lavash wrap.", img: getSafeImage("middleEast", 8), isSignature: true },
    { category: "Middle East & North Africa", name: "Kokoreç", price: "12.00", desc: "Grilled, heavily spiced sheep intestines served in crusty bread. A Turkish icon.", img: getSafeImage("middleEast", 9), isSignature: true },
    { category: "Middle East & North Africa", name: "Lahmacun", price: "7.50", desc: "Thin, crispy Turkish dough topped with minced meat and herbs (Turkish pizza).", img: getSafeImage("middleEast", 10), isSignature: true },
    { category: "Middle East & North Africa", name: "Pide", price: "9.50", desc: "Boat-shaped Turkish flatbread baked with various savory toppings.", img: getSafeImage("middleEast", 11), isSignature: false },
    { category: "Middle East & North Africa", name: "Simit", price: "4.00", desc: "Circular Turkish bread encrusted with sesame seeds, crisp on the outside.", img: getSafeImage("middleEast", 12), isSignature: false },
    { category: "Middle East & North Africa", name: "Gözleme", price: "8.50", desc: "Savory Turkish flatbread folded over a variety of fillings and griddled.", img: getSafeImage("middleEast", 13), isSignature: false },
    { category: "Middle East & North Africa", name: "Midye Dolma", price: "6.00", desc: "Turkish street mussels stuffed with spiced aromatic rice, pine nuts, and currants.", img: getSafeImage("middleEast", 14), isSignature: true },
    { category: "Middle East & North Africa", name: "Balık Ekmek", price: "10.00", desc: "Iconic Istanbul grilled fish sandwich served with onions and lettuce.", img: getSafeImage("middleEast", 15), isSignature: true },
    { category: "Middle East & North Africa", name: "Kumpir", price: "9.50", desc: "Giant baked potato loaded with butter, cheese, and endless toppings.", img: getSafeImage("middleEast", 16), isSignature: false },
    { category: "Middle East & North Africa", name: "Islak Hamburger", price: "7.00", desc: "Istanbul's 'wet burger', soaked in a garlicky tomato sauce and steamed.", img: getSafeImage("middleEast", 17), isSignature: true },
    { category: "Middle East & North Africa", name: "Börek", price: "7.50", desc: "Flaky pastry filled with cheese, minced meat, or spinach.", img: getSafeImage("middleEast", 18), isSignature: false },
    { category: "Middle East & North Africa", name: "Köfte Ekmek", price: "9.50", desc: "Turkish meatballs grilled and served inside half a loaf of bread.", img: getSafeImage("middleEast", 19), isSignature: false },
    { category: "Middle East & North Africa", name: "Dürüm", price: "10.00", desc: "A tight, portable Turkish wrap filled with kebab meat and vegetables.", img: getSafeImage("middleEast", 20), isSignature: false },
    { category: "Middle East & North Africa", name: "Adana Dürüm", price: "11.50", desc: "Spicy minced lamb kebab wrapped in flatbread with onions and parsley.", img: getSafeImage("middleEast", 21), isSignature: true },
    { category: "Middle East & North Africa", name: "Ciğer Dürüm", price: "10.50", desc: "Liver skewers wrapped in lavash bread, a favorite in Southeastern Turkey.", img: getSafeImage("middleEast", 22), isSignature: true },
    { category: "Middle East & North Africa", name: "Falafel", price: "7.00", desc: "Deep-fried balls made from ground chickpeas and herbs.", img: getSafeImage("middleEast", 23), isSignature: true },
    { category: "Middle East & North Africa", name: "Falafel Pita", price: "9.00", desc: "Crispy falafel stuffed into a pita pocket with hummus, tahini, and salad.", img: getSafeImage("middleEast", 24), isSignature: true },
    { category: "Middle East & North Africa", name: "Shawarma", price: "10.50", desc: "Levantine meat preparation, roasted on a slow-turning vertical spit.", img: getSafeImage("middleEast", 25), isSignature: true },
    { category: "Middle East & North Africa", name: "Chicken Shawarma", price: "9.50", desc: "Juicy chicken shawarma wrapped with garlic sauce and pickles.", img: getSafeImage("middleEast", 26), isSignature: false },
    { category: "Middle East & North Africa", name: "Beef Shawarma", price: "11.00", desc: "Rich beef shawarma wrapped with tahini, onions, and sumac.", img: getSafeImage("middleEast", 27), isSignature: false },
    { category: "Middle East & North Africa", name: "Lamb Shawarma", price: "12.00", desc: "Premium lamb shawarma, tender and flavorful.", img: getSafeImage("middleEast", 28), isSignature: true },
    { category: "Middle East & North Africa", name: "Manakish", price: "6.50", desc: "Levantine flatbread baked with various toppings.", img: getSafeImage("middleEast", 29), isSignature: false },
    { category: "Middle East & North Africa", name: "Manakish Zaatar", price: "5.50", desc: "Flatbread generously coated with a savory za'atar and olive oil mixture.", img: getSafeImage("middleEast", 30), isSignature: true },
    { category: "Middle East & North Africa", name: "Manakish Cheese", price: "7.00", desc: "Flatbread topped with melting Levantine white cheeses.", img: getSafeImage("middleEast", 31), isSignature: false },
    { category: "Middle East & North Africa", name: "Arayes", price: "9.50", desc: "Pita bread stuffed with minced meat and grilled until crispy.", img: getSafeImage("middleEast", 32), isSignature: true },
    { category: "Middle East & North Africa", name: "Sambousek", price: "7.50", desc: "Small, savory meat or cheese filled pastries, deep-fried or baked.", img: getSafeImage("middleEast", 33), isSignature: false },
    { category: "Middle East & North Africa", name: "Kibbeh", price: "9.00", desc: "Levantine dish made of bulgur, minced onions, and finely ground lean beef.", img: getSafeImage("middleEast", 34), isSignature: true },
    { category: "Middle East & North Africa", name: "Ka’ak", price: "5.00", desc: "Ring-shaped bread covered with sesame seeds, popular in Lebanon.", img: getSafeImage("middleEast", 35), isSignature: false },
    { category: "Middle East & North Africa", name: "Musakhan Rolls", price: "10.00", desc: "Palestinian sumac-spiced chicken and onions rolled in thin bread and baked.", img: getSafeImage("middleEast", 36), isSignature: true },
    { category: "Middle East & North Africa", name: "Sabich", price: "9.50", desc: "Israeli pita sandwich stuffed with fried eggplant, hard-boiled eggs, and amba.", img: getSafeImage("middleEast", 37), isSignature: true },
    { category: "Middle East & North Africa", name: "Jerusalem Bagel", price: "5.50", desc: "Elongated, oval-shaped bread covered in sesame seeds, softer than a standard bagel.", img: getSafeImage("middleEast", 38), isSignature: false },
    { category: "Middle East & North Africa", name: "Bourekas", price: "7.00", desc: "Israeli baked pastries made of phyllo dough, stuffed with cheese or potatoes.", img: getSafeImage("middleEast", 39), isSignature: false },
    { category: "Middle East & North Africa", name: "Malawach", price: "8.00", desc: "Yemenite-Jewish fried flaky flatbread, served with crushed tomato and zhug.", img: getSafeImage("middleEast", 40), isSignature: true },
    { category: "Middle East & North Africa", name: "Jachnun", price: "8.50", desc: "Yemenite Jewish rolled dough baked slowly overnight, served with grated tomatoes.", img: getSafeImage("middleEast", 41), isSignature: false },
    { category: "Middle East & North Africa", name: "Koshari", price: "8.00", desc: "Egypt's national dish: a mix of rice, macaroni, and lentils topped with spicy tomato sauce.", img: getSafeImage("middleEast", 42), isSignature: true },
    { category: "Middle East & North Africa", name: "Ta’ameya", price: "6.50", desc: "Egyptian falafel made from fava beans instead of chickpeas.", img: getSafeImage("middleEast", 43), isSignature: true },
    { category: "Middle East & North Africa", name: "Hawawshi", price: "9.50", desc: "Egyptian street food: pita bread stuffed with minced meat and heavily spiced.", img: getSafeImage("middleEast", 44), isSignature: true },
    { category: "Middle East & North Africa", name: "Feteer Meshaltet", price: "8.00", desc: "Egyptian flaky, layered pastry served plain or with honey and cheese.", img: getSafeImage("middleEast", 45), isSignature: false },
    { category: "Middle East & North Africa", name: "Ful Medames", price: "7.00", desc: "Slow-cooked fava beans served with olive oil, cumin, and lemon juice.", img: getSafeImage("middleEast", 46), isSignature: true },
    { category: "Middle East & North Africa", name: "Kebda Sandwich", price: "8.50", desc: "Alexandrian-style beef liver sandwich, highly spiced and garlicky.", img: getSafeImage("middleEast", 47), isSignature: true },
    { category: "Middle East & North Africa", name: "Kofta Sandwich", price: "9.00", desc: "Grilled minced meat skewers served inside a fresh Egyptian bread roll.", img: getSafeImage("middleEast", 48), isSignature: false },
    { category: "Middle East & North Africa", name: "Merguez Sandwich", price: "10.00", desc: "Spicy North African mutton or beef sausage served in a baguette.", img: getSafeImage("middleEast", 49), isSignature: true },
    { category: "Middle East & North Africa", name: "Brik", price: "7.50", desc: "Tunisian deep-fried pastry usually filled with egg, tuna, and parsley.", img: getSafeImage("middleEast", 50), isSignature: true },
    { category: "Middle East & North Africa", name: "Fricassé Tunisien", price: "8.00", desc: "Tunisian fried sandwich filled with tuna, hard-boiled egg, olives, and harissa.", img: getSafeImage("middleEast", 51), isSignature: true },
    { category: "Middle East & North Africa", name: "Lablabi", price: "7.00", desc: "Tunisian chickpea soup served over crusty bread with garlic and cumin.", img: getSafeImage("middleEast", 52), isSignature: false },
    { category: "Middle East & North Africa", name: "Msemen", price: "6.00", desc: "Moroccan square, flaky flatbread, often eaten for breakfast with honey.", img: getSafeImage("middleEast", 53), isSignature: false },
    { category: "Middle East & North Africa", name: "Maakouda", price: "5.50", desc: "Moroccan deep-fried potato patties.", img: getSafeImage("middleEast", 54), isSignature: false },
    { category: "Middle East & North Africa", name: "Sfenj", price: "5.00", desc: "Maghrebi doughnut, unsweetened and spongy, eaten plain or with sugar.", img: getSafeImage("sweets", 55), isSignature: false },
    { category: "Middle East & North Africa", name: "Brochettes", price: "9.50", desc: "Moroccan street kebabs, heavily spiced and grilled over coals.", img: getSafeImage("middleEast", 56), isSignature: false },
    { category: "Middle East & North Africa", name: "Bissara", price: "6.50", desc: "Moroccan dried fava bean soup, drizzled with olive oil and cumin.", img: getSafeImage("middleEast", 57), isSignature: false },

    // --- 3. SUB-SAHARAN AFRICA ---
    { category: "Sub-Saharan Africa", name: "Bunny Chow", price: "11.00", desc: "South African fast food: a hollowed-out loaf of bread filled with spicy curry.", img: getSafeImage("africa", 0), isSignature: true },
    { category: "Sub-Saharan Africa", name: "Boerewors Roll", price: "9.00", desc: "South African hot dog featuring a traditional, coarsely minced sausage.", img: getSafeImage("africa", 1), isSignature: true },
    { category: "Sub-Saharan Africa", name: "Vetkoek", price: "7.50", desc: "South African fried dough bread, often filled with savory mince (curry bunny).", img: getSafeImage("africa", 2), isSignature: false },
    { category: "Sub-Saharan Africa", name: "Gatsby Sandwich", price: "14.00", desc: "Cape Town's legendary massive submarine sandwich filled with chips and meat.", img: getSafeImage("africa", 3), isSignature: true },
    { category: "Sub-Saharan Africa", name: "Kota", price: "10.00", desc: "South African quarter loaf of bread hollowed out and filled with chips, polony, and cheese.", img: getSafeImage("africa", 4), isSignature: true },

    // --- 4. SOUTH ASIA (INDIA & SUBCONTINENT) ---
    { category: "South Asian Street Food", name: "Samosa", price: "5.00", desc: "Iconic Indian deep-fried pastry with a savory filling of spiced potatoes and peas.", img: getSafeImage("indian", 0), isSignature: true },
    { category: "South Asian Street Food", name: "Vada Pav", price: "6.50", desc: "Mumbai's famous street burger: deep-fried potato dumpling inside a bread bun.", img: getSafeImage("indian", 1), isSignature: true },
    { category: "South Asian Street Food", name: "Pav Bhaji", price: "8.00", desc: "A thick vegetable curry served with a soft bread roll (pav) toasted in butter.", img: getSafeImage("indian", 2), isSignature: true },
    { category: "South Asian Street Food", name: "Pani Puri", price: "6.00", desc: "Hollow, crispy puris filled with a mixture of flavored water, tamarind chutney, and potatoes.", img: getSafeImage("indian", 3), isSignature: true },
    { category: "South Asian Street Food", name: "Golgappa", price: "6.00", desc: "Another name for the beloved Pani Puri, famous in Northern India.", img: getSafeImage("indian", 4), isSignature: false },
    { category: "South Asian Street Food", name: "Bhel Puri", price: "6.50", desc: "A savory snack made of puffed rice, vegetables, and a tangy tamarind sauce.", img: getSafeImage("indian", 5), isSignature: false },
    { category: "South Asian Street Food", name: "Sev Puri", price: "6.50", desc: "Crispy papdi loaded with diced potatoes, onions, chutneys, and crunchy sev.", img: getSafeImage("indian", 6), isSignature: false },
    { category: "South Asian Street Food", name: "Dahi Puri", price: "7.00", desc: "Puris filled with potatoes and chutneys, heavily drenched in sweetened yogurt.", img: getSafeImage("indian", 7), isSignature: false },
    { category: "South Asian Street Food", name: "Aloo Tikki", price: "6.00", desc: "North Indian snack made of boiled potatoes, peas, and various curry spices.", img: getSafeImage("indian", 8), isSignature: false },
    { category: "South Asian Street Food", name: "Aloo Chaat", price: "7.00", desc: "Fried potato cubes tossed in spicy and tangy chutneys.", img: getSafeImage("indian", 9), isSignature: false },
    { category: "South Asian Street Food", name: "Papdi Chaat", price: "7.50", desc: "Crisp dough wafers served with boiled potatoes, chickpeas, chilies, yogurt, and tamarind chutney.", img: getSafeImage("indian", 10), isSignature: false },
    { category: "South Asian Street Food", name: "Samosa Chaat", price: "8.50", desc: "Crushed samosas topped with chickpea curry, yogurt, and sweet and sour chutneys.", img: getSafeImage("indian", 11), isSignature: true },
    { category: "South Asian Street Food", name: "Kachori", price: "6.00", desc: "Spicy deep-fried snack, round and fluffy, filled with baked mixture of lentils or onions.", img: getSafeImage("indian", 12), isSignature: false },
    { category: "South Asian Street Food", name: "Dabeli", price: "6.50", desc: "Sweet and spicy potato mixture filled into a burger bun, topped with pomegranate and peanuts.", img: getSafeImage("indian", 13), isSignature: true },
    { category: "South Asian Street Food", name: "Frankie", price: "9.00", desc: "Mumbai's famous street wrap, filled with spicy meat or vegetables.", img: getSafeImage("indian", 14), isSignature: false },
    { category: "South Asian Street Food", name: "Kathi Roll", price: "9.50", desc: "Kolkata's street food wrap containing skewer-roasted kebab inside a paratha bread.", img: getSafeImage("indian", 15), isSignature: true },
    { category: "South Asian Street Food", name: "Chicken Kathi Roll", price: "10.50", desc: "A Kathi roll stuffed with spicy, marinated grilled chicken.", img: getSafeImage("indian", 16), isSignature: false },
    { category: "South Asian Street Food", name: "Egg Roll", price: "8.00", desc: "A paratha coated with egg and wrapped around onions and chutneys.", img: getSafeImage("indian", 17), isSignature: false },
    { category: "South Asian Street Food", name: "Paneer Roll", price: "9.50", desc: "Vegetarian roll filled with spiced Indian cottage cheese (paneer).", img: getSafeImage("indian", 18), isSignature: false },
    { category: "South Asian Street Food", name: "Chole Bhature", price: "11.00", desc: "Spicy white chickpeas (chole) served with a large, puffy fried bread (bhature).", img: getSafeImage("indian", 19), isSignature: true },
    { category: "South Asian Street Food", name: "Chole Kulche", price: "10.00", desc: "Spicy chickpeas served with a soft, leavened flatbread.", img: getSafeImage("indian", 20), isSignature: false },
    { category: "South Asian Street Food", name: "Kulcha", price: "4.00", desc: "Mildly leavened flatbread, perfect for soaking up curries.", img: getSafeImage("indian", 21), isSignature: false },
    { category: "South Asian Street Food", name: "Amritsari Kulcha", price: "7.00", desc: "Crisp, flaky bread stuffed with spiced potatoes, cooked in a tandoor.", img: getSafeImage("indian", 22), isSignature: true },
    { category: "South Asian Street Food", name: "Paratha", price: "5.00", desc: "Flaky, buttery layered Indian flatbread.", img: getSafeImage("indian", 23), isSignature: false },
    { category: "South Asian Street Food", name: "Aloo Paratha", price: "6.50", desc: "Paratha heavily stuffed with a spiced potato mixture.", img: getSafeImage("indian", 24), isSignature: false },
    { category: "South Asian Street Food", name: "Paneer Paratha", price: "8.00", desc: "Paratha stuffed with spiced cottage cheese.", img: getSafeImage("indian", 25), isSignature: false },
    { category: "South Asian Street Food", name: "Keema Paratha", price: "9.50", desc: "A meat-lovers paratha stuffed with spicy minced meat.", img: getSafeImage("indian", 26), isSignature: false },
    { category: "South Asian Street Food", name: "Dosa", price: "7.00", desc: "A thin, savory crepe made from a fermented batter of lentils and rice.", img: getSafeImage("indian", 27), isSignature: true },
    { category: "South Asian Street Food", name: "Masala Dosa", price: "9.00", desc: "A crispy dosa wrapped around a spiced potato curry filling.", img: getSafeImage("indian", 28), isSignature: true },
    { category: "South Asian Street Food", name: "Mysore Dosa", price: "9.50", desc: "A spicy variant of dosa smeared with a fiery red chutney.", img: getSafeImage("indian", 29), isSignature: false },
    { category: "South Asian Street Food", name: "Uttapam", price: "8.00", desc: "A thick pancake made from dosa batter, topped with tomatoes, onions, and chilies.", img: getSafeImage("indian", 30), isSignature: false },
    { category: "South Asian Street Food", name: "Idli", price: "6.00", desc: "Soft, fluffy steamed rice and lentil cakes, usually served with sambar.", img: getSafeImage("indian", 31), isSignature: false },
    { category: "South Asian Street Food", name: "Medu Vada", price: "6.50", desc: "Crispy, savory, doughnut-shaped fritters made from black lentils.", img: getSafeImage("indian", 32), isSignature: false },
    { category: "South Asian Street Food", name: "Mirchi Bajji", price: "5.50", desc: "Green chilies dipped in gram flour batter and deep-fried.", img: getSafeImage("indian", 33), isSignature: false },
    { category: "South Asian Street Food", name: "Pakora", price: "6.00", desc: "Assorted vegetables deep-fried in a spiced gram flour batter.", img: getSafeImage("indian", 34), isSignature: false },
    { category: "South Asian Street Food", name: "Bhaji", price: "5.50", desc: "Crispy onion fritters, a classic Indian street snack.", img: getSafeImage("indian", 35), isSignature: false },
    { category: "South Asian Street Food", name: "Bread Pakora", price: "6.50", desc: "Slices of bread dipped in spiced gram flour batter and deep-fried.", img: getSafeImage("indian", 36), isSignature: false },
    { category: "South Asian Street Food", name: "Momos", price: "8.00", desc: "Steamed dumplings with a meat or vegetable filling, popular in Northern India and Nepal.", img: getSafeImage("indian", 37), isSignature: true },
    { category: "South Asian Street Food", name: "Chicken Momos", price: "9.00", desc: "Momos filled with juicy, spiced minced chicken.", img: getSafeImage("indian", 38), isSignature: false },
    { category: "South Asian Street Food", name: "Vegetable Momos", price: "7.50", desc: "Momos filled with finely chopped cabbage, carrots, and onions.", img: getSafeImage("indian", 39), isSignature: false },
    { category: "South Asian Street Food", name: "Jhal Muri", price: "5.00", desc: "A spicy, tangy puffed rice snack from Kolkata, mixed with mustard oil.", img: getSafeImage("indian", 40), isSignature: false },
    { category: "South Asian Street Food", name: "Ghugni Chaat", price: "6.50", desc: "Dried yellow peas curry topped with onions, coriander, and chutneys.", img: getSafeImage("indian", 41), isSignature: false },
    { category: "South Asian Street Food", name: "Litti Chokha", price: "8.50", desc: "Roasted wheat balls stuffed with sattu, served with mashed roasted eggplant and tomatoes.", img: getSafeImage("indian", 42), isSignature: true },
    { category: "South Asian Street Food", name: "Ram Ladoo", price: "6.00", desc: "Deep-fried moong dal fritters topped with grated radish and green chutney.", img: getSafeImage("indian", 43), isSignature: false },
    { category: "South Asian Street Food", name: "Jalebi", price: "5.50", desc: "Deep-fried wheat flour batter in circular shapes, soaked in sugar syrup.", img: getSafeImage("sweets", 44), isSignature: true },
    { category: "South Asian Street Food", name: "Kulfi", price: "6.00", desc: "Traditional Indian ice cream, denser and creamier than Western ice cream.", img: getSafeImage("sweets", 45), isSignature: true },
    { category: "South Asian Street Food", name: "Kulfi Falooda", price: "8.00", desc: "Kulfi served with vermicelli noodles, rose syrup, and sweet basil seeds.", img: getSafeImage("sweets", 46), isSignature: true },

    // --- 5. EAST ASIA (CHINA, TAIWAN, JAPAN, KOREA) ---
    { category: "East Asian Street Food", name: "Chinese Jianbing", price: "7.50", desc: "China's favorite street breakfast: a savory, folded crepe filled with egg, sauces, and a crispy cracker.", img: getSafeImage("eastAsian", 0), isSignature: true },
    { category: "East Asian Street Food", name: "Jianbing Guozi", price: "8.00", desc: "The authentic Tianjin version of Jianbing, utilizing a mung bean batter.", img: getSafeImage("eastAsian", 1), isSignature: false },
    { category: "East Asian Street Food", name: "Baozi", price: "6.00", desc: "Soft, fluffy steamed buns filled with savory meat or sweet bean paste.", img: getSafeImage("eastAsian", 2), isSignature: true },
    { category: "East Asian Street Food", name: "Sheng Jian Bao", price: "8.50", desc: "Pan-fried pork buns with a crispy bottom and a juicy, soup-filled interior.", img: getSafeImage("eastAsian", 3), isSignature: true },
    { category: "East Asian Street Food", name: "Xiaolongbao", price: "10.00", desc: "Delicate soup dumplings, expertly pleated and steamed in bamboo baskets.", img: getSafeImage("eastAsian", 4), isSignature: true },
    { category: "East Asian Street Food", name: "Guo Tie", price: "7.50", desc: "Chinese potstickers: pan-fried dumplings that are crispy on the bottom and soft on top.", img: getSafeImage("eastAsian", 5), isSignature: false },
    { category: "East Asian Street Food", name: "Jiaozi", price: "7.00", desc: "Classic Chinese dumplings, typically boiled or steamed.", img: getSafeImage("eastAsian", 6), isSignature: false },
    { category: "East Asian Street Food", name: "Cong You Bing", price: "5.50", desc: "Crispy and flaky scallion pancakes, a staple Chinese street food.", img: getSafeImage("eastAsian", 7), isSignature: true },
    { category: "East Asian Street Food", name: "Rou Jia Mo", price: "8.50", desc: "The 'Chinese hamburger': shredded braised pork stuffed inside a flatbread.", img: getSafeImage("eastAsian", 8), isSignature: true },
    { category: "East Asian Street Food", name: "Chuan’r", price: "9.00", desc: "Spicy cumin-dusted meat skewers, heavily roasted over charcoal.", img: getSafeImage("eastAsian", 9), isSignature: true },
    { category: "East Asian Street Food", name: "Lamb Skewers", price: "10.00", desc: "Xinjiang-style lamb skewers, fatty and heavily spiced with cumin and chili.", img: getSafeImage("eastAsian", 10), isSignature: false },
    { category: "East Asian Street Food", name: "Tanghulu", price: "6.00", desc: "Candied fruit skewers, traditionally made with hawthorn berries coated in hard sugar syrup.", img: getSafeImage("sweets", 11), isSignature: true },
    { category: "East Asian Street Food", name: "Stinky Tofu", price: "7.50", desc: "Fermented tofu with a strong odor but a mild, savory flavor, usually deep-fried.", img: getSafeImage("eastAsian", 12), isSignature: true },
    { category: "East Asian Street Food", name: "Scallion Pancakes", price: "5.50", desc: "Crispy, chewy dough layered with oil and minced scallions.", img: getSafeImage("eastAsian", 13), isSignature: false },
    { category: "East Asian Street Food", name: "Egg Pancakes", price: "6.50", desc: "Taiwanese breakfast staple: a thin pancake wrapped around a fried egg.", img: getSafeImage("eastAsian", 14), isSignature: false },
    { category: "East Asian Street Food", name: "Tea Eggs", price: "3.50", desc: "Hard-boiled eggs cracked and simmered in a savory brew of tea and spices.", img: getSafeImage("eastAsian", 15), isSignature: false },
    { category: "East Asian Street Food", name: "Taiwanese Gua Bao", price: "8.50", desc: "A fluffy steamed bun filled with braised pork belly, pickled mustard greens, and peanut powder.", img: getSafeImage("eastAsian", 16), isSignature: true },
    { category: "East Asian Street Food", name: "Taiwanese Fried Chicken", price: "9.50", desc: "Giant, flattened chicken breast, breaded and fried with a distinctive five-spice flavor.", img: getSafeImage("eastAsian", 17), isSignature: true },
    { category: "East Asian Street Food", name: "Popcorn Chicken", price: "8.00", desc: "Bite-sized pieces of Taiwanese fried chicken with crispy basil leaves.", img: getSafeImage("eastAsian", 18), isSignature: false },
    { category: "East Asian Street Food", name: "Oyster Omelette", price: "10.50", desc: "A starchy, savory omelet filled with small oysters and topped with a sweet-savory sauce.", img: getSafeImage("eastAsian", 19), isSignature: true },
    { category: "East Asian Street Food", name: "Lu Rou Fan", price: "9.00", desc: "Taiwanese ultimate comfort food: minced braised pork belly served over rice.", img: getSafeImage("eastAsian", 20), isSignature: true },
    { category: "East Asian Street Food", name: "Scallion Pancake Roll", price: "8.00", desc: "A flaky scallion pancake rolled around sliced beef and hoisin sauce.", img: getSafeImage("eastAsian", 21), isSignature: false },
    { category: "East Asian Street Food", name: "Pepper Bun", price: "7.00", desc: "Baked buns (Hujiao bing) filled with peppery pork and scallions, cooked in a tandoor-like oven.", img: getSafeImage("eastAsian", 22), isSignature: true },
    { category: "East Asian Street Food", name: "Ba Wan", price: "8.50", desc: "Taiwanese 'meat sphere': a translucent, gelatinous dough stuffed with pork and bamboo shoots.", img: getSafeImage("eastAsian", 23), isSignature: false },
    { category: "East Asian Street Food", name: "Tian Bu La", price: "7.50", desc: "Taiwanese fish paste tempura, deep-fried and served with a sweet brown sauce.", img: getSafeImage("eastAsian", 24), isSignature: false },
    { category: "East Asian Street Food", name: "Wheel Cake", price: "5.00", desc: "Taiwanese Imagawayaki: a round pancake-like pastry filled with red bean or custard.", img: getSafeImage("sweets", 25), isSignature: false },
    { category: "East Asian Street Food", name: "Bubble Waffle", price: "7.50", desc: "Hong Kong's famous spherical egg waffle, crispy on the edges and soft inside.", img: getSafeImage("sweets", 26), isSignature: true },
    { category: "East Asian Street Food", name: "Egg Waffle", price: "7.50", desc: "Another name for the beloved Bubble Waffle.", img: getSafeImage("sweets", 27), isSignature: false },
    { category: "East Asian Street Food", name: "Curry Fish Balls", price: "6.50", desc: "Hong Kong street classic: bouncy fish balls simmered in a mild curry sauce.", img: getSafeImage("eastAsian", 28), isSignature: true },
    { category: "East Asian Street Food", name: "Fish Balls", price: "5.50", desc: "Simple boiled or fried fish balls on a skewer.", img: getSafeImage("eastAsian", 29), isSignature: false },
    { category: "East Asian Street Food", name: "Siu Mai", price: "7.50", desc: "Street-style yellow pork and shrimp dumplings from Hong Kong.", img: getSafeImage("eastAsian", 30), isSignature: false },
    { category: "East Asian Street Food", name: "Cheung Fun", price: "8.00", desc: "Silky, rolled rice noodle rolls, served plain with sweet soy sauce and sesame.", img: getSafeImage("eastAsian", 31), isSignature: true },
    { category: "East Asian Street Food", name: "Char Siu Bao", price: "7.00", desc: "Fluffy steamed buns filled with sweet, sticky BBQ pork.", img: getSafeImage("eastAsian", 32), isSignature: true },
    { category: "East Asian Street Food", name: "Pineapple Bun", price: "5.50", desc: "Hong Kong sweet bun with a crunchy, sugary top crust (contains no pineapple).", img: getSafeImage("sweets", 33), isSignature: false },
    { category: "East Asian Street Food", name: "Takoyaki", price: "9.00", desc: "Japanese spherical snacks made of a wheat flour batter, filled with minced octopus.", img: getSafeImage("eastAsian", 34), isSignature: true },
    { category: "East Asian Street Food", name: "Okonomiyaki", price: "12.00", desc: "Japanese savory pancake containing a variety of ingredients, heavily drizzled with sauce and mayo.", img: getSafeImage("eastAsian", 35), isSignature: true },
    { category: "East Asian Street Food", name: "Yakitori", price: "10.00", desc: "Japanese grilled chicken skewers, glazed with a sweet and savory tare sauce.", img: getSafeImage("eastAsian", 36), isSignature: true },
    { category: "East Asian Street Food", name: "Karaage", price: "9.50", desc: "Japanese bite-sized fried chicken, marinated in soy sauce and ginger.", img: getSafeImage("eastAsian", 37), isSignature: false },
    { category: "East Asian Street Food", name: "Taiyaki", price: "6.50", desc: "Japanese fish-shaped cake, traditionally filled with sweet red bean paste.", img: getSafeImage("sweets", 38), isSignature: true },
    { category: "East Asian Street Food", name: "Imagawayaki", price: "6.00", desc: "A thick Japanese pancake round filled with sweet azuki bean paste.", img: getSafeImage("sweets", 39), isSignature: false },
    { category: "East Asian Street Food", name: "Yaki Imo", price: "5.00", desc: "Japanese roasted sweet potatoes, sold from street carts in winter.", img: getSafeImage("eastAsian", 40), isSignature: false },
    { category: "East Asian Street Food", name: "Yakisoba", price: "10.50", desc: "Japanese stir-fried noodles with pork, cabbage, and a sweet-savory sauce.", img: getSafeImage("eastAsian", 41), isSignature: true },
    { category: "East Asian Street Food", name: "Onigiri", price: "4.50", desc: "Japanese rice ball formed into a triangle, often wrapped in seaweed and filled.", img: getSafeImage("eastAsian", 42), isSignature: false },
    { category: "East Asian Street Food", name: "Korokke", price: "6.50", desc: "Japanese deep-fried potato and meat croquettes.", img: getSafeImage("eastAsian", 43), isSignature: false },
    { category: "East Asian Street Food", name: "Nikuman", price: "6.00", desc: "Japanese steamed pork buns.", img: getSafeImage("eastAsian", 44), isSignature: false },
    { category: "East Asian Street Food", name: "Ikayaki", price: "11.00", desc: "Grilled whole squid on a stick, glazed with sweet soy sauce.", img: getSafeImage("eastAsian", 45), isSignature: true },
    { category: "East Asian Street Food", name: "Dango", price: "5.50", desc: "Japanese dumplings made from rice flour, served on a skewer.", img: getSafeImage("sweets", 46), isSignature: false },
    { category: "East Asian Street Food", name: "Mitarashi Dango", price: "6.00", desc: "Skewered rice dumplings covered in a sweet soy sauce glaze.", img: getSafeImage("sweets", 47), isSignature: true },
    { category: "East Asian Street Food", name: "Melon Pan", price: "5.50", desc: "Japanese sweet bread covered in a crisp cookie dough crust.", img: getSafeImage("sweets", 48), isSignature: false },
    { category: "East Asian Street Food", name: "Korean Tteokbokki", price: "9.50", desc: "Spicy Korean stir-fried rice cakes in a fiery gochujang sauce.", img: getSafeImage("eastAsian", 49), isSignature: true },
    { category: "East Asian Street Food", name: "Hotteok", price: "6.50", desc: "Korean sweet pancakes filled with brown sugar, honey, chopped peanuts, and cinnamon.", img: getSafeImage("sweets", 50), isSignature: true },
    { category: "East Asian Street Food", name: "Gimbap", price: "8.50", desc: "Korean seaweed rice rolls filled with vegetables, egg, and meat.", img: getSafeImage("eastAsian", 51), isSignature: true },
    { category: "East Asian Street Food", name: "Korean Corn Dog", price: "7.50", desc: "A crispy, sugar-dusted corn dog, often half mozzarella and half sausage, coated in french fries.", img: getSafeImage("eastAsian", 52), isSignature: true },
    { category: "East Asian Street Food", name: "Eomuk", price: "6.00", desc: "Korean fish cakes served on skewers in a hot, savory broth.", img: getSafeImage("eastAsian", 53), isSignature: false },
    { category: "East Asian Street Food", name: "Odeng", price: "6.00", desc: "Another name for Korean fish cake skewers.", img: getSafeImage("eastAsian", 54), isSignature: false },
    { category: "East Asian Street Food", name: "Dakkochi", price: "8.50", desc: "Korean grilled chicken skewers glazed in a spicy-sweet sauce.", img: getSafeImage("eastAsian", 55), isSignature: false },
    { category: "East Asian Street Food", name: "Mandu", price: "7.50", desc: "Korean dumplings, steamed, boiled, or pan-fried.", img: getSafeImage("eastAsian", 56), isSignature: false },
    { category: "East Asian Street Food", name: "Bindaetteok", price: "9.00", desc: "Savory Korean mung bean pancakes, crispy and filling.", img: getSafeImage("eastAsian", 57), isSignature: false },
    { category: "East Asian Street Food", name: "Twigim", price: "8.00", desc: "Korean tempura-style deep-fried snacks (vegetables, squid, sweet potatoes).", img: getSafeImage("eastAsian", 58), isSignature: false },
    { category: "East Asian Street Food", name: "Sundae", price: "9.50", desc: "Korean blood sausage stuffed with cellophane noodles.", img: getSafeImage("eastAsian", 59), isSignature: true },
    { category: "East Asian Street Food", name: "Gyeranppang", price: "6.00", desc: "Korean 'egg bread': a sweet, fluffy oblong loaf with a whole egg baked inside.", img: getSafeImage("eastAsian", 60), isSignature: true },
    { category: "East Asian Street Food", name: "Dakgangjeong", price: "10.00", desc: "Crispy Korean fried chicken coated in a sticky, sweet, and spicy glaze.", img: getSafeImage("eastAsian", 61), isSignature: true },
    { category: "East Asian Street Food", name: "Tornado Potato", price: "7.00", desc: "A whole potato spiral-cut onto a skewer, deep-fried, and dusted with seasonings.", img: getSafeImage("eastAsian", 62), isSignature: false },

    // --- 6. SOUTHEAST ASIA ---
    { category: "Southeast Asian Street Food", name: "Vietnamese Bánh Mì", price: "9.50", desc: "A crispy French baguette loaded with Vietnamese pâté, meats, pickled veggies, and cilantro.", img: getSafeImage("seAsian", 0), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Bánh Xèo", price: "11.00", desc: "A crispy, sizzling Vietnamese crepe stuffed with pork, shrimp, and bean sprouts.", img: getSafeImage("seAsian", 1), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Bánh Tráng Nướng", price: "8.50", desc: "'Vietnamese Pizza': grilled rice paper topped with egg, pork, and scallions.", img: getSafeImage("seAsian", 2), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Gỏi Cuốn", price: "7.50", desc: "Fresh Vietnamese spring rolls wrapped in translucent rice paper with shrimp and herbs.", img: getSafeImage("seAsian", 3), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Chả Giò", price: "8.00", desc: "Vietnamese fried spring rolls, shattering crisp on the outside.", img: getSafeImage("seAsian", 4), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Bánh Bao", price: "7.00", desc: "Vietnamese steamed pork bun with a quail egg inside.", img: getSafeImage("seAsian", 5), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Bánh Cuốn", price: "9.00", desc: "Delicate Vietnamese steamed fermented rice batter rolls filled with ground pork.", img: getSafeImage("seAsian", 6), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Bánh Khọt", price: "8.50", desc: "Miniature Vietnamese crispy savory pancakes topped with a shrimp.", img: getSafeImage("seAsian", 7), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Bột Chiên", price: "9.00", desc: "Vietnamese fried rice flour cakes cooked with egg and scallions.", img: getSafeImage("seAsian", 8), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Nem Nướng", price: "10.00", desc: "Vietnamese grilled pork sausage skewers, often rolled in rice paper.", img: getSafeImage("seAsian", 9), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Cơm Tấm", price: "12.00", desc: "Vietnamese 'broken rice' served with grilled pork chops and a fried egg.", img: getSafeImage("seAsian", 10), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Xôi", price: "7.50", desc: "Vietnamese savory sticky rice topped with mung bean, chicken, or pork floss.", img: getSafeImage("seAsian", 11), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Phở Cups", price: "9.50", desc: "Vietnam's iconic beef noodle soup, served in a convenient street-style cup.", img: getSafeImage("seAsian", 12), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Thai Pad Thai", price: "11.50", desc: "Thailand's national dish: stir-fried rice noodles with egg, peanuts, sprouts, and lime.", img: getSafeImage("seAsian", 13), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Pad See Ew", price: "11.00", desc: "Thai stir-fried wide rice noodles in dark soy sauce with pork and Chinese broccoli.", img: getSafeImage("seAsian", 14), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Pad Kra Pao", price: "12.00", desc: "Spicy Thai holy basil stir-fry with minced pork, served over rice with a fried egg.", img: getSafeImage("seAsian", 15), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Som Tam", price: "9.00", desc: "Spicy, tart, and sweet Thai green papaya salad crushed in a mortar.", img: getSafeImage("seAsian", 16), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Moo Ping", price: "8.50", desc: "Thai grilled pork skewers marinated in coconut milk and garlic.", img: getSafeImage("seAsian", 17), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Gai Yang", price: "10.00", desc: "Thai street-style grilled chicken, marinated in lemongrass and fish sauce.", img: getSafeImage("seAsian", 18), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Sai Krok Isan", price: "9.50", desc: "Fermented, sour pork and rice sausage from Northeastern Thailand.", img: getSafeImage("seAsian", 19), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Khanom Buang", price: "7.00", desc: "Thai crispy crepes resembling tacos, filled with sweet meringue and egg yolk threads.", img: getSafeImage("sweets", 20), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Khanom Krok", price: "6.50", desc: "Tiny, sweet and savory Thai coconut milk pancakes.", img: getSafeImage("sweets", 21), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Roti Gluay", price: "7.50", desc: "Thai street pancake fried with banana and drizzled with condensed milk.", img: getSafeImage("sweets", 22), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Mango Sticky Rice", price: "8.50", desc: "Classic Thai dessert of sweet coconut sticky rice topped with fresh, ripe mango.", img: getSafeImage("sweets", 23), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Thai Fried Chicken", price: "9.50", desc: "Crispy Thai fried chicken topped with fried shallots.", img: getSafeImage("seAsian", 24), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Boat Noodles", price: "10.00", desc: "Intense Thai noodle soup with a rich broth thickened with pig or cow blood.", img: getSafeImage("seAsian", 25), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Grilled Squid", price: "11.00", desc: "Whole Thai squid scored and grilled, served with a fiery seafood dipping sauce.", img: getSafeImage("seAsian", 26), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Fish Cakes", price: "8.00", desc: "Thai red curry fish cakes (Tod Mun Pla), fried and served with cucumber relish.", img: getSafeImage("seAsian", 27), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Satay", price: "9.00", desc: "Southeast Asian grilled meat skewers served with a rich peanut sauce.", img: getSafeImage("seAsian", 28), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Chicken Satay", price: "9.00", desc: "Grilled chicken skewers with peanut sauce.", img: getSafeImage("seAsian", 29), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Beef Satay", price: "9.50", desc: "Grilled beef skewers with peanut sauce.", img: getSafeImage("seAsian", 30), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Nasi Goreng", price: "10.50", desc: "Indonesian sweet and spicy fried rice, topped with a fried egg.", img: getSafeImage("seAsian", 31), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Mie Goreng", price: "10.50", desc: "Indonesian stir-fried noodles with a sweet soy sauce glaze.", img: getSafeImage("seAsian", 32), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Martabak", price: "11.00", desc: "Indonesian stuffed pan-fried bread, loaded with minced meat and eggs.", img: getSafeImage("seAsian", 33), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Martabak Manis", price: "10.00", desc: "The sweet version of Martabak: a thick, buttery pancake stuffed with chocolate and peanuts.", img: getSafeImage("sweets", 34), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Bakso", price: "9.50", desc: "Indonesian meatball soup served with noodles and sambal.", img: getSafeImage("seAsian", 35), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Pempek", price: "10.00", desc: "Indonesian savory fishcake delicacy, deep-fried and served with a rich sweet and sour sauce.", img: getSafeImage("seAsian", 36), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Siomay", price: "9.00", desc: "Indonesian steamed fish dumplings served with peanut sauce.", img: getSafeImage("seAsian", 37), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Batagor", price: "9.50", desc: "Fried version of Siomay (fried fish dumplings) served with peanut sauce.", img: getSafeImage("seAsian", 38), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Nasi Uduk", price: "11.00", desc: "Indonesian coconut rice served with fried chicken, tempeh, and sambal.", img: getSafeImage("seAsian", 39), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Nasi Kuning", price: "11.00", desc: "Festive Indonesian yellow rice colored with turmeric.", img: getSafeImage("seAsian", 40), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Soto Ayam", price: "9.50", desc: "Indonesian yellow spicy chicken soup with vermicelli.", img: getSafeImage("seAsian", 41), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Ayam Goreng", price: "10.50", desc: "Indonesian-style fried chicken, rich in turmeric and galangal.", img: getSafeImage("seAsian", 42), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Pisang Goreng", price: "6.50", desc: "Indonesian deep-fried banana fritters.", img: getSafeImage("sweets", 43), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Otak-Otak", price: "8.00", desc: "Grilled fish cake wrapped in a banana leaf.", img: getSafeImage("seAsian", 44), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Kerak Telor", price: "9.00", desc: "Jakarta's traditional spicy omelet made with glutinous rice and dried shrimp.", img: getSafeImage("seAsian", 45), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Serabi", price: "7.00", desc: "Indonesian traditional pancake made from rice flour and coconut milk.", img: getSafeImage("sweets", 46), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Roti Bakar", price: "7.50", desc: "Indonesian thick toast heavily slathered with chocolate, cheese, or jam.", img: getSafeImage("sweets", 47), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Malaysian Roti Canai", price: "7.00", desc: "Flaky, buttery Malaysian flatbread served with dhal curry.", img: getSafeImage("seAsian", 48), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Murtabak", price: "10.00", desc: "Stuffed pancake or pan-fried bread filled with minced meat, popular in Malaysia.", img: getSafeImage("seAsian", 49), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Nasi Lemak", price: "11.50", desc: "Malaysia's national dish: fragrant coconut rice served with spicy sambal, anchovies, and egg.", img: getSafeImage("seAsian", 50), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Char Kway Teow", price: "12.00", desc: "Malaysian/Singaporean stir-fried flat rice noodles cooked over intense wok hei (breath of the wok).", img: getSafeImage("seAsian", 51), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Hokkien Mee", price: "11.50", desc: "Rich noodle dish simmered in a dark, fragrant soy sauce or prawn broth.", img: getSafeImage("seAsian", 52), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Curry Puff", price: "6.00", desc: "Deep-fried crescent-shaped pastry filled with curried potatoes and chicken.", img: getSafeImage("seAsian", 53), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Apam Balik", price: "7.00", desc: "Malaysian sweet folded pancake filled with crushed peanuts, sugar, and sweet corn.", img: getSafeImage("sweets", 54), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Lok Lok", price: "9.00", desc: "Assorted foods on skewers dipped in boiling broth or deep-fried.", img: getSafeImage("seAsian", 55), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Ramly Burger", price: "10.00", desc: "Malaysia's iconic street burger: patty wrapped in a thin egg omelet and drenched in sauces.", img: getSafeImage("seAsian", 56), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Satay Celup", price: "10.50", desc: "Skewers of raw or semi-cooked food dipped into a boiling pot of satay gravy.", img: getSafeImage("seAsian", 57), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Assam Laksa", price: "11.00", desc: "Penang's famous tart, sour, and spicy fish-based noodle soup.", img: getSafeImage("seAsian", 58), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Penang Laksa", price: "11.00", desc: "Another name for the intensely flavorful Assam Laksa.", img: getSafeImage("seAsian", 59), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Singapore Hainanese Chicken Rice", price: "12.50", desc: "Singapore's national dish: gently poached chicken served with fragrant rice cooked in chicken broth.", img: getSafeImage("seAsian", 60), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Singapore Chili Crab Buns", price: "11.00", desc: "Fried mantou buns served with Singapore's famous sweet, savory, and spicy chili crab sauce.", img: getSafeImage("seAsian", 61), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Kaya Toast", price: "7.00", desc: "Singaporean breakfast staple: toasted bread thickly spread with sweet coconut jam (kaya) and butter.", img: getSafeImage("sweets", 62), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Laksa", price: "11.50", desc: "Spicy noodle soup with a rich, coconut milk curry broth.", img: getSafeImage("seAsian", 63), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Carrot Cake", price: "9.00", desc: "Singaporean savory dish of stir-fried radish cake cubes with egg and preserved radish (Chai Tow Kway).", img: getSafeImage("seAsian", 64), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Popiah", price: "8.00", desc: "Fresh spring roll filled with finely grated turnip, jicama, and peanuts.", img: getSafeImage("seAsian", 65), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Rojak", price: "8.50", desc: "Traditional fruit and vegetable salad dish topped with a sticky shrimp paste dressing and crushed peanuts.", img: getSafeImage("seAsian", 66), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Mee Goreng", price: "10.00", desc: "Spicy fried noodle dish.", img: getSafeImage("seAsian", 67), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Fishball Noodles", price: "9.50", desc: "Noodles served dry or in soup, topped with bouncy fishballs.", img: getSafeImage("seAsian", 68), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Filipino Isaw", price: "7.00", desc: "Filipino street food classic: barbecued pig or chicken intestines on a skewer.", img: getSafeImage("seAsian", 69), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Kwek-Kwek", price: "6.00", desc: "Hard-boiled quail eggs coated in an orange batter and deep-fried.", img: getSafeImage("seAsian", 70), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Tokneneng", price: "6.50", desc: "Similar to Kwek-Kwek, but using regular chicken eggs in the orange batter.", img: getSafeImage("seAsian", 71), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Squid Balls", price: "6.00", desc: "Deep-fried balls of squid paste on a stick.", img: getSafeImage("seAsian", 72), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Kikiam", price: "6.50", desc: "Fried rolls of minced pork and vegetables wrapped in bean curd skin.", img: getSafeImage("seAsian", 73), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Banana Cue", price: "5.00", desc: "Deep-fried Saba bananas coated in caramelized brown sugar on a skewer.", img: getSafeImage("sweets", 74), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Camote Cue", price: "5.00", desc: "Deep-fried sweet potatoes coated in caramelized brown sugar.", img: getSafeImage("sweets", 75), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Turon", price: "5.50", desc: "Banana and jackfruit rolled in a spring roll wrapper and fried with a sugar glaze.", img: getSafeImage("sweets", 76), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Taho", price: "5.00", desc: "Warm silken tofu mixed with arnibal (brown sugar syrup) and sago pearls.", img: getSafeImage("sweets", 77), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Balut", price: "8.00", desc: "The famous, controversial fertilized duck egg, boiled and eaten from the shell.", img: getSafeImage("seAsian", 78), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Sisig", price: "12.00", desc: "Sizzling platter of chopped pork face and ears, seasoned with calamansi and chili.", img: getSafeImage("seAsian", 79), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Pork Barbecue", price: "8.50", desc: "Filipino-style sweet and savory pork skewers grilled over charcoal.", img: getSafeImage("seAsian", 80), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Chicken Inasal", price: "11.00", desc: "Bacolod-style grilled chicken marinated in calamansi, pepper, and annatto.", img: getSafeImage("seAsian", 81), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Lumpia", price: "7.00", desc: "Filipino spring rolls, tightly wrapped and fried until crispy.", img: getSafeImage("seAsian", 82), isSignature: false },
    { category: "Southeast Asian Street Food", name: "Empanada Ilocos", price: "8.50", desc: "A bright orange, crispy empanada stuffed with longganisa, egg, and papaya.", img: getSafeImage("seAsian", 83), isSignature: true },
    { category: "Southeast Asian Street Food", name: "Pancit Habhab", price: "9.00", desc: "Noodles from Lucban eaten directly from a banana leaf without utensils.", img: getSafeImage("seAsian", 84), isSignature: false },

    // --- 7. EUROPE (WESTERN) ---
    { category: "Western European Street Food", name: "Belgian Fries", price: "7.00", desc: "Thick, double-fried Belgian frites served in a paper cone with a dollop of mayonnaise.", img: getSafeImage("europe", 0), isSignature: true },
    { category: "Western European Street Food", name: "Moules Frites Cups", price: "14.00", desc: "Mussels steamed in white wine, served in a cup over crispy Belgian fries.", img: getSafeImage("europe", 1), isSignature: true },
    { category: "Western European Street Food", name: "Belgian Waffles", price: "8.00", desc: "Classic thick waffles, crispy outside and fluffy inside.", img: getSafeImage("sweets", 2), isSignature: false },
    { category: "Western European Street Food", name: "Liège Waffles", price: "9.00", desc: "Dense, chewy Belgian waffles caramelized with chunks of pearl sugar.", img: getSafeImage("sweets", 3), isSignature: true },
    { category: "Western European Street Food", name: "Brussels Waffles", price: "8.50", desc: "Lighter, rectangular waffles dusted with powdered sugar.", img: getSafeImage("sweets", 4), isSignature: false },
    { category: "Western European Street Food", name: "French Crêpes", price: "8.00", desc: "Thin French pancakes folded over sweet or savory fillings.", img: getSafeImage("sweets", 5), isSignature: true },
    { category: "Western European Street Food", name: "Galettes", price: "10.00", desc: "Savory buckwheat crepes from Brittany, typically filled with ham, cheese, and egg.", img: getSafeImage("europe", 6), isSignature: true },
    { category: "Western European Street Food", name: "Croque Monsieur", price: "11.00", desc: "The ultimate French grilled ham and cheese sandwich, smothered in béchamel.", img: getSafeImage("europe", 7), isSignature: true },
    { category: "Western European Street Food", name: "Jambon-Beurre", price: "9.50", desc: "A simple, perfect Parisian street sandwich: crusty baguette, good butter, and ham.", img: getSafeImage("europe", 8), isSignature: false },
    { category: "Western European Street Food", name: "Socca", price: "8.00", desc: "Nice's famous thin, unleavened chickpea flour pancake, baked in a wood oven.", img: getSafeImage("europe", 9), isSignature: true },
    { category: "Western European Street Food", name: "Pan Bagnat", price: "12.00", desc: "A Niçoise salad inside a crusty bun, heavily drenched in olive oil.", img: getSafeImage("europe", 10), isSignature: false },
    { category: "Western European Street Food", name: "Spanish Bocadillo de Calamares", price: "12.50", desc: "Madrid's famous fried squid ring sandwich.", img: getSafeImage("europe", 11), isSignature: true },
    { category: "Western European Street Food", name: "Patatas Bravas", price: "8.50", desc: "Fried potato cubes smothered in a spicy red 'bravas' sauce.", img: getSafeImage("europe", 12), isSignature: true },
    { category: "Western European Street Food", name: "Churros con Chocolate", price: "9.00", desc: "Spanish fried dough sticks served with a cup of thick, dark chocolate for dipping.", img: getSafeImage("sweets", 13), isSignature: true },
    { category: "Western European Street Food", name: "Pinchos", price: "7.00", desc: "Small snacks spiked to a piece of bread with a toothpick, typical in bars.", img: getSafeImage("europe", 14), isSignature: false },
    { category: "Western European Street Food", name: "Pintxos", price: "7.50", desc: "Basque version of Pinchos, elevated and incredibly diverse bar snacks.", img: getSafeImage("europe", 15), isSignature: true },
    { category: "Western European Street Food", name: "Empanadas Gallegas", price: "11.00", desc: "A large, flat savory pie from Galicia, usually filled with tuna or meat.", img: getSafeImage("europe", 16), isSignature: false },
    { category: "Western European Street Food", name: "Tortilla Española Sandwich", price: "10.00", desc: "A thick Spanish potato and egg omelet served inside a crusty baguette.", img: getSafeImage("europe", 17), isSignature: true },
    { category: "Western European Street Food", name: "Italian Pizza al Taglio", price: "8.00", desc: "Rectangular Roman street pizza sold by the slice (by weight).", img: getSafeImage("europe", 18), isSignature: true },
    { category: "Western European Street Food", name: "Pizza Fritta", price: "11.00", desc: "Neapolitan deep-fried pizza dough stuffed with ricotta and pork cracklings.", img: getSafeImage("europe", 19), isSignature: true },
    { category: "Western European Street Food", name: "Arancini", price: "9.00", desc: "Sicilian golden-fried rice balls stuffed with a rich meat ragù and peas.", img: getSafeImage("europe", 20), isSignature: true },
    { category: "Western European Street Food", name: "Supplì", price: "8.00", desc: "Roman elongated fried rice croquettes filled with a melting core of mozzarella.", img: getSafeImage("europe", 21), isSignature: true },
    { category: "Western European Street Food", name: "Panzerotti", price: "9.50", desc: "Apulian small, deep-fried pockets of dough filled with molten tomato and cheese.", img: getSafeImage("europe", 22), isSignature: false },
    { category: "Western European Street Food", name: "Piadina", price: "10.50", desc: "A thin Italian flatbread sandwich from Romagna, filled with prosciutto and cheese.", img: getSafeImage("europe", 23), isSignature: true },
    { category: "Western European Street Food", name: "Porchetta Sandwich", price: "12.50", desc: "A crusty roll filled with rich, fatty, herb-roasted Italian pork.", img: getSafeImage("europe", 24), isSignature: true },
    { category: "Western European Street Food", name: "Lampredotto", price: "11.00", desc: "The ultimate Florentine street food: stewed cow stomach in a crusty roll.", img: getSafeImage("europe", 25), isSignature: true },
    { category: "Western European Street Food", name: "Focaccia", price: "7.00", desc: "Soft, dimpled Italian flatbread drenched in olive oil.", img: getSafeImage("europe", 26), isSignature: false },
    { category: "Western European Street Food", name: "Farinata", price: "8.00", desc: "Ligurian savory chickpea flour pancake baked until crispy.", img: getSafeImage("europe", 27), isSignature: false },
    { category: "Western European Street Food", name: "Olive Ascolane", price: "10.00", desc: "Large green olives stuffed with meat, breaded, and deep-fried.", img: getSafeImage("europe", 28), isSignature: true },
    { category: "Western European Street Food", name: "German Currywurst", price: "9.50", desc: "Iconic Berlin street food: sliced sausage drenched in curry-spiced ketchup.", img: getSafeImage("europe", 29), isSignature: true },
    { category: "Western European Street Food", name: "Bratwurst", price: "8.50", desc: "Classic German grilled pork sausage served in a crusty roll with mustard.", img: getSafeImage("europe", 30), isSignature: true },
    { category: "Western European Street Food", name: "Bockwurst", price: "8.50", desc: "A mildly flavored German sausage, typically simmered, not grilled.", img: getSafeImage("europe", 31), isSignature: false },
    { category: "Western European Street Food", name: "Leberkäse Semmel", price: "9.00", desc: "Bavarian street food: a thick slice of baked meatloaf served in a bun.", img: getSafeImage("europe", 32), isSignature: true },
    { category: "Western European Street Food", name: "Pretzel", price: "6.00", desc: "Large, soft, lye-dipped German pretzel encrusted with coarse salt.", img: getSafeImage("europe", 33), isSignature: true },
    { category: "Western European Street Food", name: "Kartoffelpuffer", price: "8.00", desc: "German shallow-fried potato pancakes, often served with applesauce.", img: getSafeImage("europe", 34), isSignature: false },
    { category: "Western European Street Food", name: "Fischbrötchen", price: "10.50", desc: "Northern German sandwich made with fresh or pickled fish and onions.", img: getSafeImage("europe", 35), isSignature: true },
    { category: "Western European Street Food", name: "Dutch Stroopwafel", price: "7.00", desc: "Two thin waffles pressed together with a layer of sweet caramel syrup.", img: getSafeImage("sweets", 36), isSignature: true },
    { category: "Western European Street Food", name: "Poffertjes", price: "8.00", desc: "Miniature, fluffy Dutch pancakes served with a lump of butter and powdered sugar.", img: getSafeImage("sweets", 37), isSignature: true },
    { category: "Western European Street Food", name: "Patat", price: "7.50", desc: "Dutch fries, served in a cone and famously drowned in mayonnaise or peanut sauce.", img: getSafeImage("europe", 38), isSignature: false },
    { category: "Western European Street Food", name: "Bitterballen", price: "9.00", desc: "Dutch deep-fried, crispy meatballs filled with a thick, savory ragout.", img: getSafeImage("europe", 39), isSignature: true },
    { category: "Western European Street Food", name: "Kroket", price: "8.50", desc: "A cylindrical version of the bitterbal, often eaten in a soft bun.", img: getSafeImage("europe", 40), isSignature: false },
    { category: "Western European Street Food", name: "Frikandel", price: "8.00", desc: "A skinless, deep-fried minced meat sausage from the Netherlands.", img: getSafeImage("europe", 41), isSignature: false },
    { category: "Western European Street Food", name: "Kibbeling", price: "11.00", desc: "Dutch chunks of battered and deep-fried white fish, served with a garlic sauce.", img: getSafeImage("europe", 42), isSignature: true },
    { category: "Western European Street Food", name: "Herring Sandwich", price: "10.00", desc: "Raw Dutch herring served in a soft bun with chopped raw onions.", img: getSafeImage("europe", 43), isSignature: true },

    // --- 8. EUROPE (EASTERN & BALKANS) ---
    { category: "Eastern Europe & Balkans", name: "Polish Zapiekanka", price: "9.50", desc: "Poland's beloved open-faced baguette topped with mushrooms, cheese, and ketchup.", img: getSafeImage("balkans", 0), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Pierogi", price: "10.00", desc: "Polish dumplings filled with potatoes and cheese, meat, or fruit.", img: getSafeImage("balkans", 1), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Obwarzanek", price: "5.00", desc: "Kraków's braided ring-shaped bread, boiled then baked.", img: getSafeImage("balkans", 2), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Oscypek", price: "8.50", desc: "Smoked cheese made of salted sheep milk from the Tatra Mountains, often grilled.", img: getSafeImage("balkans", 3), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Kielbasa", price: "9.00", desc: "Classic Polish grilled sausage served with mustard and bread.", img: getSafeImage("balkans", 4), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Hungarian Lángos", price: "9.50", desc: "Deep-fried flatbread rubbed with garlic, smothered in sour cream and grated cheese.", img: getSafeImage("balkans", 5), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Kürtőskalács", price: "8.00", desc: "Hungarian chimney cake, spun around a spit, baked, and coated in sugar and walnuts.", img: getSafeImage("sweets", 6), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Kolbász", price: "9.50", desc: "Hungarian spiced sausage rich in paprika.", img: getSafeImage("balkans", 7), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Pogácsa", price: "6.00", desc: "Small, savory Hungarian biscuits, often flavored with cheese or pork cracklings.", img: getSafeImage("balkans", 8), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Czech Trdelník", price: "8.50", desc: "Czech variant of the chimney cake, extremely popular in Prague streets.", img: getSafeImage("sweets", 9), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Klobása", price: "9.00", desc: "Czech grilled sausage sold from street stalls.", img: getSafeImage("balkans", 10), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Smažený Sýr", price: "10.50", desc: "Czech thick slice of breaded and deep-fried cheese, served with tartar sauce.", img: getSafeImage("balkans", 11), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Bramborák", price: "8.00", desc: "Czech crispy fried potato pancakes flavored with garlic and marjoram.", img: getSafeImage("balkans", 12), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Romanian Mici", price: "11.00", desc: "Skinless grilled sausages made of beef, lamb, and pork, rich in garlic.", img: getSafeImage("balkans", 13), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Covrigi", price: "4.50", desc: "Romanian pretzels, baked fresh and topped with salt, sesame, or poppy seeds.", img: getSafeImage("balkans", 14), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Langos Romanian Style", price: "9.00", desc: "Romanian take on the fried dough, often stuffed with cheese.", img: getSafeImage("balkans", 15), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Plăcintă", price: "7.50", desc: "Traditional Romanian pastry, pan-fried and filled with cheese or apples.", img: getSafeImage("balkans", 16), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Bulgarian Banitsa", price: "8.00", desc: "Flaky pastry pie made with layers of phyllo dough and a mixture of eggs and sirene cheese.", img: getSafeImage("balkans", 17), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Kebapche", price: "9.50", desc: "Bulgarian elongated grilled minced meat, strongly flavored with cumin.", img: getSafeImage("balkans", 18), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Serbian Pljeskavica", price: "11.50", desc: "The ultimate Balkan burger: a massive, spiced meat patty served in lepinja bread with kajmak.", img: getSafeImage("balkans", 19), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Ćevapi", price: "11.00", desc: "Skinless grilled meat sausages served in flatbread with chopped onions.", img: getSafeImage("balkans", 20), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Burek", price: "8.50", desc: "Flaky, greasy, and incredibly satisfying phyllo pastry filled with meat or cheese.", img: getSafeImage("balkans", 21), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Komplet Lepinja", price: "12.00", desc: "A heavy, calorie-dense flatbread soaked in meat drippings, baked with an egg and kajmak.", img: getSafeImage("balkans", 22), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Karađorđeva Street Sandwich", price: "13.00", desc: "Breaded and fried rolled meat stuffed with kajmak, served in a bun.", img: getSafeImage("balkans", 23), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Roštiljska Kobasica", price: "10.00", desc: "Spicy Serbian grilled sausage.", img: getSafeImage("balkans", 24), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Uštipci", price: "8.00", desc: "Fried dough balls, eaten savory with cheese or sweet with jam.", img: getSafeImage("balkans", 25), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Mekike", price: "7.50", desc: "Balkan deep-fried dough, similar to a doughnut, usually eaten for breakfast.", img: getSafeImage("balkans", 26), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Croatian Ćevapi", price: "11.00", desc: "Croatian style skinless meat sausages.", img: getSafeImage("balkans", 27), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Fritule", price: "7.00", desc: "Croatian festive sweet fried dough balls flavored with citrus and raisins.", img: getSafeImage("sweets", 28), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Soparnik", price: "9.50", desc: "Dalmatian savory pie filled with Swiss chard and baked in an open fire.", img: getSafeImage("balkans", 29), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Bosnian Ćevapi", price: "11.50", desc: "The iconic Sarajevo ćevapi, served in somun bread that has been steamed over the grill.", img: getSafeImage("balkans", 30), isSignature: true },
    { category: "Eastern Europe & Balkans", name: "Zeljanica", price: "8.50", desc: "Bosnian savory pie (pita) filled with spinach and cheese.", img: getSafeImage("balkans", 31), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Sirnica", price: "8.50", desc: "Bosnian savory pie (pita) filled solely with cheese.", img: getSafeImage("balkans", 32), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Albanian Byrek", price: "8.00", desc: "Albanian version of the phyllo pastry pie.", img: getSafeImage("balkans", 33), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Qofte", price: "9.50", desc: "Albanian seasoned meatballs, often fried or grilled.", img: getSafeImage("balkans", 34), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Petulla", price: "7.00", desc: "Albanian fried dough, eaten sweet or savory.", img: getSafeImage("balkans", 35), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Macedonian Burek", price: "8.50", desc: "Macedonian style meat or cheese pie.", img: getSafeImage("balkans", 36), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Kebapi", price: "11.00", desc: "Macedonian grilled skinless sausages.", img: getSafeImage("balkans", 37), isSignature: false },
    { category: "Eastern Europe & Balkans", name: "Pastrmajlija", price: "10.50", desc: "Macedonian oval-shaped bread pie topped with cubed pork and egg.", img: getSafeImage("balkans", 38), isSignature: true },

    // --- 9. CAUCASUS & RUSSIA ---
    { category: "Caucasus & Russia", name: "Georgian Khachapuri", price: "12.00", desc: "The famous Georgian cheese bread.", img: getSafeImage("balkans", 39), isSignature: true },
    { category: "Caucasus & Russia", name: "Adjarian Khachapuri", price: "13.50", desc: "A boat-shaped cheese bread crowned with a raw egg yolk and a generous slice of butter.", img: getSafeImage("balkans", 40), isSignature: true },
    { category: "Caucasus & Russia", name: "Lobiani", price: "10.00", desc: "Georgian bread baked with a savory, spiced kidney bean filling.", img: getSafeImage("balkans", 41), isSignature: false },
    { category: "Caucasus & Russia", name: "Kubdari", price: "12.00", desc: "Georgian Svaneti meat pie filled with chunks of spiced beef or pork.", img: getSafeImage("balkans", 42), isSignature: true },
    { category: "Caucasus & Russia", name: "Churchkhela", price: "8.00", desc: "Georgian candle-shaped candy made of walnuts dipped in thickened grape juice.", img: getSafeImage("sweets", 43), isSignature: true },
    { category: "Caucasus & Russia", name: "Armenian Lahmajoun", price: "9.00", desc: "Armenian flatbread topped with minced meat, distinct for its thinness.", img: getSafeImage("balkans", 44), isSignature: false },
    { category: "Caucasus & Russia", name: "Jingalov Hats", price: "10.00", desc: "Armenian flatbread stuffed with a mix of dozens of finely diced wild herbs.", img: getSafeImage("balkans", 45), isSignature: true },
    { category: "Caucasus & Russia", name: "Gata", price: "7.50", desc: "Armenian sweet pastry or sweet bread.", img: getSafeImage("sweets", 46), isSignature: false },
    { category: "Caucasus & Russia", name: "Russian Pirozhki", price: "8.00", desc: "Small Russian baked or fried buns filled with meat, cabbage, or potatoes.", img: getSafeImage("balkans", 47), isSignature: true },
    { category: "Caucasus & Russia", name: "Blini", price: "9.00", desc: "Russian thin pancakes, served with sour cream, jam, or caviar.", img: getSafeImage("balkans", 48), isSignature: true },
    { category: "Caucasus & Russia", name: "Chebureki", price: "8.50", desc: "Deep-fried turnover with a filling of minced meat and onions.", img: getSafeImage("balkans", 49), isSignature: true },
    { category: "Caucasus & Russia", name: "Pelmeni Cups", price: "11.00", desc: "Russian meat dumplings served in a cup with broth and sour cream.", img: getSafeImage("balkans", 50), isSignature: true },
    { category: "Caucasus & Russia", name: "Ukrainian Pyrizhky", price: "8.00", desc: "Ukrainian individual-sized baked or fried buns.", img: getSafeImage("balkans", 51), isSignature: false },
    { category: "Caucasus & Russia", name: "Varenyky", price: "10.50", desc: "Ukrainian dumplings filled with potatoes, cheese, or sour cherries.", img: getSafeImage("balkans", 52), isSignature: true },

    // --- 10. NORTH AMERICA & OCEANIA ---
    { category: "North America & Oceania", name: "Canadian Poutine", price: "12.00", desc: "The Canadian classic: French fries topped with fresh cheese curds and smothered in hot brown gravy.", img: getSafeImage("naAmerica", 0), isSignature: true },
    { category: "North America & Oceania", name: "Montreal Smoked Meat Sandwich", price: "15.00", desc: "Piled high layers of cured, smoked beef brisket on rye bread with mustard.", img: getSafeImage("naAmerica", 1), isSignature: true },
    { category: "North America & Oceania", name: "BeaverTails", price: "8.00", desc: "Canadian fried dough pastries, stretched to resemble a beaver's tail and topped with sweets.", img: getSafeImage("sweets", 2), isSignature: true },
    { category: "North America & Oceania", name: "Halifax Donair", price: "13.00", desc: "Spiced meat roasted on a spit, served in a pita with tomatoes, onions, and a sweet garlic sauce.", img: getSafeImage("naAmerica", 3), isSignature: true },
    { category: "North America & Oceania", name: "American Hot Dog", price: "7.00", desc: "Classic American street cart hot dog with mustard and ketchup.", img: getSafeImage("naAmerica", 4), isSignature: false },
    { category: "North America & Oceania", name: "New York Hot Dog", price: "8.00", desc: "Topped with sauerkraut, sweet onion relish, and spicy brown mustard.", img: getSafeImage("naAmerica", 5), isSignature: true },
    { category: "North America & Oceania", name: "Chicago Hot Dog", price: "9.00", desc: "An all-beef frank 'dragged through the garden' – loaded with neon relish, peppers, and celery salt.", img: getSafeImage("naAmerica", 6), isSignature: true },
    { category: "North America & Oceania", name: "Corn Dog", price: "7.50", desc: "A sausage coated in a thick layer of cornmeal batter and deep-fried on a stick.", img: getSafeImage("naAmerica", 7), isSignature: false },
    { category: "North America & Oceania", name: "Cheesesteak", price: "14.00", desc: "Thinly sliced steak and melted cheese in a hoagie roll.", img: getSafeImage("naAmerica", 8), isSignature: false },
    { category: "North America & Oceania", name: "Philly Cheesesteak", price: "15.00", desc: "The original Philadelphia sandwich loaded with steak, onions, and Cheez Whiz.", img: getSafeImage("naAmerica", 9), isSignature: true },
    { category: "North America & Oceania", name: "Lobster Roll", price: "24.00", desc: "New England delicacy: chunks of sweet lobster meat served in a buttered, toasted hot dog bun.", img: getSafeImage("naAmerica", 10), isSignature: true },
    { category: "North America & Oceania", name: "Po’ Boy", price: "14.50", desc: "Louisiana submarine sandwich, typically filled with crispy fried shrimp or oysters.", img: getSafeImage("naAmerica", 11), isSignature: true },
    { category: "North America & Oceania", name: "New Orleans Muffuletta", price: "16.00", desc: "A massive round sandwich layered with Italian cold cuts, cheese, and olive salad.", img: getSafeImage("naAmerica", 12), isSignature: true },
    { category: "North America & Oceania", name: "New York Pizza Slice", price: "6.00", desc: "A wide, foldable slice of thin-crust pizza, dripping with cheese.", img: getSafeImage("naAmerica", 13), isSignature: true },
    { category: "North America & Oceania", name: "Funnel Cake", price: "8.50", desc: "American fairground classic of overlapping batter ribbons deep-fried and powdered with sugar.", img: getSafeImage("sweets", 14), isSignature: true },
    { category: "North America & Oceania", name: "Corn on the Cob", price: "5.00", desc: "Roasted sweet corn served on a stick with butter.", img: getSafeImage("naAmerica", 15), isSignature: false },
    { category: "North America & Oceania", name: "Pulled Pork Sandwich", price: "13.00", desc: "Southern BBQ favorite: slow-smoked, shredded pork shoulder in a sweet and tangy sauce.", img: getSafeImage("naAmerica", 16), isSignature: true },
    { category: "North America & Oceania", name: "BBQ Brisket Sandwich", price: "15.00", desc: "Texas-style smoked brisket, incredibly tender, served on a soft bun.", img: getSafeImage("naAmerica", 17), isSignature: true },
    { category: "North America & Oceania", name: "Fried Chicken Sandwich", price: "12.50", desc: "A massive, crispy, buttermilk-marinated fried chicken breast with pickles.", img: getSafeImage("naAmerica", 18), isSignature: true },
    { category: "North America & Oceania", name: "Chicken Wings", price: "11.00", desc: "Deep-fried wings tossed in a fiery Buffalo sauce, served with blue cheese dip.", img: getSafeImage("naAmerica", 19), isSignature: false },
    { category: "North America & Oceania", name: "Loaded Fries", price: "10.00", desc: "Fries buried under melted cheese, bacon bits, and sour cream.", img: getSafeImage("naAmerica", 20), isSignature: false },
    { category: "North America & Oceania", name: "Chili Cheese Fries", price: "11.50", desc: "Fries topped with a hearty, meaty chili and nacho cheese.", img: getSafeImage("naAmerica", 21), isSignature: false },
    { category: "North America & Oceania", name: "Grilled Cheese", price: "8.00", desc: "A buttery, crispy sandwich melting with American cheese.", img: getSafeImage("naAmerica", 22), isSignature: false },
    { category: "North America & Oceania", name: "Smash Burger", price: "12.00", desc: "A beef patty smashed thinly onto a hot griddle for maximum crust.", img: getSafeImage("naAmerica", 23), isSignature: true },
    { category: "North America & Oceania", name: "Cheeseburger", price: "11.00", desc: "Classic American cheeseburger.", img: getSafeImage("naAmerica", 24), isSignature: false },
    { category: "North America & Oceania", name: "Bacon Cheeseburger", price: "13.50", desc: "Cheeseburger topped with thick-cut crispy bacon.", img: getSafeImage("naAmerica", 25), isSignature: false },
    { category: "North America & Oceania", name: "Sloppy Joe", price: "10.50", desc: "A messy, glorious sandwich of ground beef simmered in a sweet tomato sauce.", img: getSafeImage("naAmerica", 26), isSignature: false },
    { category: "North America & Oceania", name: "Pastrami Sandwich", price: "14.50", desc: "New York deli icon: heavily smoked and spiced beef layered on rye.", img: getSafeImage("naAmerica", 27), isSignature: true },
    { category: "North America & Oceania", name: "Cuban Sandwich", price: "13.00", desc: "Pressed sandwich made with ham, roasted pork, Swiss cheese, pickles, and mustard.", img: getSafeImage("naAmerica", 28), isSignature: true },
    { category: "North America & Oceania", name: "Reuben Sandwich", price: "14.00", desc: "Corned beef, Swiss cheese, sauerkraut, and Russian dressing, grilled between slices of rye.", img: getSafeImage("naAmerica", 29), isSignature: true },
    { category: "North America & Oceania", name: "Bagel with Cream Cheese", price: "6.00", desc: "A New York boiled-then-baked bagel smeared generously with cream cheese.", img: getSafeImage("naAmerica", 30), isSignature: false },
    { category: "North America & Oceania", name: "Breakfast Burrito", price: "11.00", desc: "A flour tortilla stuffed with eggs, potatoes, cheese, and bacon or sausage.", img: getSafeImage("naAmerica", 31), isSignature: false },
    { category: "North America & Oceania", name: "Aussie Meat Pie", price: "10.00", desc: "Australia's national snack: a hand-sized pie filled with minced meat and gravy.", img: getSafeImage("naAmerica", 32), isSignature: true },
    { category: "North America & Oceania", name: "Sausage Roll", price: "8.50", desc: "Sausage meat wrapped in flaky puff pastry.", img: getSafeImage("naAmerica", 33), isSignature: false },
    { category: "North America & Oceania", name: "Chiko Roll", price: "9.00", desc: "Australian deep-fried roll inspired by the spring roll, filled with mutton and cabbage.", img: getSafeImage("naAmerica", 34), isSignature: true },
    { category: "North America & Oceania", name: "Potato Scallops", price: "6.50", desc: "Thick slices of potato, battered and deep-fried.", img: getSafeImage("naAmerica", 35), isSignature: false },
    { category: "North America & Oceania", name: "Dim Sim", price: "7.00", desc: "Australian-Chinese meat and cabbage dumpling, often eaten deep-fried.", img: getSafeImage("naAmerica", 36), isSignature: false },
    { category: "North America & Oceania", name: "Halal Snack Pack", price: "14.00", desc: "A towering box of kebab meat, chips, and cheese, drowned in garlic and chili sauces.", img: getSafeImage("naAmerica", 37), isSignature: true },
    { category: "North America & Oceania", name: "New Zealand Meat Pie", price: "10.50", desc: "Kiwi-style pie, often featuring steak and cheese or mince and cheese.", img: getSafeImage("naAmerica", 38), isSignature: true },
    { category: "North America & Oceania", name: "Whitebait Fritter", price: "13.00", desc: "New Zealand delicacy of tiny, translucent fish fried into an egg omelet.", img: getSafeImage("naAmerica", 39), isSignature: true },
    { category: "North America & Oceania", name: "Māori Fry Bread", price: "8.00", desc: "Golden, deep-fried dough eaten plain or with golden syrup and butter.", img: getSafeImage("sweets", 40), isSignature: true }
  ]
};
// KRAJ FAJLA: src/DemoData/globalStreetFoodData.js