import { generateAiImage } from './v8AiVision.js';

const GYROS_SOUVLAKI = ["Gyros", "Chicken Gyros", "Pork Gyros", "Lamb Gyros", "Gyros Pita", "Souvlaki", "Chicken Souvlaki", "Pork Souvlaki", "Lamb Souvlaki", "Beef Souvlaki", "Souvlaki Pita", "Kalamaki", "Kontosouvli", "Pita Gyros", "Gyros Wrap", "Souvlaki Wrap", "Greek Chicken Wrap", "Greek Lamb Wrap", "Greek Pork Wrap", "Gyros Plate", "Souvlaki Plate", "Mixed Grill", "Greek Mixed Grill", "Meat Platter", "Loukaniko Sandwich", "Greek Sausage Pita", "Keftedes Pita", "Bifteki Pita", "Halloumi Pita", "Falafel Pita Greek Style", "Veggie Pita", "Greek Loaded Fries", "Gyros Loaded Fries", "Souvlaki Loaded Fries", "Feta Loaded Fries", "Gyros Sandwich", "Souvlaki Sandwich"];
const TRADITIONAL_MAINS = ["Moussaka", "Pastitsio", "Papoutsakia", "Gemista", "Lahanodolmades", "Giouvetsi", "Stifado", "Beef Stifado", "Rabbit Stifado", "Kleftiko", "Lamb Kleftiko", "Lamb Fricassée", "Arni Lemonato", "Arni Sto Fourno", "Lamb with Potatoes", "Kokkinisto", "Moschari Kokkinisto", "Sofrito", "Pastitsada", "Bekri Meze", "Tigania", "Pork Tigania", "Chicken Tigania", "Soutzoukaki", "Kokoretsi", "Gardoumba", "Exohiko", "Apaki", "Syglino", "Bifteki", "Bifteki Gemisto", "Keftedes", "Soutzoukakia", "Loukaniko", "Spetsofai", "Greek Meatballs", "Keftedakia", "Fried Keftedes", "Grilled Bifteki", "Feta-Stuffed Bifteki", "Lamb Chops", "Paidakia", "Grilled Pork Chops", "Grilled Chicken", "Lemon Chicken", "Chicken with Potatoes", "Kotopoulo Lemonato", "Kotopoulo Sto Fourno", "Roast Lamb", "Roast Goat", "Katsiki Sto Fourno", "Pork with Celery", "Pork Lemonato", "Pork with Leeks", "Makaronia me Kima", "Greek Spaghetti with Meat Sauce", "Gamopilafo", "Antikristo", "Cretan Lamb"];
const MEZE_STARTERS = ["Saganaki", "Cheese Saganaki", "Feta Saganaki", "Halloumi", "Grilled Halloumi", "Feta Cheese", "Baked Feta", "Feta Psiti", "Bouyiourdi", "Tirokafteri", "Tzatziki", "Taramosalata", "Melitzanosalata", "Skordalia", "Fava", "Hummus Greek Style", "Kopanisti", "Tyrosalata", "Htipiti", "Olive Tapenade", "Greek Olives", "Kalamata Olives", "Marinated Olives", "Dolmades", "Dolmadakia", "Fried Cheese", "Graviera Saganaki", "Kefalotyri Saganaki", "Manouri Cheese", "Graviera Cheese", "Kefalograviera", "Kasseri", "Mizithra", "Anthotyro", "Metsovone", "Greek Meze", "Feta Meze", "Mezze Platter", "Cheese Croquettes", "Tirokroketes", "Potato Croquettes", "Patatokeftedes", "Kolokithokeftedes", "Tomatokeftedes", "Revithokeftedes", "Fava Fritters", "Pita Bread", "Greek Pita", "Pita with Tzatziki", "Pita with Feta", "Greek Nachos", "Pita Chips with Tzatziki", "Fried Pita Chips"];
const SEAFOOD = ["Shrimp Saganaki", "Mussels Saganaki", "Fried Calamari", "Grilled Calamari", "Stuffed Calamari", "Octopus", "Grilled Octopus", "Octopus in Vinegar", "Octopus Stifado", "Fried Sardines", "Grilled Sardines", "Marinated Anchovies", "Gavros Marinatos", "Fried Anchovies", "Grilled Sea Bream", "Grilled Sea Bass", "Lavraki", "Tsipoura", "Swordfish Souvlaki", "Grilled Swordfish", "Fried Cod", "Bakaliaros Skordalia", "Fried Red Mullet", "Barbouni", "Grilled Shrimp", "Fried Shrimp", "Shrimp with Feta", "Garides Saganaki", "Grilled Prawns", "Mussels", "Steamed Mussels", "Fried Mussels", "Midia Saganaki", "Seafood Giouvetsi", "Seafood Orzo", "Seafood Pasta", "Lobster Pasta", "Astakomakaronada", "Shrimp Kritharoto", "Seafood Meze"];
const SOUPS_PIES_BAKERY = ["Tiropita", "Spanakopita", "Spanakotiropita", "Kotopita", "Kreatopita", "Prasopita", "Hortopita", "Manitaropita", "Bougatsa", "Bougatsa with Cheese", "Fasolada", "Avgolemono Soup", "Chicken Avgolemono", "Magiritsa", "Psarosoupa", "Kakavia", "Trahana Soup", "Revithosoupa", "Fakies", "Lentil Soup", "Bean Soup", "Chickpea Soup", "Giouvarlakia", "Youvarlakia Avgolemono", "Koulouri Thessalonikis", "Ladenia", "Eliopita", "Olive Bread", "Feta Bread", "Psomi", "Lagana", "Daktyla Bread", "Paximadi", "Barley Rusks", "Sfakianopita", "Kalitsounia", "Cheese Kalitsounia", "Mizithropita", "Cretan Cheese Pie", "Cretan Meat Pie"];
const SALADS_SIDES = ["Greek Salad", "Horiatiki", "Dakos", "Cretan Dakos", "Maroulosalata", "Horta", "Beetroot Salad", "Cabbage Salad", "Politiki Salata", "Potato Salad", "Fasolakia Salad", "Lentil Salad", "Chickpea Salad", "Fasolakia Ladera", "Bamies", "Briam", "Imam Bayildi Greek Style", "Gigantes Plaki", "Revithada", "Arakas Laderos", "Spanakorizo", "Lahanorizo", "Prasorizo", "Gemista with Rice", "Stuffed Tomatoes", "Stuffed Peppers", "Stuffed Zucchini", "Kolokithakia Gemista", "Eggplant Imam", "Melitzanes Papoutsakia", "Fried Eggplant", "Grilled Eggplant", "Fried Zucchini", "Fried Peppers", "Florina Peppers", "Stuffed Florina Peppers", "Grilled Peppers with Feta", "Patates Tiganites", "Greek Fries", "Feta Fries", "Oregano Fries", "Lemon Potatoes", "Patates Lemonates", "Roasted Greek Potatoes", "Potato Saganaki"];
const DESSERTS = ["Greek Yogurt", "Yogurt with Honey", "Yogurt with Honey and Walnuts", "Loukoumades", "Baklava", "Galaktoboureko", "Kataifi", "Portokalopita", "Karidopita", "Ravani", "Revani", "Samali", "Melomakarona", "Kourabiedes", "Diples", "Amygdalota", "Halva", "Semolina Halva", "Pasteli", "Spoon Sweets", "Glyko Koutaliou", "Rizogalo", "Greek Rice Pudding", "Ekmek Kataifi", "Karydopita", "Moustalevria", "Fanouropita", "Vasilopita", "Tsoureki", "Lazarakia", "Koulourakia", "Finikia", "Loukoumi", "Mandolato", "Sesame Bars", "Honey Puffs", "Greek Pancakes", "Tiganites", "Sweet Kalitsounia"];

const RAW_GREEK_ITEMS = [
  ...GYROS_SOUVLAKI.map((name, idx) => ({ category: "Gyros, Souvlaki & Pita", name, price: "6.50", desc: `A Mediterranean classic reimagined, this ${name} features sun-ripened ingredients and premium olive oil for an unforgettable taste.`, img: generateAiImage(name, "authentic Greek taverna"), isSignature: idx === 0 })),
  ...TRADITIONAL_MAINS.map((name, idx) => ({ category: "Traditional Mains & Grill", name, price: "16.00", desc: `An exceptional presentation of ${name}, slow-roasted to absolute perfection and steeped in authentic Greek heritage.`, img: generateAiImage(name, "authentic Greek taverna"), isSignature: name === "Moussaka" })),
  ...MEZE_STARTERS.map((name, idx) => ({ category: "Meze, Dips & Starters", name, price: "8.00", desc: `A bright and flavorful ${name}, thoughtfully prepared with fresh herbs and designed to awaken your palate.`, img: generateAiImage(name, "authentic Greek taverna"), isSignature: false })),
  ...SEAFOOD.map((name, idx) => ({ category: "Aegean Seafood", name, price: "22.00", desc: `Impeccably fresh ${name}, caught wild from the Aegean Sea and delicately charred over an open flame with lemon.`, img: generateAiImage(name, "authentic Greek taverna"), isSignature: name === "Grilled Octopus" })),
  ...SOUPS_PIES_BAKERY.map((name, idx) => ({ category: "Pies, Soups & Bakery", name, price: "7.50", desc: `Handcrafted ${name}, showcasing golden, flaky textures and deeply comforting, rustic Mediterranean flavors.`, img: generateAiImage(name, "authentic Greek taverna"), isSignature: false })),
  ...SALADS_SIDES.map((name, idx) => ({ category: "Greek Salads & Sides", name, price: "9.00", desc: `A crisp, refreshing ${name}, elevating the simplest, highest-quality organic ingredients with a drizzle of robust olive oil.`, img: generateAiImage(name, "authentic Greek taverna"), isSignature: name === "Greek Salad" })),
  ...DESSERTS.map((name, idx) => ({ category: "Greek Sweets & Yogurt", name, price: "6.00", desc: `A symphony of honey and artisan pastry, this ${name} is the definitive sweet conclusion to your dining experience.`, img: generateAiImage(name, "authentic Greek taverna"), isSignature: name === "Baklava" }))
];

export const GREEK_MASSIVE_MENU = { restaurantName: "Η Χρυσή Ελιά (The Golden Olive)", themeColor: "#3b82f6", currency: "€", items: RAW_GREEK_ITEMS };