// POČETAK FAJLA: src/DemoData/italianMassiveData.js

// 🔥 BAZA SIGURNIH HD SLIKA (BEZ AI HALUCINACIJA I GREŠAKA) 🔥
const SAFE_IMAGE_POOLS = {
  pasta: [
    "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1516685018646-549198525c1b?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1621996316565-df04803930bf?auto=format&fit=crop&w=800&q=80"
  ],
  pizza: [
    "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=800&q=80"
  ],
  antipasti: [
    "https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1600803907087-f56d462fd26b?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1529312266912-b33cfce2eefd?auto=format&fit=crop&w=800&q=80"
  ],
  secondi: [
    "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1559742811-822873691fc8?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80"
  ],
  soups: [
    "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1604152135912-04a022e23696?auto=format&fit=crop&w=800&q=80"
  ],
  dolci: [
    "https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80"
  ],
  coffee: [
    "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80"
  ]
};

const getSafeImage = (poolName, index) => {
  const pool = SAFE_IMAGE_POOLS[poolName] || SAFE_IMAGE_POOLS.pasta;
  return pool[index % pool.length];
};

export const ITALIAN_MASSIVE_MENU = { 
  restaurantName: "Bella Napoli", 
  themeColor: "#eab308", 
  currency: "€", 
  items: [
    // --- PASTA FRESCA ---
    { category: "Pasta", name: "Spaghetti Carbonara", price: "18.00", desc: "Classic Roman pasta with crispy guanciale, pecorino romano, and a rich egg yolk emulsion.", img: getSafeImage("pasta", 0), isSignature: true },
    { category: "Pasta", name: "Cacio e Pepe", price: "16.00", desc: "A minimalist masterpiece made strictly with toasted black pepper and aged pecorino cheese.", img: getSafeImage("pasta", 1), isSignature: true },
    { category: "Pasta", name: "Pasta all’Amatriciana", price: "17.00", desc: "Rich tomato sauce infused with cured pork cheek, chili, and sharp sheep's cheese.", img: getSafeImage("pasta", 2), isSignature: false },
    { category: "Pasta", name: "Pasta alla Gricia", price: "17.00", desc: "The white ancestor of Amatriciana, featuring emulsified pork fat, black pepper, and cheese.", img: getSafeImage("pasta", 3), isSignature: false },
    { category: "Pasta", name: "Spaghetti Aglio e Olio", price: "14.00", desc: "A simple, garlic-infused extra virgin olive oil pasta with a hint of red chili flakes.", img: getSafeImage("pasta", 4), isSignature: false },
    { category: "Pasta", name: "Pasta al Pesto Genovese", price: "18.50", desc: "Fresh basil, pine nuts, garlic, and parmesan, pounded in a traditional mortar.", img: getSafeImage("pasta", 5), isSignature: true },
    { category: "Pasta", name: "Tagliatelle al Ragù Bolognese", price: "21.00", desc: "Authentic slow-simmered meat sauce over flat, egg-based ribbons of pasta.", img: getSafeImage("pasta", 6), isSignature: true },
    { category: "Pasta", name: "Pappardelle al Cinghiale", price: "24.00", desc: "Wide pasta ribbons coated in a rustic, slow-cooked wild boar ragù.", img: getSafeImage("pasta", 7), isSignature: true },
    { category: "Pasta", name: "Lasagne alla Bolognese", price: "19.00", desc: "Layers of fresh pasta baked with rich meat ragù, creamy béchamel, and parmesan crust.", img: getSafeImage("pasta", 8), isSignature: false },
    { category: "Pasta", name: "Lasagne al Pesto", price: "18.00", desc: "Ligurian-style lasagna layered with vibrant green pesto and creamy béchamel.", img: getSafeImage("pasta", 9), isSignature: false },
    { category: "Pasta", name: "Penne all’Arrabbiata", price: "15.00", desc: "Short pasta tossed in a fiery, garlic-laden tomato sauce.", img: getSafeImage("pasta", 10), isSignature: false },
    { category: "Pasta", name: "Pasta alla Norma", price: "17.50", desc: "Sicilian classic featuring fried eggplant, tomato basil sauce, and salted ricotta.", img: getSafeImage("pasta", 11), isSignature: false },
    { category: "Pasta", name: "Pasta Puttanesca", price: "16.50", desc: "A pungent, briny sauce of tomatoes, black olives, capers, and anchovies.", img: getSafeImage("pasta", 12), isSignature: false },
    { category: "Pasta", name: "Linguine alle Vongole", price: "23.00", desc: "Elegant long pasta tossed with fresh clams, white wine, garlic, and parsley.", img: getSafeImage("pasta", 13), isSignature: true },
    { category: "Pasta", name: "Spaghetti ai Frutti di Mare", price: "26.00", desc: "A luxurious seafood medley of mussels, clams, squid, and shrimp over spaghetti.", img: getSafeImage("pasta", 14), isSignature: true },
    { category: "Pasta", name: "Spaghetti alle Cozze", price: "19.00", desc: "Spaghetti tossed with plump mussels in a garlicky tomato broth.", img: getSafeImage("pasta", 15), isSignature: false },
    { category: "Pasta", name: "Spaghetti al Pomodoro", price: "13.00", desc: "The ultimate Italian comfort: sweet San Marzano tomatoes, olive oil, and fresh basil.", img: getSafeImage("pasta", 16), isSignature: false },
    { category: "Pasta", name: "Spaghetti alla Nerano", price: "20.00", desc: "Amalfi Coast specialty with fried zucchini and provolone del Monaco cheese.", img: getSafeImage("pasta", 17), isSignature: true },
    { category: "Pasta", name: "Fettuccine Alfredo", price: "17.00", desc: "A rich, emulsified sauce of pure butter and aged Parmigiano Reggiano.", img: getSafeImage("pasta", 18), isSignature: false },
    { category: "Pasta", name: "Fettuccine al Tartufo", price: "28.00", desc: "Decadent pasta completely enveloped in butter and freshly shaved black truffles.", img: getSafeImage("pasta", 19), isSignature: true },
    { category: "Pasta", name: "Fettuccine ai Funghi", price: "18.50", desc: "Earthy mushroom pasta cooked in a light garlic and white wine sauce.", img: getSafeImage("pasta", 20), isSignature: false },
    { category: "Pasta", name: "Bucatini all’Amatriciana", price: "17.50", desc: "Thick, hollow spaghetti drenched in a smoky pancetta and tomato reduction.", img: getSafeImage("pasta", 21), isSignature: false },
    { category: "Pasta", name: "Rigatoni alla Carbonara", price: "18.50", desc: "Hearty rigatoni tubes capturing the creamy, peppery egg and guanciale sauce.", img: getSafeImage("pasta", 22), isSignature: false },
    { category: "Pasta", name: "Rigatoni con Pajata", price: "21.00", desc: "A traditional, bold Roman dish made with milk-fed veal intestines and tomatoes.", img: getSafeImage("pasta", 23), isSignature: true },
    { category: "Pasta", name: "Paccheri al Ragù", price: "22.00", desc: "Giant pasta tubes holding a rich, slow-cooked Neapolitan meat sauce.", img: getSafeImage("pasta", 24), isSignature: false },
    { category: "Pasta", name: "Paccheri ai Frutti di Mare", price: "27.00", desc: "Large pasta tubes served with a glorious bounty of mixed seafood.", img: getSafeImage("pasta", 25), isSignature: true },
    { category: "Pasta", name: "Orecchiette con Cime di Rapa", price: "18.00", desc: "Puglia's pride: little ear pasta tossed with bitter turnip tops and anchovy.", img: getSafeImage("pasta", 26), isSignature: true },
    { category: "Pasta", name: "Trofie al Pesto", price: "19.00", desc: "Twisted Ligurian pasta with potatoes, green beans, and fresh basil pesto.", img: getSafeImage("pasta", 27), isSignature: false },
    { category: "Pasta", name: "Trenette al Pesto", price: "18.50", desc: "Long, flat pasta served with bright, herbaceous Genoese pesto.", img: getSafeImage("pasta", 28), isSignature: false },
    { category: "Pasta", name: "Bigoli in Salsa", price: "17.00", desc: "Venetian thick spaghetti coated in a slowly dissolved onion and anchovy sauce.", img: getSafeImage("pasta", 29), isSignature: false },
    { category: "Pasta", name: "Pici all’Aglione", price: "16.50", desc: "Hand-rolled Tuscan pasta strands in a robust, garlic-heavy tomato sauce.", img: getSafeImage("pasta", 30), isSignature: false },
    { category: "Pasta", name: "Pasta alla Genovese", price: "20.00", desc: "A slow-cooked, deeply sweet onion and beef ragout served over ziti.", img: getSafeImage("pasta", 31), isSignature: true },
    { category: "Pasta", name: "Pasta alla Vodka", price: "17.00", desc: "Smooth tomato cream sauce flamed with vodka and tossed with penne.", img: getSafeImage("pasta", 32), isSignature: false },
    { category: "Pasta", name: "Pasta al Limone", price: "15.00", desc: "A vibrant, citrusy sauce made of lemon zest, butter, and parmesan.", img: getSafeImage("pasta", 33), isSignature: false },
    { category: "Pasta", name: "Pasta ai Quattro Formaggi", price: "18.00", desc: "An indulgent blend of four melted Italian cheeses over short pasta.", img: getSafeImage("pasta", 34), isSignature: false },
    { category: "Pasta", name: "Pasta al Nero di Seppia", price: "22.00", desc: "Striking black pasta colored and flavored by fresh cuttlefish ink.", img: getSafeImage("pasta", 35), isSignature: true },
    { category: "Pasta", name: "Pasta con Bottarga", price: "25.00", desc: "Pasta dusted with the 'gold of the sea' – grated cured mullet roe.", img: getSafeImage("pasta", 36), isSignature: true },
    { category: "Pasta", name: "Pasta con Ricotta", price: "14.50", desc: "Simple, delicate, and creamy pasta folded with fresh sheep's milk ricotta.", img: getSafeImage("pasta", 37), isSignature: false },
    { category: "Pasta", name: "Pasta con Zucchine", price: "15.00", desc: "Light pasta dish featuring sautéed zucchini, garlic, and fresh mint.", img: getSafeImage("pasta", 38), isSignature: false },
    { category: "Pasta", name: "Pasta con Funghi Porcini", price: "21.00", desc: "Aromatically intense pasta featuring wild foraged porcini mushrooms.", img: getSafeImage("pasta", 39), isSignature: false },
    { category: "Pasta", name: "Pasta con Salsiccia", price: "18.50", desc: "Hearty dish combining crumbled Italian sausage with tomato and fennel.", img: getSafeImage("pasta", 40), isSignature: false },
    { category: "Pasta", name: "Pasta alla Sorrentina", price: "17.00", desc: "Baked pasta with tomatoes, melting mozzarella, and fresh basil leaves.", img: getSafeImage("pasta", 41), isSignature: false },
    { category: "Pasta", name: "Malloreddus alla Campidanese", price: "19.00", desc: "Sardinian saffron gnocchi in a rich sausage and tomato ragù.", img: getSafeImage("pasta", 42), isSignature: true },
    { category: "Pasta", name: "Culurgiones", price: "21.00", desc: "Intricately braided Sardinian ravioli stuffed with potato, pecorino, and mint.", img: getSafeImage("pasta", 43), isSignature: true },
    { category: "Pasta", name: "Fregola con Arselle", price: "24.00", desc: "Toasted Sardinian pasta pearls simmered with fresh clams in a light broth.", img: getSafeImage("pasta", 44), isSignature: true },
    { category: "Pasta", name: "Casarecce alla Siciliana", price: "17.50", desc: "Twisted pasta mixed with eggplant, tomatoes, capers, and olives.", img: getSafeImage("pasta", 45), isSignature: false },
    { category: "Pasta", name: "Strozzapreti al Ragù", price: "19.00", desc: "Hand-rolled 'priest strangler' pasta covered in a meaty, rustic sauce.", img: getSafeImage("pasta", 46), isSignature: false },

    // --- RAVIOLI E PASTA RIPIENA ---
    { category: "Pasta Ripiena (Punjena Pasta)", name: "Ravioli Ricotta e Spinaci", price: "18.00", desc: "Pillowy pasta squares filled with fresh ricotta and spinach in sage butter.", img: getSafeImage("pasta", 47), isSignature: false },
    { category: "Pasta Ripiena (Punjena Pasta)", name: "Ravioli al Tartufo", price: "28.00", desc: "Luxurious ravioli stuffed with black truffle cream, finished with truffle oil.", img: getSafeImage("pasta", 48), isSignature: true },
    { category: "Pasta Ripiena (Punjena Pasta)", name: "Ravioli di Zucca", price: "19.00", desc: "Sweet pumpkin ravioli tossed in brown butter, sage, and crushed amaretti.", img: getSafeImage("pasta", 49), isSignature: true },
    { category: "Pasta Ripiena (Punjena Pasta)", name: "Ravioli al Pomodoro", price: "16.00", desc: "Classic meat or cheese ravioli bathed in a light, sweet tomato basil sauce.", img: getSafeImage("pasta", 50), isSignature: false },
    { category: "Pasta Ripiena (Punjena Pasta)", name: "Agnolotti del Plin", price: "22.00", desc: "Piedmontese pinched pasta filled with roasted meats, served in rich pan drippings.", img: getSafeImage("pasta", 51), isSignature: true },
    { category: "Pasta Ripiena (Punjena Pasta)", name: "Tortellini in Brodo", price: "19.50", desc: "Tiny meat-filled tortellini swimming in a crystal-clear, rich capon broth.", img: getSafeImage("pasta", 52), isSignature: true },
    { category: "Pasta Ripiena (Punjena Pasta)", name: "Tortellini alla Panna", price: "18.50", desc: "Prosciutto-stuffed tortellini coated in a heavy cream and parmesan reduction.", img: getSafeImage("pasta", 53), isSignature: false },
    { category: "Pasta Ripiena (Punjena Pasta)", name: "Tortelloni Ricotta e Spinaci", price: "17.00", desc: "Large tortelloni pockets filled with greens and cheese in a light butter sauce.", img: getSafeImage("pasta", 54), isSignature: false },
    { category: "Pasta Ripiena (Punjena Pasta)", name: "Cappelletti in Brodo", price: "20.00", desc: "Little 'hats' of pasta stuffed with cheese and meat, served in hot broth.", img: getSafeImage("pasta", 55), isSignature: false },
    { category: "Pasta Ripiena (Punjena Pasta)", name: "Cannelloni", price: "18.00", desc: "Large pasta tubes stuffed with meat and ricotta, baked under tomato and béchamel.", img: getSafeImage("pasta", 56), isSignature: false },
    { category: "Pasta Ripiena (Punjena Pasta)", name: "Manicotti", price: "17.50", desc: "Baked pasta sleeves heavily filled with a seasoned ricotta cheese mixture.", img: getSafeImage("pasta", 57), isSignature: false },

    // --- GNOCCHI ---
    { category: "Gnocchi", name: "Gnocchi al Pomodoro", price: "15.00", desc: "Soft potato dumplings in a vibrant and fresh tomato basil sauce.", img: getSafeImage("pasta", 58), isSignature: false },
    { category: "Gnocchi", name: "Gnocchi al Gorgonzola", price: "17.50", desc: "Pillowy gnocchi swimming in a pungent, creamy melted gorgonzola sauce.", img: getSafeImage("pasta", 59), isSignature: true },
    { category: "Gnocchi", name: "Gnocchi alla Sorrentina", price: "16.50", desc: "Baked potato gnocchi bubbling with mozzarella, tomato sauce, and fresh basil.", img: getSafeImage("pasta", 60), isSignature: false },
    { category: "Gnocchi", name: "Gnocchi al Pesto", price: "16.00", desc: "Gnocchi coated in a bright, herbaceous, and garlicky green basil pesto.", img: getSafeImage("pasta", 61), isSignature: false },
    { category: "Gnocchi", name: "Gnocchi al Ragù", price: "18.00", desc: "Potato dumplings smothered in a thick, slow-cooked Bolognese meat sauce.", img: getSafeImage("pasta", 62), isSignature: false },
    { category: "Gnocchi", name: "Gnocchi di Zucca", price: "17.00", desc: "Sweet autumnal pumpkin gnocchi served with a fragrant sage butter glaze.", img: getSafeImage("pasta", 63), isSignature: false },
    { category: "Gnocchi", name: "Gnocchi di Ricotta", price: "16.50", desc: "Ultra-light and airy dumplings made entirely from fresh ricotta cheese.", img: getSafeImage("pasta", 64), isSignature: false },
    { category: "Gnocchi", name: "Gnocchi alla Romana", price: "18.00", desc: "Baked semolina discs layered with butter and generous amounts of pecorino.", img: getSafeImage("pasta", 65), isSignature: true },

    // --- RISOTTI ---
    { category: "Risotto", name: "Risotto alla Milanese", price: "22.00", desc: "The iconic, golden-hued saffron risotto, finished with bone marrow and parmesan.", img: getSafeImage("pasta", 66), isSignature: true },
    { category: "Risotto", name: "Risotto ai Funghi Porcini", price: "24.00", desc: "Earthy, creamy arborio rice slowly cooked with wild porcini mushrooms.", img: getSafeImage("pasta", 67), isSignature: true },
    { category: "Risotto", name: "Risotto al Tartufo", price: "29.00", desc: "A luxurious risotto completely infused with the aroma of fresh black truffles.", img: getSafeImage("pasta", 68), isSignature: true },
    { category: "Risotto", name: "Risotto ai Frutti di Mare", price: "26.00", desc: "Seafood risotto brimming with the fresh catch of the day in a light tomato broth.", img: getSafeImage("pasta", 69), isSignature: false },
    { category: "Risotto", name: "Risotto al Limone", price: "18.00", desc: "A surprisingly bright and creamy lemon-infused risotto from the Amalfi coast.", img: getSafeImage("pasta", 70), isSignature: false },
    { category: "Risotto", name: "Risotto al Nero di Seppia", price: "23.00", desc: "Striking black risotto colored with squid ink, offering a deep oceanic flavor.", img: getSafeImage("pasta", 71), isSignature: true },
    { category: "Risotto", name: "Risotto alla Zucca", price: "19.00", desc: "Creamy, vibrant orange pumpkin risotto garnished with toasted pumpkin seeds.", img: getSafeImage("pasta", 72), isSignature: false },
    { category: "Risotto", name: "Risotto al Radicchio", price: "19.50", desc: "A slightly bitter, visually stunning red radicchio risotto balanced with sweet wine.", img: getSafeImage("pasta", 73), isSignature: false },
    { category: "Risotto", name: "Risotto agli Asparagi", price: "20.00", desc: "Springtime on a plate: delicate green asparagus spears folded into creamy rice.", img: getSafeImage("pasta", 74), isSignature: false },
    { category: "Risotto", name: "Risotto ai Quattro Formaggi", price: "21.00", desc: "An intensely rich and gooey risotto melting with four premium Italian cheeses.", img: getSafeImage("pasta", 75), isSignature: false },
    { category: "Risotto", name: "Risotto con Salsiccia", price: "20.50", desc: "Rustic risotto cooked with crumbled savory sausage and a splash of red wine.", img: getSafeImage("pasta", 76), isSignature: false },
    { category: "Risotto", name: "Risi e Bisi", price: "17.00", desc: "A cross between soup and risotto, featuring fresh spring peas and pancetta.", img: getSafeImage("pasta", 77), isSignature: false },
    { category: "Risotto", name: "Paniscia", price: "21.00", desc: "A hearty Piedmontese rice dish cooked with beans, cabbage, and local salami.", img: getSafeImage("pasta", 78), isSignature: false },

    // --- MINESTRE E ZUPPE (Supe i Čorbe) ---
    { category: "Minestre e Zuppe", name: "Pasta e Fagioli", price: "14.00", desc: "A thick, warming stew of beans and short pasta in a savory tomato-pancetta broth.", img: getSafeImage("soups", 0), isSignature: false },
    { category: "Minestre e Zuppe", name: "Pasta e Ceci", price: "13.50", desc: "Comforting Roman soup made with chickpeas, garlic, rosemary, and short pasta.", img: getSafeImage("soups", 1), isSignature: false },
    { category: "Minestre e Zuppe", name: "Pasta e Patate", price: "14.00", desc: "A starchy, intensely satisfying Neapolitan stew of pasta, potatoes, and provola cheese.", img: getSafeImage("soups", 2), isSignature: true },
    { category: "Minestre e Zuppe", name: "Pasta con le Sarde", price: "19.00", desc: "Sicilian classic with fresh sardines, pine nuts, raisins, and wild fennel.", img: getSafeImage("soups", 3), isSignature: true },
    { category: "Minestre e Zuppe", name: "Minestrone", price: "12.00", desc: "The quintessential Italian vegetable soup, packed with seasonal greens and beans.", img: getSafeImage("soups", 4), isSignature: false },
    { category: "Minestre e Zuppe", name: "Ribollita", price: "15.00", desc: "A hearty Tuscan potage of recooked bread, cannellini beans, and black cabbage.", img: getSafeImage("soups", 5), isSignature: true },
    { category: "Minestre e Zuppe", name: "Zuppa Toscana", price: "16.00", desc: "A rich cream-based soup loaded with spicy Italian sausage, kale, and potatoes.", img: getSafeImage("soups", 6), isSignature: false },
    { category: "Minestre e Zuppe", name: "Acquacotta", price: "14.00", desc: "A peasant 'cooked water' soup from Maremma, enriched with an egg and stale bread.", img: getSafeImage("soups", 7), isSignature: false },
    { category: "Minestre e Zuppe", name: "Pappa al Pomodoro", price: "13.50", desc: "Thick, garlicky Tuscan bread and tomato soup, heavily drizzled with olive oil.", img: getSafeImage("soups", 8), isSignature: true },
    { category: "Minestre e Zuppe", name: "Stracciatella alla Romana", price: "14.50", desc: "Roman egg drop soup whisked with parmesan and nutmeg in a clear meat broth.", img: getSafeImage("soups", 9), isSignature: false },
    { category: "Minestre e Zuppe", name: "Zuppa di Ceci", price: "13.00", desc: "A rustic, slowly simmered chickpea soup finished with a sprig of rosemary.", img: getSafeImage("soups", 10), isSignature: false },
    { category: "Minestre e Zuppe", name: "Zuppa di Lenticchie", price: "13.00", desc: "Hearty brown lentil soup, a traditional Italian symbol of prosperity.", img: getSafeImage("soups", 11), isSignature: false },
    { category: "Minestre e Zuppe", name: "Zuppa di Fagioli", price: "12.50", desc: "A warming bean soup cooked with garlic, tomatoes, and a hint of chili.", img: getSafeImage("soups", 12), isSignature: false },
    { category: "Minestre e Zuppe", name: "Zuppa di Farro", price: "14.00", desc: "Nutty and wholesome spelt soup cooked with aromatic root vegetables.", img: getSafeImage("soups", 13), isSignature: false },
    { category: "Minestre e Zuppe", name: "Zuppa di Pesce", price: "26.00", desc: "A fragrant fisherman's stew brimming with the fresh catch of the day.", img: getSafeImage("soups", 14), isSignature: true },
    { category: "Minestre e Zuppe", name: "Brodetto di Pesce", price: "27.00", desc: "Adriatic coast seafood soup cooked with a splash of vinegar and tomatoes.", img: getSafeImage("soups", 15), isSignature: true },
    { category: "Minestre e Zuppe", name: "Cacciucco", price: "29.00", desc: "Livorno's famous robust fish stew poured over garlic-rubbed toasted bread.", img: getSafeImage("soups", 16), isSignature: true },
    { category: "Minestre e Zuppe", name: "Cioppino", price: "28.00", desc: "Italian-American tomato-based seafood stew loaded with crab, mussels, and fish.", img: getSafeImage("soups", 17), isSignature: false },

    // --- PIZZA ---
    { category: "Pizza Napoletana", name: "Pizza Margherita", price: "12.00", desc: "The queen of pizzas: San Marzano tomato sauce, fresh mozzarella, and basil.", img: getSafeImage("pizza", 0), isSignature: true },
    { category: "Pizza Napoletana", name: "Pizza Marinara", price: "10.00", desc: "A simple, cheese-free pie heavily seasoned with garlic, oregano, and olive oil.", img: getSafeImage("pizza", 1), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Napoletana", price: "14.00", desc: "A bold pizza topped with tomato sauce, mozzarella, anchovies, and capers.", img: getSafeImage("pizza", 2), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Diavola", price: "15.00", desc: "A fiery pizza covered in spicy Calabrian salami and chili flakes.", img: getSafeImage("pizza", 3), isSignature: true },
    { category: "Pizza Napoletana", name: "Pizza Capricciosa", price: "16.50", desc: "An 'unpredictable' mix of artichokes, mushrooms, ham, and black olives.", img: getSafeImage("pizza", 4), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Quattro Formaggi", price: "17.00", desc: "A white pizza melting with mozzarella, gorgonzola, fontina, and parmesan.", img: getSafeImage("pizza", 5), isSignature: true },
    { category: "Pizza Napoletana", name: "Pizza Quattro Stagioni", price: "16.50", desc: "The Four Seasons: divided into four sections of mushrooms, ham, artichokes, and olives.", img: getSafeImage("pizza", 6), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Prosciutto e Funghi", price: "15.50", desc: "A comforting combination of cooked ham and fresh mushrooms.", img: getSafeImage("pizza", 7), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Romana", price: "14.50", desc: "A crispy crust topped with tomato, mozzarella, anchovies, and oregano.", img: getSafeImage("pizza", 8), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Siciliana", price: "15.00", desc: "Thick crust pan pizza featuring tomatoes, onions, anchovies, and breadcrumbs.", img: getSafeImage("pizza", 9), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Bianca", price: "11.00", desc: "A white pizza brushed simply with olive oil, coarse salt, and rosemary.", img: getSafeImage("pizza", 10), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Ortolana", price: "14.00", desc: "The greengrocer's pizza: loaded with roasted eggplant, zucchini, and peppers.", img: getSafeImage("pizza", 11), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Vegetariana", price: "14.00", desc: "A fresh assortment of seasonal grilled vegetables over a tomato base.", img: getSafeImage("pizza", 12), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Tonno e Cipolla", price: "15.50", desc: "A robust pairing of flaked tuna and thinly sliced red onions.", img: getSafeImage("pizza", 13), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Boscaiola", price: "16.00", desc: "The woodman's pizza featuring earthy mushrooms and crumbled sausage.", img: getSafeImage("pizza", 14), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Bufalina", price: "18.00", desc: "A premium Margherita topped with whole balls of fresh buffalo mozzarella.", img: getSafeImage("pizza", 15), isSignature: true },
    { category: "Pizza Napoletana", name: "Pizza Parmigiana", price: "16.50", desc: "Pizza layered with fried eggplant slices, parmesan cheese, and basil.", img: getSafeImage("pizza", 16), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Salsiccia e Friarielli", price: "17.50", desc: "A Neapolitan classic featuring savory sausage and bitter broccoli rabe.", img: getSafeImage("pizza", 17), isSignature: true },
    { category: "Pizza Napoletana", name: "Pizza al Taglio", price: "7.00", desc: "A rectangular slice of Roman street pizza, baked in a sheet pan.", img: getSafeImage("pizza", 18), isSignature: false },
    { category: "Pizza Napoletana", name: "Pizza Fritta", price: "14.00", desc: "Neapolitan deep-fried pizza dough stuffed with ricotta and pork cracklings.", img: getSafeImage("pizza", 19), isSignature: true },

    // --- CALZONE, PANZEROTTI & FOCACCIA ---
    { category: "Focacceria & Fritti", name: "Calzone", price: "14.00", desc: "A folded, moon-shaped pizza baked and stuffed with ricotta, salami, and mozzarella.", img: getSafeImage("antipasti", 0), isSignature: false },
    { category: "Focacceria & Fritti", name: "Panzerotti", price: "9.00", desc: "Apulian small, deep-fried pockets of dough filled with molten tomato and cheese.", img: getSafeImage("antipasti", 1), isSignature: true },
    { category: "Focacceria & Fritti", name: "Focaccia Genovese", price: "8.00", desc: "Soft, dimpled Ligurian flatbread heavily drenched in premium olive oil and salt.", img: getSafeImage("antipasti", 2), isSignature: true },
    { category: "Focacceria & Fritti", name: "Focaccia Barese", price: "9.00", desc: "Apulian focaccia baked with cherry tomatoes and olives pressed into the dough.", img: getSafeImage("antipasti", 3), isSignature: false },
    { category: "Focacceria & Fritti", name: "Focaccia al Rosmarino", price: "7.00", desc: "A fragrant flatbread baked with fresh rosemary sprigs and sea salt.", img: getSafeImage("antipasti", 4), isSignature: false },
    { category: "Focacceria & Fritti", name: "Focaccia con Cipolle", price: "8.50", desc: "Savory focaccia topped with thinly sliced, caramelized sweet onions.", img: getSafeImage("antipasti", 5), isSignature: false },
    { category: "Focacceria & Fritti", name: "Schiacciata Toscana", price: "9.50", desc: "A crispy, salt-crusted Tuscan flatbread, perfect for filling with cured meats.", img: getSafeImage("antipasti", 6), isSignature: false },
    { category: "Focacceria & Fritti", name: "Piadina Romagnola", price: "10.00", desc: "A thin Italian flatbread sandwich, griddled and filled with prosciutto and squacquerone cheese.", img: getSafeImage("antipasti", 7), isSignature: true },
    { category: "Focacceria & Fritti", name: "Crescia", price: "11.00", desc: "A flaky, lard-enriched flatbread from Marche, served warm with greens.", img: getSafeImage("antipasti", 8), isSignature: false },
    { category: "Focacceria & Fritti", name: "Tigelle", price: "12.00", desc: "Small, round breads from Emilia-Romagna, split and stuffed with garlic-laced lardo.", img: getSafeImage("antipasti", 9), isSignature: true },
    { category: "Focacceria & Fritti", name: "Gnocco Fritto", price: "13.00", desc: "Puffy, hollow pillows of fried dough, served alongside delicate prosciutto.", img: getSafeImage("antipasti", 10), isSignature: true },
    { category: "Focacceria & Fritti", name: "Farinata", price: "8.00", desc: "A naturally vegan, savory chickpea flour pancake baked until crispy at the edges.", img: getSafeImage("antipasti", 11), isSignature: false },
    { category: "Focacceria & Fritti", name: "Cecina", price: "8.00", desc: "Tuscan equivalent of farinata, heavily dusted with cracked black pepper.", img: getSafeImage("antipasti", 12), isSignature: false },
    { category: "Focacceria & Fritti", name: "Arancini", price: "9.00", desc: "Sicilian golden-fried rice balls stuffed with a rich meat ragù and peas.", img: getSafeImage("antipasti", 13), isSignature: true },
    { category: "Focacceria & Fritti", name: "Arancine", price: "9.00", desc: "The Palermo version of the rice ball, round and filled with butter or meat.", img: getSafeImage("antipasti", 14), isSignature: false },
    { category: "Focacceria & Fritti", name: "Supplì", price: "7.00", desc: "Roman elongated fried rice croquettes filled with a melting core of mozzarella.", img: getSafeImage("antipasti", 15), isSignature: true },
    { category: "Focacceria & Fritti", name: "Crocchette di Riso", price: "8.00", desc: "Simple and crispy fried rice croquettes.", img: getSafeImage("antipasti", 16), isSignature: false },

    // --- ANTIPASTI & BRUSCHETTA ---
    { category: "Antipasti & Bruschette", name: "Bruschetta al Pomodoro", price: "8.00", desc: "Grilled rustic bread rubbed with garlic and piled high with marinated tomatoes.", img: getSafeImage("antipasti", 17), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Bruschetta ai Funghi", price: "9.50", desc: "Toasted bread topped with sautéed wild mushrooms and a drizzle of truffle oil.", img: getSafeImage("antipasti", 18), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Bruschetta al Tartufo", price: "14.00", desc: "A luxurious starter: grilled bread slathered in rich black truffle paste.", img: getSafeImage("antipasti", 19), isSignature: true },
    { category: "Antipasti & Bruschette", name: "Crostini Toscani", price: "11.00", desc: "Small toasted bread slices thickly spread with a rich, savory chicken liver pâté.", img: getSafeImage("antipasti", 20), isSignature: true },
    { category: "Antipasti & Bruschette", name: "Crostini al Pomodoro", price: "7.50", desc: "Bite-sized crispy toasts topped with a simple tomato and basil salad.", img: getSafeImage("antipasti", 21), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Crostini ai Funghi", price: "9.00", desc: "Toasts topped with warm, garlicky mushrooms.", img: getSafeImage("antipasti", 22), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Caprese", price: "13.00", desc: "A vibrant salad of sliced fresh mozzarella, tomatoes, and sweet basil leaves.", img: getSafeImage("antipasti", 23), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Panzanella", price: "12.00", desc: "A Tuscan bread salad thoroughly soaked with ripe tomato juices and vinegar.", img: getSafeImage("antipasti", 24), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Insalata di Mare", price: "18.00", desc: "A bright, lemony salad of lightly poached mixed seafood, celery, and parsley.", img: getSafeImage("antipasti", 25), isSignature: true },
    { category: "Antipasti & Bruschette", name: "Insalata di Polpo", price: "19.00", desc: "Tender chunks of boiled octopus tossed with potatoes, garlic, and parsley.", img: getSafeImage("antipasti", 26), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Insalata di Riso", price: "11.00", desc: "A cold summer rice salad mixed with pickled vegetables, cheese, and ham.", img: getSafeImage("antipasti", 27), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Insalata di Farro", price: "12.00", desc: "Nutty spelt salad mixed with cherry tomatoes, mozzarella, and fresh basil.", img: getSafeImage("antipasti", 28), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Insalata di Tonno", price: "13.50", desc: "A hearty salad featuring premium oil-packed tuna, red onions, and cannellini beans.", img: getSafeImage("antipasti", 29), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Insalata Mista", price: "8.00", desc: "A simple, refreshing mixed green salad with a light balsamic vinaigrette.", img: getSafeImage("antipasti", 30), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Insalata di Finocchi e Arance", price: "11.00", desc: "A crisp Sicilian salad of shaved fennel and sweet oranges with black olives.", img: getSafeImage("antipasti", 31), isSignature: true },
    { category: "Antipasti & Bruschette", name: "Carpaccio di Manzo", price: "17.00", desc: "Paper-thin slices of raw beef fillet dressed with lemon, olive oil, and shaved parmesan.", img: getSafeImage("antipasti", 32), isSignature: true },
    { category: "Antipasti & Bruschette", name: "Carpaccio di Tonno", price: "19.00", desc: "Delicate slices of raw tuna adorned with capers, citrus, and pink peppercorns.", img: getSafeImage("antipasti", 33), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Vitello Tonnato", price: "18.50", desc: "Chilled, thinly sliced veal covered in a creamy, caper-studded tuna mayonnaise.", img: getSafeImage("antipasti", 34), isSignature: true },
    { category: "Antipasti & Bruschette", name: "Bresaola con Rucola e Parmigiano", price: "16.00", desc: "Air-dried salted beef topped with peppery arugula and large parmesan shavings.", img: getSafeImage("antipasti", 35), isSignature: false },
    { category: "Antipasti & Bruschette", name: "Prosciutto e Melone", price: "15.00", desc: "The ultimate sweet and salty pairing: draped prosciutto over ripe cantaloupe.", img: getSafeImage("antipasti", 36), isSignature: false },

    // --- SALUMI E FORMAGGI ---
    { category: "Salumi e Formaggi", name: "Prosciutto di Parma", price: "14.00", desc: "Sweet, delicate, and world-famous dry-cured ham from Parma.", img: getSafeImage("antipasti", 37), isSignature: true },
    { category: "Salumi e Formaggi", name: "Prosciutto San Daniele", price: "15.00", desc: "A darker, sweeter, and more complex dry-cured ham from Friuli.", img: getSafeImage("antipasti", 38), isSignature: false },
    { category: "Salumi e Formaggi", name: "Mortadella", price: "12.00", desc: "Silky, studded pork sausage from Bologna with pistachios and fat cubes.", img: getSafeImage("antipasti", 39), isSignature: true },
    { category: "Salumi e Formaggi", name: "Bresaola", price: "15.00", desc: "Lean, deep-red air-dried salted beef from the Valtellina valley.", img: getSafeImage("antipasti", 40), isSignature: false },
    { category: "Salumi e Formaggi", name: "Speck", price: "13.00", desc: "A distinctively smoky, juniper-flavored cured ham from South Tyrol.", img: getSafeImage("antipasti", 41), isSignature: false },
    { category: "Salumi e Formaggi", name: "Salame Milano", price: "12.00", desc: "A finely ground, sweet, and garlicky cured pork sausage.", img: getSafeImage("antipasti", 42), isSignature: false },
    { category: "Salumi e Formaggi", name: "Salame Napoli", price: "12.50", desc: "A coarser, slightly spicy salami seasoned with black peppercorns.", img: getSafeImage("antipasti", 43), isSignature: false },
    { category: "Salumi e Formaggi", name: "Soppressata", price: "13.50", desc: "A rustic, unevenly cut, and robustly flavored dry salami.", img: getSafeImage("antipasti", 44), isSignature: false },
    { category: "Salumi e Formaggi", name: "Finocchiona", price: "14.00", desc: "A soft Tuscan salami powerfully flavored with toasted fennel seeds.", img: getSafeImage("antipasti", 45), isSignature: true },
    { category: "Salumi e Formaggi", name: "Capocollo", price: "14.50", desc: "A beautifully marbled, dry-cured pork neck seasoned with wine and spices.", img: getSafeImage("antipasti", 46), isSignature: false },
    { category: "Salumi e Formaggi", name: "Pancetta", price: "11.00", desc: "Italian cured pork belly, rolled and seasoned with black pepper.", img: getSafeImage("antipasti", 47), isSignature: false },
    { category: "Salumi e Formaggi", name: "Guanciale", price: "13.00", desc: "Cured pork jowl, the rich and intensely flavored backbone of Roman pasta.", img: getSafeImage("antipasti", 48), isSignature: true },
    { category: "Salumi e Formaggi", name: "Lardo di Colonnata", price: "16.00", desc: "Pure pork fat cured in marble basins with rosemary; melts instantly on warm bread.", img: getSafeImage("antipasti", 49), isSignature: true },
    { category: "Salumi e Formaggi", name: "Antipasto Italiano", price: "24.00", desc: "A grand, wooden board filled with a mixed selection of the finest cured meats and cheeses.", img: getSafeImage("antipasti", 50), isSignature: true },
    { category: "Salumi e Formaggi", name: "Antipasto di Mare", price: "28.00", desc: "An elegant platter showcasing a chilled variety of marinated seafood delicacies.", img: getSafeImage("antipasti", 51), isSignature: false },
    { category: "Salumi e Formaggi", name: "Giardiniera", price: "8.00", desc: "A colorful medley of tangy, pickled crisp vegetables.", img: getSafeImage("antipasti", 52), isSignature: false },
    { category: "Salumi e Formaggi", name: "Parmigiano Reggiano", price: "12.00", desc: "Hard, granular cheese aged for months, offering a complex, nutty flavor.", img: getSafeImage("antipasti", 53), isSignature: true },
    { category: "Salumi e Formaggi", name: "Grana Padano", price: "10.00", desc: "A slightly sweeter, less crumbly relative of Parmigiano.", img: getSafeImage("antipasti", 54), isSignature: false },
    { category: "Salumi e Formaggi", name: "Mozzarella di Bufala", price: "14.00", desc: "Exceptionally creamy, tangy mozzarella made entirely from water buffalo milk.", img: getSafeImage("antipasti", 55), isSignature: true },
    { category: "Salumi e Formaggi", name: "Burrata", price: "15.00", desc: "A mozzarella pouch that splits open to reveal a rich, flowing cream center.", img: getSafeImage("antipasti", 56), isSignature: true },
    { category: "Salumi e Formaggi", name: "Stracciatella di Burrata", price: "14.50", desc: "The luscious, creamy shreds of cheese found inside a burrata.", img: getSafeImage("antipasti", 57), isSignature: false },
    { category: "Salumi e Formaggi", name: "Ricotta", price: "9.00", desc: "Fresh, mild, and fluffy whey cheese served with honey or herbs.", img: getSafeImage("antipasti", 58), isSignature: false },
    { category: "Salumi e Formaggi", name: "Mascarpone", price: "9.50", desc: "Incredibly rich, buttery double-cream cheese.", img: getSafeImage("antipasti", 59), isSignature: false },
    { category: "Salumi e Formaggi", name: "Gorgonzola", price: "11.00", desc: "A soft, buttery, and deeply pungent blue-veined cheese from Milan.", img: getSafeImage("antipasti", 60), isSignature: true },
    { category: "Salumi e Formaggi", name: "Taleggio", price: "10.50", desc: "A washed-rind cheese that smells strong but tastes unexpectedly fruity and mild.", img: getSafeImage("antipasti", 61), isSignature: false },
    { category: "Salumi e Formaggi", name: "Fontina", price: "11.50", desc: "A superior melting cheese from the Alps with a nutty, earthy profile.", img: getSafeImage("antipasti", 62), isSignature: false },
    { category: "Salumi e Formaggi", name: "Asiago", price: "10.00", desc: "A versatile Alpine cow's milk cheese, ranging from smooth to crumbly.", img: getSafeImage("antipasti", 63), isSignature: false },
    { category: "Salumi e Formaggi", name: "Pecorino Romano", price: "11.00", desc: "A hard, fiercely salty sheep's milk cheese essential for Roman pastas.", img: getSafeImage("antipasti", 64), isSignature: true },
    { category: "Salumi e Formaggi", name: "Pecorino Toscano", price: "12.00", desc: "A milder, sweeter sheep's cheese from Tuscany, often rubbed with olive oil.", img: getSafeImage("antipasti", 65), isSignature: false },
    { category: "Salumi e Formaggi", name: "Pecorino Sardo", price: "12.50", desc: "A firm and richly flavored sheep's milk cheese from Sardinia.", img: getSafeImage("antipasti", 66), isSignature: false },
    { category: "Salumi e Formaggi", name: "Provolone", price: "9.00", desc: "A semi-hard, slightly piquant pulled-curd cheese.", img: getSafeImage("antipasti", 67), isSignature: false },
    { category: "Salumi e Formaggi", name: "Scamorza", price: "10.00", desc: "A pear-shaped, smoked curd cheese with a delightfully chewy texture.", img: getSafeImage("antipasti", 68), isSignature: false },
    { category: "Salumi e Formaggi", name: "Caciocavallo", price: "11.50", desc: "A sharp, teardrop-shaped aged cheese tied with a rope.", img: getSafeImage("antipasti", 69), isSignature: false },
    { category: "Salumi e Formaggi", name: "Robiola", price: "12.00", desc: "A soft, ripened cheese that is beautifully tangy and spreadable.", img: getSafeImage("antipasti", 70), isSignature: false },
    { category: "Salumi e Formaggi", name: "Castelmagno", price: "15.00", desc: "A rare, crumbly, and intense semi-hard cheese from Piedmont.", img: getSafeImage("antipasti", 71), isSignature: true },
    { category: "Salumi e Formaggi", name: "Montasio", price: "11.00", desc: "A creamy, unpasteurized cow's milk cheese from the northeast mountains.", img: getSafeImage("antipasti", 72), isSignature: false },

    // --- CONTORNI E VERDURE ---
    { category: "Contorni (Prilozi)", name: "Olive Ascolane", price: "12.00", desc: "Large green olives stuffed with seasoned meat, breaded, and deep-fried.", img: getSafeImage("antipasti", 73), isSignature: true },
    { category: "Contorni (Prilozi)", name: "Mozzarella in Carrozza", price: "11.00", desc: "A decadent fried mozzarella sandwich, crispy outside and oozing inside.", img: getSafeImage("antipasti", 74), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Fiori di Zucca Fritti", price: "13.00", desc: "Delicate zucchini blossoms stuffed with mozzarella and anchovies, battered and fried.", img: getSafeImage("antipasti", 75), isSignature: true },
    { category: "Contorni (Prilozi)", name: "Verdure Grigliate", price: "9.00", desc: "A simple, healthy platter of smoky grilled seasonal vegetables.", img: getSafeImage("antipasti", 76), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Verdure Sott’Olio", price: "8.50", desc: "Vegetables preserved in high-quality olive oil and herbs.", img: getSafeImage("antipasti", 77), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Melanzane Sott’Olio", price: "9.00", desc: "Strips of eggplant preserved in olive oil, garlic, and chili.", img: getSafeImage("antipasti", 78), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Carciofi alla Romana", price: "14.00", desc: "Whole artichokes braised slowly with garlic, mint, and white wine.", img: getSafeImage("antipasti", 79), isSignature: true },
    { category: "Contorni (Prilozi)", name: "Carciofi alla Giudia", price: "15.00", desc: "Famous Jewish-Roman artichokes, deep-fried whole until the leaves shatter like glass.", img: getSafeImage("antipasti", 80), isSignature: true },
    { category: "Contorni (Prilozi)", name: "Carciofi Gratinati", price: "13.50", desc: "Artichoke hearts baked under a crispy, cheesy breadcrumb crust.", img: getSafeImage("antipasti", 81), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Polenta", price: "8.00", desc: "A creamy, warming bowl of slow-cooked golden cornmeal.", img: getSafeImage("antipasti", 82), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Polenta con Funghi", price: "14.00", desc: "Soft polenta blanketed in a rich, earthy wild mushroom ragù.", img: getSafeImage("antipasti", 83), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Polenta con Salsiccia", price: "15.00", desc: "A hearty mountain dish of polenta covered in a thick sausage and tomato sauce.", img: getSafeImage("antipasti", 84), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Polenta Taragna", price: "13.00", desc: "A darker, earthier polenta mixed with buckwheat and melted local cheeses.", img: getSafeImage("antipasti", 85), isSignature: true },
    { category: "Contorni (Prilozi)", name: "Polenta Concia", price: "14.50", desc: "A decadent baked polenta saturated with fontina cheese and browned butter.", img: getSafeImage("antipasti", 86), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Parmigiana di Melanzane", price: "16.00", desc: "A magnificent bake of fried eggplant layers, tomato sauce, and parmesan.", img: getSafeImage("antipasti", 87), isSignature: true },
    { category: "Contorni (Prilozi)", name: "Melanzane alla Parmigiana", price: "16.00", desc: "Southern Italy's classic version of the beloved eggplant parmigiana.", img: getSafeImage("antipasti", 88), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Melanzane Ripiene", price: "14.00", desc: "Eggplant halves stuffed with a savory mixture of meat, breadcrumbs, and cheese.", img: getSafeImage("antipasti", 89), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Zucchine Ripiene", price: "13.00", desc: "Baked zucchini boats filled with seasoned minced meat.", img: getSafeImage("antipasti", 90), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Peperoni Ripieni", price: "14.50", desc: "Bell peppers roasted and stuffed with an aromatic rice and meat filling.", img: getSafeImage("antipasti", 91), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Pomodori Ripieni", price: "13.50", desc: "Roman-style tomatoes stuffed with herbed rice and baked until blistered.", img: getSafeImage("antipasti", 92), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Involtini di Melanzane", price: "15.00", desc: "Fried eggplant slices rolled around a filling of ricotta and baked in tomato sauce.", img: getSafeImage("antipasti", 93), isSignature: true },
    { category: "Contorni (Prilozi)", name: "Frittata", price: "10.00", desc: "A thick, slow-cooked Italian omelet, served in satisfying wedges.", img: getSafeImage("antipasti", 94), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Frittata di Zucchine", price: "11.00", desc: "A sweet and savory frittata loaded with grated fresh zucchini.", img: getSafeImage("antipasti", 95), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Frittata di Cipolle", price: "10.50", desc: "A rustic frittata made incredibly sweet by deeply caramelized onions.", img: getSafeImage("antipasti", 96), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Frittata di Patate", price: "11.50", desc: "A dense, comforting frittata packed with sliced potatoes and herbs.", img: getSafeImage("antipasti", 97), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Frittata di Asparagi", price: "12.00", desc: "A vibrant spring frittata filled with tender green asparagus spears.", img: getSafeImage("antipasti", 98), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Frittata di Carciofi", price: "13.00", desc: "An elegant frittata studded with thinly sliced, sautéed artichoke hearts.", img: getSafeImage("antipasti", 99), isSignature: false },
    { category: "Contorni (Prilozi)", name: "Frittata di Pasta", price: "12.50", desc: "A brilliant Neapolitan creation: leftover pasta fried into a crispy, cheesy cake.", img: getSafeImage("antipasti", 100), isSignature: true },

    // --- SECONDI DI CARNE (Glavna Jela od Mesa) ---
    { category: "Secondi di Carne", name: "Ossobuco alla Milanese", price: "34.00", desc: "Cross-cut veal shanks braised for hours, topped with a zesty lemon-parsley gremolata.", img: getSafeImage("secondi", 0), isSignature: true },
    { category: "Secondi di Carne", name: "Cotoletta alla Milanese", price: "28.00", desc: "A giant, bone-in veal chop, breaded and fried in pure clarifying butter.", img: getSafeImage("secondi", 1), isSignature: true },
    { category: "Secondi di Carne", name: "Scaloppine al Limone", price: "22.00", desc: "Thinly pounded veal medallions sautéed in a bright, glossy lemon-butter sauce.", img: getSafeImage("secondi", 2), isSignature: false },
    { category: "Secondi di Carne", name: "Scaloppine ai Funghi", price: "24.00", desc: "Tender veal scaloppine smothered in a creamy, earthy mushroom sauce.", img: getSafeImage("secondi", 3), isSignature: false },
    { category: "Secondi di Carne", name: "Scaloppine al Marsala", price: "24.50", desc: "Veal slices quickly pan-fried and glazed with sweet Sicilian Marsala wine.", img: getSafeImage("secondi", 4), isSignature: false },
    { category: "Secondi di Carne", name: "Saltimbocca alla Romana", price: "26.00", desc: "Veal lined with prosciutto and sage, which 'jumps in the mouth' with flavor.", img: getSafeImage("secondi", 5), isSignature: true },
    { category: "Secondi di Carne", name: "Vitello alla Pizzaiola", price: "23.00", desc: "Veal cutlets simmered in a robust sauce of tomatoes, garlic, and oregano.", img: getSafeImage("secondi", 6), isSignature: false },
    { category: "Secondi di Carne", name: "Vitello al Limone", price: "22.00", desc: "A variation of scaloppine, focusing heavily on a sharp, citrusy reduction.", img: getSafeImage("secondi", 7), isSignature: false },
    { category: "Secondi di Carne", name: "Vitello Marsala", price: "24.50", desc: "Classic Italian-American favorite: veal drowned in a rich mushroom and Marsala gravy.", img: getSafeImage("secondi", 8), isSignature: false },
    { category: "Secondi di Carne", name: "Arrosto di Vitello", price: "27.00", desc: "A beautifully rolled and tied veal roast, slow-cooked with root vegetables.", img: getSafeImage("secondi", 9), isSignature: false },
    { category: "Secondi di Carne", name: "Brasato al Barolo", price: "32.00", desc: "Beef roast marinated and slowly braised in noble Barolo wine until spoon-tender.", img: getSafeImage("secondi", 10), isSignature: true },
    { category: "Secondi di Carne", name: "Bollito Misto", price: "29.00", desc: "A grand northern feast of various mixed meats, slowly boiled and served with pungent green sauce.", img: getSafeImage("secondi", 11), isSignature: true },
    { category: "Secondi di Carne", name: "Stracotto", price: "26.00", desc: "An Italian pot roast, cooked 'overdone' in tomatoes and wine until it falls apart.", img: getSafeImage("secondi", 12), isSignature: false },
    { category: "Secondi di Carne", name: "Spezzatino di Manzo", price: "24.00", desc: "A comforting, rustic beef stew with potatoes and peas in a rich tomato gravy.", img: getSafeImage("secondi", 13), isSignature: false },
    { category: "Secondi di Carne", name: "Peposo", price: "25.00", desc: "A legendary Tuscan beef stew heavily spiced with cracked black peppercorns and red wine.", img: getSafeImage("secondi", 14), isSignature: true },
    { category: "Secondi di Carne", name: "Tagliata di Manzo", price: "32.00", desc: "Sliced rare beef steak fanned out over a bed of arugula and shaved parmesan.", img: getSafeImage("secondi", 15), isSignature: true },
    { category: "Secondi di Carne", name: "Bistecca alla Fiorentina", price: "75.00", desc: "A colossal, thick-cut T-bone steak from Chianina beef, grilled rare over wood coals.", img: getSafeImage("secondi", 16), isSignature: true },
    { category: "Secondi di Carne", name: "Filetto al Pepe Verde", price: "36.00", desc: "A prime beef fillet flambéed with brandy and coated in a green peppercorn cream sauce.", img: getSafeImage("secondi", 17), isSignature: false },
    { category: "Secondi di Carne", name: "Filetto al Barolo", price: "38.00", desc: "The finest beef tenderloin bathed in an intense, syrupy Barolo wine reduction.", img: getSafeImage("secondi", 18), isSignature: true },
    { category: "Secondi di Carne", name: "Carne alla Pizzaiola", price: "22.00", desc: "Beef slices stewed in a pizza-like sauce of tomatoes, olive oil, and oregano.", img: getSafeImage("secondi", 19), isSignature: false },
    { category: "Secondi di Carne", name: "Polpette al Sugo", price: "18.00", desc: "Large, tender Italian meatballs slowly simmered in a sweet basil tomato sauce.", img: getSafeImage("secondi", 20), isSignature: false },
    { category: "Secondi di Carne", name: "Polpette di Carne", price: "17.00", desc: "Classic fried or baked meatballs, crispy on the outside and juicy inside.", img: getSafeImage("secondi", 21), isSignature: false },
    { category: "Secondi di Carne", name: "Polpette di Melanzane", price: "16.00", desc: "Vegetarian 'meatballs' made entirely of roasted eggplant, breadcrumbs, and pecorino.", img: getSafeImage("secondi", 22), isSignature: false },
    { category: "Secondi di Carne", name: "Polpette di Ricotta", price: "16.50", desc: "Incredibly light and delicate meatballs made from fresh ricotta cheese.", img: getSafeImage("secondi", 23), isSignature: false },
    { category: "Secondi di Carne", name: "Involtini di Carne", price: "24.00", desc: "Thin slices of beef rolled around a savory filling of cheese, herbs, and pine nuts.", img: getSafeImage("secondi", 24), isSignature: false },
    { category: "Secondi di Carne", name: "Braciole al Sugo", price: "26.00", desc: "Southern Italian beef rolls simmered for hours in a tomato ragù until tender.", img: getSafeImage("secondi", 25), isSignature: true },
    { category: "Secondi di Carne", name: "Porchetta", price: "22.00", desc: "A whole, deboned pig, heavily stuffed with garlic and fennel, roasted until the skin crackles.", img: getSafeImage("secondi", 26), isSignature: true },
    { category: "Secondi di Carne", name: "Saltimbocca", price: "26.00", desc: "Tender veal cutlets adorned with prosciutto and fresh sage leaves.", img: getSafeImage("secondi", 27), isSignature: false },
    { category: "Secondi di Carne", name: "Abbacchio alla Romana", price: "29.00", desc: "Roman-style suckling lamb braised with garlic, rosemary, and anchovies.", img: getSafeImage("secondi", 28), isSignature: true },
    { category: "Secondi di Carne", name: "Abbacchio Scottadito", price: "31.00", desc: "Baby lamb chops grilled so hot they 'burn your fingers' when eaten.", img: getSafeImage("secondi", 29), isSignature: true },
    { category: "Secondi di Carne", name: "Agnello al Forno", price: "28.00", desc: "A comforting oven-roasted lamb leg marinated in herbs and wine.", img: getSafeImage("secondi", 30), isSignature: false },
    { category: "Secondi di Carne", name: "Agnello con Patate", price: "26.00", desc: "Roasted lamb chunks served over potatoes that have absorbed all the meat's juices.", img: getSafeImage("secondi", 31), isSignature: false },
    { category: "Secondi di Carne", name: "Costolette di Agnello", price: "33.00", desc: "Elegant, herb-crusted lamb rib chops pan-seared to a perfect medium rare.", img: getSafeImage("secondi", 32), isSignature: false },
    { category: "Secondi di Carne", name: "Coniglio alla Cacciatora", price: "25.00", desc: "Hunter-style rabbit braised with tomatoes, olives, onions, and wine.", img: getSafeImage("secondi", 33), isSignature: true },
    { category: "Secondi di Carne", name: "Coniglio alla Ligure", price: "26.00", desc: "Rabbit stewed with Taggiasca olives, pine nuts, and delicate Ligurian olive oil.", img: getSafeImage("secondi", 34), isSignature: false },
    { category: "Secondi di Carne", name: "Pollo alla Cacciatora", price: "21.00", desc: "Hunter-style chicken stewed with bell peppers, onions, and mushrooms.", img: getSafeImage("secondi", 35), isSignature: false },
    { category: "Secondi di Carne", name: "Pollo alla Romana", price: "22.00", desc: "Chicken braised in a sauce of sweet tomatoes and vibrant red and yellow peppers.", img: getSafeImage("secondi", 36), isSignature: false },
    { category: "Secondi di Carne", name: "Pollo al Limone", price: "19.00", desc: "Pan-roasted chicken breast coated in a glossy, tart lemon-butter reduction.", img: getSafeImage("secondi", 37), isSignature: false },
    { category: "Secondi di Carne", name: "Pollo alla Diavola", price: "20.00", desc: "'Devil's chicken' - split open, flattened, and grilled under a brick with fierce chili heat.", img: getSafeImage("secondi", 38), isSignature: true },
    { category: "Secondi di Carne", name: "Pollo Arrosto", price: "18.00", desc: "A simple, perfectly roasted half-chicken scented with rosemary.", img: getSafeImage("secondi", 39), isSignature: false },
    { category: "Secondi di Carne", name: "Faraona Arrosto", price: "26.00", desc: "Oven-roasted guinea fowl, offering a richer, slightly gamey flavor compared to chicken.", img: getSafeImage("secondi", 40), isSignature: true },
    { category: "Secondi di Carne", name: "Salsiccia e Peperoni", price: "19.00", desc: "A sweet and savory skillet of grilled Italian sausage and roasted bell peppers.", img: getSafeImage("secondi", 41), isSignature: false },
    { category: "Secondi di Carne", name: "Salsiccia e Friarielli", price: "20.00", desc: "Neapolitan classic: savory pork sausage served alongside bitter broccoli rabe.", img: getSafeImage("secondi", 42), isSignature: true },
    { category: "Secondi di Carne", name: "Salsiccia con Polenta", price: "18.50", desc: "Comfort food at its peak: grilled sausages resting on a bed of creamy cornmeal.", img: getSafeImage("secondi", 43), isSignature: false },
    { category: "Secondi di Carne", name: "Trippa alla Romana", price: "19.00", desc: "Tender strips of tripe slow-cooked in tomato sauce and dusted with sharp pecorino.", img: getSafeImage("secondi", 44), isSignature: true },
    { category: "Secondi di Carne", name: "Trippa alla Fiorentina", price: "19.00", desc: "Tuscan-style tripe, cooked until meltingly soft and served with abundant parmesan.", img: getSafeImage("secondi", 45), isSignature: false },
    { category: "Secondi di Carne", name: "Lampredotto", price: "15.00", desc: "The ultimate Florentine street food: the dark stomach of the cow, served in a crusty roll.", img: getSafeImage("secondi", 46), isSignature: true },
    { category: "Secondi di Carne", name: "Fegato alla Veneziana", price: "22.00", desc: "Calf's liver cut into strips and sautéed with a mountain of sweet, melting onions.", img: getSafeImage("secondi", 47), isSignature: true },
    { category: "Secondi di Carne", name: "Coda alla Vaccinara", price: "24.00", desc: "A robust Roman oxtail stew, cooked for hours with celery, tomatoes, and cocoa.", img: getSafeImage("secondi", 48), isSignature: true },
    { category: "Secondi di Carne", name: "Porchetta di Ariccia", price: "23.00", desc: "The famed crispy roasted pork from the Roman hills, bursting with garlic and rosemary.", img: getSafeImage("secondi", 49), isSignature: true },
    { category: "Secondi di Carne", name: "Frico", price: "16.00", desc: "A crispy, savory pancake made entirely from fried Montasio cheese and potatoes.", img: getSafeImage("secondi", 50), isSignature: true },

    // --- SECONDI DI MARE (Glavna Jela od Ribe) ---
    { category: "Secondi di Mare", name: "Seppie in Umido", price: "24.00", desc: "Tender cuttlefish slowly stewed with tomatoes, peas, and white wine.", img: getSafeImage("secondi", 51), isSignature: false },
    { category: "Secondi di Mare", name: "Seppie al Nero", price: "26.00", desc: "Cuttlefish cooked in its own dark ink, producing a briny, jet-black sauce.", img: getSafeImage("secondi", 52), isSignature: true },
    { category: "Secondi di Mare", name: "Calamari Fritti", price: "19.00", desc: "Crispy, golden rings of fried squid, served simply with a lemon wedge.", img: getSafeImage("secondi", 53), isSignature: false },
    { category: "Secondi di Mare", name: "Calamari Ripieni", price: "23.00", desc: "Whole squid tubes stuffed with breadcrumbs, garlic, and their own tentacles.", img: getSafeImage("secondi", 54), isSignature: true },
    { category: "Secondi di Mare", name: "Fritto Misto di Mare", price: "28.00", desc: "A grand seaside basket of lightly battered and fried mixed seafood.", img: getSafeImage("secondi", 55), isSignature: true },
    { category: "Secondi di Mare", name: "Fritto Misto di Pesce", price: "27.00", desc: "An assortment of small local fish, fried until the bones are crispy and edible.", img: getSafeImage("secondi", 56), isSignature: false },
    { category: "Secondi di Mare", name: "Polpo alla Luciana", price: "26.00", desc: "Neapolitan octopus stewed until tender in tomatoes, capers, and olives.", img: getSafeImage("secondi", 57), isSignature: true },
    { category: "Secondi di Mare", name: "Polpo alla Griglia", price: "28.00", desc: "A thick octopus tentacle, boiled then charred on the grill for a smoky finish.", img: getSafeImage("secondi", 58), isSignature: true },
    { category: "Secondi di Mare", name: "Polpo e Patate", price: "25.00", desc: "A warm salad of tender octopus rounds tossed with boiled potatoes and olive oil.", img: getSafeImage("secondi", 59), isSignature: false },
    { category: "Secondi di Mare", name: "Cozze alla Marinara", price: "17.00", desc: "A mountain of fresh mussels steamed open in white wine, garlic, and parsley.", img: getSafeImage("secondi", 60), isSignature: false },
    { category: "Secondi di Mare", name: "Cozze alla Tarantina", price: "18.00", desc: "Mussels served in a slightly spicy, broth-like tomato sauce from Puglia.", img: getSafeImage("secondi", 61), isSignature: false },
    { category: "Secondi di Mare", name: "Impepata di Cozze", price: "17.50", desc: "A Neapolitan specialty: mussels cooked in their own juices with a heavy dose of black pepper.", img: getSafeImage("secondi", 62), isSignature: true },
    { category: "Secondi di Mare", name: "Vongole alla Marinara", price: "21.00", desc: "Clams steamed with garlic, olive oil, and wine, served with crusty bread.", img: getSafeImage("secondi", 63), isSignature: false },
    { category: "Secondi di Mare", name: "Scampi alla Griglia", price: "32.00", desc: "Large, sweet langoustines split and cooked quickly over an open flame.", img: getSafeImage("secondi", 64), isSignature: true },
    { category: "Secondi di Mare", name: "Gamberi alla Griglia", price: "29.00", desc: "Jumbo shrimp grilled with the shell on to lock in moisture and flavor.", img: getSafeImage("secondi", 65), isSignature: false },
    { category: "Secondi di Mare", name: "Gamberi al Limone", price: "27.00", desc: "Plump shrimp sautéed gently in a vibrant lemon and white wine reduction.", img: getSafeImage("secondi", 66), isSignature: false },
    { category: "Secondi di Mare", name: "Gamberi all’Aglio", price: "28.00", desc: "Shrimp sizzling in a pan of olive oil and thinly sliced toasted garlic.", img: getSafeImage("secondi", 67), isSignature: false },
    { category: "Secondi di Mare", name: "Baccalà alla Vicentina", price: "26.00", desc: "Salt cod beaten into a creamy consistency, slowly cooked with onions and milk.", img: getSafeImage("secondi", 68), isSignature: true },
    { category: "Secondi di Mare", name: "Baccalà Mantecato", price: "24.00", desc: "Venetian whipped salt cod mousse, served over grilled squares of polenta.", img: getSafeImage("secondi", 69), isSignature: true },
    { category: "Secondi di Mare", name: "Baccalà alla Livornese", price: "25.00", desc: "Chunks of salt cod simmered in a rich tomato sauce with garlic and parsley.", img: getSafeImage("secondi", 70), isSignature: false },
    { category: "Secondi di Mare", name: "Stoccafisso all’Anconetana", price: "27.00", desc: "Air-dried cod stewed for hours with potatoes, tomatoes, and black olives.", img: getSafeImage("secondi", 71), isSignature: true },
    { category: "Secondi di Mare", name: "Orata al Forno", price: "29.00", desc: "A whole sea bream baked in the oven with a crust of potatoes and rosemary.", img: getSafeImage("secondi", 72), isSignature: false },
    { category: "Secondi di Mare", name: "Branzino al Forno", price: "30.00", desc: "Whole European sea bass baked simply with lemon and olive oil.", img: getSafeImage("secondi", 73), isSignature: false },
    { category: "Secondi di Mare", name: "Branzino alla Griglia", price: "32.00", desc: "A butterflied sea bass, charred on the grill to impart a smoky sea flavor.", img: getSafeImage("secondi", 74), isSignature: false },
    { category: "Secondi di Mare", name: "Pesce Spada alla Siciliana", price: "28.00", desc: "A thick swordfish steak cooked with tomatoes, capers, olives, and pine nuts.", img: getSafeImage("secondi", 75), isSignature: true },
    { category: "Secondi di Mare", name: "Pesce Spada alla Griglia", price: "26.00", desc: "Swordfish steak grilled simply, dressed with a squeeze of fresh lemon (salmoriglio).", img: getSafeImage("secondi", 76), isSignature: false },
    { category: "Secondi di Mare", name: "Tonno alla Siciliana", price: "27.00", desc: "Fresh tuna steak pan-seared and topped with a sweet and sour onion relish.", img: getSafeImage("secondi", 77), isSignature: false },
    { category: "Secondi di Mare", name: "Sarde a Beccafico", price: "21.00", desc: "Sicilian stuffed sardines rolled with breadcrumbs, raisins, and pine nuts.", img: getSafeImage("secondi", 78), isSignature: true },
    { category: "Secondi di Mare", name: "Sarde in Saor", price: "20.00", desc: "Venetian sweet and sour sardines, marinated in vinegar, onions, and raisins.", img: getSafeImage("secondi", 79), isSignature: true },
    { category: "Secondi di Mare", name: "Alici Marinate", price: "15.00", desc: "Fresh anchovy fillets 'cooked' in a bright lemon juice and olive oil marinade.", img: getSafeImage("secondi", 80), isSignature: false },
    { category: "Secondi di Mare", name: "Alici Fritte", price: "16.00", desc: "A plate of whole fresh anchovies, lightly dusted in flour and deep-fried.", img: getSafeImage("secondi", 81), isSignature: false },
    { category: "Secondi di Mare", name: "Fritto di Paranza", price: "25.00", desc: "A traditional fisherman's fry of tiny, whole assorted fish eaten like chips.", img: getSafeImage("secondi", 82), isSignature: true },

    // --- DOLCI (Dezerti) ---
    { category: "Dolci (Dezerti)", name: "Tiramisu", price: "12.00", desc: "The absolute Italian classic: espresso-soaked ladyfingers layered with airy mascarpone cream.", img: getSafeImage("dolci", 0), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Panna Cotta", price: "10.00", desc: "A silky, wobbly 'cooked cream' dessert topped with a tart mixed berry coulis.", img: getSafeImage("dolci", 1), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Cannoli Siciliani", price: "11.00", desc: "Crispy, blistered pastry tubes piped full of sweetened sheep's milk ricotta.", img: getSafeImage("dolci", 2), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Cassata Siciliana", price: "13.00", desc: "An extravagant sponge cake moistened with liqueur, layered with ricotta, and draped in green marzipan.", img: getSafeImage("dolci", 3), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Sfogliatella", price: "9.00", desc: "A shell-shaped Neapolitan pastry featuring incredibly shattered, crispy layers hiding a citrus-ricotta filling.", img: getSafeImage("dolci", 4), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Babà al Rum", price: "10.00", desc: "A tall, mushroom-shaped sponge cake thoroughly drenched in a sticky, sweet rum syrup.", img: getSafeImage("dolci", 5), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Zeppole di San Giuseppe", price: "9.50", desc: "Deep-fried rings of choux pastry piped high with pastry cream and topped with an amarena cherry.", img: getSafeImage("dolci", 6), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Bomboloni", price: "8.00", desc: "Italian doughnuts coated in granulated sugar and stuffed to the brim with custard or Nutella.", img: getSafeImage("dolci", 7), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Maritozzi", price: "8.50", desc: "Roman sweet, soft yeast buns split open and overflowing with lightly sweetened whipped cream.", img: getSafeImage("dolci", 8), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Cornetti", price: "5.00", desc: "The Italian cousin of the croissant, softer and sweeter, perfect for dipping in cappuccino.", img: getSafeImage("dolci", 9), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Crostata", price: "8.00", desc: "A rustic, homestyle Italian tart made with buttery shortcrust pastry.", img: getSafeImage("dolci", 10), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Crostata di Frutta", price: "9.50", desc: "A beautiful tart shell filled with vanilla pastry cream and a crown of glazed fresh fruits.", img: getSafeImage("dolci", 11), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Crostata alla Marmellata", price: "8.50", desc: "The classic lattice-topped tart filled with thick, tart apricot or berry jam.", img: getSafeImage("dolci", 12), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Torta Caprese", price: "11.00", desc: "A dense, flourless chocolate and almond cake originating from the island of Capri.", img: getSafeImage("dolci", 13), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Torta della Nonna", price: "10.50", desc: "'Grandmother's cake': a shortcrust pie filled with lemon-scented custard and topped with pine nuts.", img: getSafeImage("dolci", 14), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Torta Paradiso", price: "9.00", desc: "An impossibly light, airy, and buttery sponge cake dusted heavily with powdered sugar.", img: getSafeImage("dolci", 15), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Torta Tenerina", price: "10.00", desc: "A famously flat, crackly-topped chocolate cake from Ferrara with a molten, tender center.", img: getSafeImage("dolci", 16), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Torta Mimosa", price: "12.00", desc: "A dome-shaped sponge cake covered in yellow cake cubes to resemble the mimosa flower.", img: getSafeImage("dolci", 17), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Torta della Foresta Nera Italiana", price: "13.00", desc: "The Italian interpretation of Black Forest cake, laced with cherry liqueur and whipped cream.", img: getSafeImage("dolci", 18), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Panettone", price: "14.00", desc: "The towering, airy Milanese Christmas bread studded with candied citrus and raisins.", img: getSafeImage("dolci", 19), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Pandoro", price: "13.50", desc: "A golden, star-shaped Veronese holiday cake, rich in butter and dusted with vanilla sugar.", img: getSafeImage("dolci", 20), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Colomba Pasquale", price: "14.00", desc: "The Easter dove: a Panettone-like dough baked in a dove shape, crowned with almonds and pearl sugar.", img: getSafeImage("dolci", 21), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Torrone", price: "10.00", desc: "A dense, chewy nougat confection loaded with toasted almonds and honey.", img: getSafeImage("dolci", 22), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Amaretti", price: "7.00", desc: "Small, dome-shaped almond macaroons with a distinctively bitter-sweet flavor.", img: getSafeImage("dolci", 23), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Cantucci", price: "8.00", desc: "Hard, twice-baked Tuscan almond biscotti, traditionally dunked in sweet Vin Santo.", img: getSafeImage("dolci", 24), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Biscotti", price: "6.00", desc: "A selection of classic, crunchy Italian dipping cookies.", img: getSafeImage("dolci", 25), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Baci di Dama", price: "8.50", desc: "'Lady's kisses': two hazelnut cookies sandwiching a drop of dark chocolate.", img: getSafeImage("dolci", 26), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Ricciarelli", price: "9.00", desc: "Soft, chewy, and deeply almond-flavored oval cookies from Siena.", img: getSafeImage("dolci", 27), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Brutti ma Buoni", price: "7.50", desc: "'Ugly but good': irregular, crunchy meringue cookies packed with toasted hazelnuts.", img: getSafeImage("dolci", 28), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Savoiardi", price: "6.50", desc: "Light, dry sponge finger cookies, the essential building block of Tiramisu.", img: getSafeImage("dolci", 29), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Pizzelle", price: "7.00", desc: "Thin, crisp waffle cookies stamped with intricate traditional iron patterns.", img: getSafeImage("dolci", 30), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Panforte", price: "12.00", desc: "A dense, chewy medieval Sienese cake packed with fruits, nuts, and intense spices.", img: getSafeImage("dolci", 31), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Struffoli", price: "11.00", desc: "A mound of deep-fried dough marbles bound together by warm honey and sprinkles.", img: getSafeImage("dolci", 32), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Cartellate", price: "10.00", desc: "Apulian festive pastry rosettes, fried and soaked in vincotto (grape must).", img: getSafeImage("dolci", 33), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Chiacchiere", price: "8.00", desc: "Carnival 'chatter': thin ribbons of dough fried until bubbly and dusted with sugar.", img: getSafeImage("dolci", 34), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Castagnole", price: "8.50", desc: "Small, soft fried dough balls, often spiked with anise or citrus liqueur.", img: getSafeImage("dolci", 35), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Frittelle", price: "9.00", desc: "Venetian carnival fritters, sometimes filled with raisins and pine nuts or zabaglione.", img: getSafeImage("dolci", 36), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Graffe Napoletane", price: "9.50", desc: "Neapolitan doughnuts made with a potato-enriched dough, incredibly soft and sugary.", img: getSafeImage("dolci", 37), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Gelato", price: "6.00", desc: "A scoop of traditional Italian ice cream, denser and smoother than regular ice cream.", img: getSafeImage("dolci", 38), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Gelato al Pistacchio", price: "7.50", desc: "Premium gelato made with imported, intensely green Bronte pistachios.", img: getSafeImage("dolci", 39), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Gelato alla Nocciola", price: "7.00", desc: "A rich, roasted hazelnut gelato, a staple flavor of northern Italy.", img: getSafeImage("dolci", 40), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Gelato al Cioccolato", price: "7.00", desc: "Deep, dark, and velvety chocolate artisan gelato.", img: getSafeImage("dolci", 41), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Gelato alla Stracciatella", price: "7.00", desc: "Sweet cream gelato marbled with fine, crunchy shards of dark chocolate.", img: getSafeImage("dolci", 42), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Gelato alla Vaniglia", price: "6.50", desc: "Classic vanilla gelato speckled with real vanilla bean seeds.", img: getSafeImage("dolci", 43), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Sorbetto al Limone", price: "6.00", desc: "A frosty, palate-cleansing lemon sorbet, perfectly sweet and sharply tart.", img: getSafeImage("dolci", 44), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Granita Siciliana", price: "8.00", desc: "A semi-frozen, icy, and refreshing Sicilian dessert eaten with a spoon.", img: getSafeImage("dolci", 45), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Granita al Limone", price: "8.50", desc: "The purest form of granita, made simply from water, sugar, and zesty lemons.", img: getSafeImage("dolci", 46), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Granita alla Mandorla", price: "9.00", desc: "A cloudy, sweet, and nutty almond granita, an absolute Sicilian morning ritual.", img: getSafeImage("dolci", 47), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Affogato", price: "9.50", desc: "A scoop of vanilla gelato 'drowned' under a shot of steaming hot espresso.", img: getSafeImage("dolci", 48), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Semifreddo", price: "10.50", desc: "A 'half-cold' dessert, offering the texture of frozen mousse or ice-cream cake.", img: getSafeImage("dolci", 49), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Zabaione", price: "11.00", desc: "A warm, frothy custard vigorously whisked from egg yolks, sugar, and Marsala wine.", img: getSafeImage("dolci", 50), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Budino", price: "9.00", desc: "A dense, molded Italian pudding, heavily flavored with dark chocolate or caramel.", img: getSafeImage("dolci", 51), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Crema Pasticcera", price: "8.00", desc: "A bowl of simple, rich Italian pastry cream, flavored with lemon zest or vanilla.", img: getSafeImage("dolci", 52), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Crema Catalana Italiana", price: "10.00", desc: "A creamy custard base topped with a brittle layer of hard caramel.", img: getSafeImage("dolci", 53), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Bonet", price: "12.00", desc: "A Piedmontese chocolate and amaretti flan, laced with rum or cognac.", img: getSafeImage("dolci", 54), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Pastiera Napoletana", price: "13.00", desc: "A complex Easter tart filled with ricotta, candied fruit, and boiled wheat berries.", img: getSafeImage("dolci", 55), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Delizia al Limone", price: "12.50", desc: "A dome of sponge cake filled and coated with a smooth, bright lemon cream.", img: getSafeImage("dolci", 56), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Tartufo di Pizzo", price: "11.00", desc: "A molded ball of hazelnut gelato with a molten chocolate heart, dusted in cocoa.", img: getSafeImage("dolci", 57), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Zuccotto", price: "13.00", desc: "A dome-shaped Florentine dessert layered with cake, ricotta, and chocolate.", img: getSafeImage("dolci", 58), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Sbrisolona", price: "10.00", desc: "A hard, crumbly almond tart from Mantua, broken into jagged pieces by hand.", img: getSafeImage("dolci", 59), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Castagnaccio", price: "9.50", desc: "An autumnal, naturally sweet flat cake made entirely from chestnut flour, rosemary, and pine nuts.", img: getSafeImage("dolci", 60), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Seadas", price: "12.00", desc: "A large, deep-fried Sardinian pastry stuffed with sour pecorino and drenched in warm honey.", img: getSafeImage("dolci", 61), isSignature: true },
    { category: "Dolci (Dezerti)", name: "Pardulas", price: "11.00", desc: "Small, star-shaped Sardinian tartlets filled with a saffron and ricotta mixture.", img: getSafeImage("dolci", 62), isSignature: false },
    { category: "Dolci (Dezerti)", name: "Biancomangiare", price: "9.00", desc: "An ancient, delicate white almond milk pudding set with cornstarch.", img: getSafeImage("dolci", 63), isSignature: false },

    // --- CAFFÈ E BEVANDE ---
    { category: "Caffetteria", name: "Espresso", price: "2.50", desc: "A short, intense shot of pure Italian dark roast coffee with a thick crema.", img: getSafeImage("coffee", 0), isSignature: true },
    { category: "Caffetteria", name: "Cappuccino", price: "4.00", desc: "A morning staple: one-third espresso, one-third steamed milk, one-third deep foam.", img: getSafeImage("coffee", 1), isSignature: true },
    { category: "Caffetteria", name: "Caffè Macchiato", price: "3.00", desc: "An espresso shot 'stained' with just a drop of hot foamed milk.", img: getSafeImage("coffee", 2), isSignature: false },
    { category: "Caffetteria", name: "Caffè Latte", price: "4.50", desc: "A tall glass of warm milk gently mixed with a single shot of espresso.", img: getSafeImage("coffee", 3), isSignature: false },
    { category: "Caffetteria", name: "Latte Macchiato", price: "4.50", desc: "A glass of steamed milk beautifully 'stained' by pouring espresso over the top.", img: getSafeImage("coffee", 4), isSignature: false },
    { category: "Caffetteria", name: "Caffè Corretto", price: "5.50", desc: "An espresso 'corrected' with a shot of strong liquor, typically Grappa or Sambuca.", img: getSafeImage("coffee", 5), isSignature: true },
    { category: "Caffetteria", name: "Caffè Shakerato", price: "6.00", desc: "Espresso shaken vigorously with ice and sugar syrup until an incredibly thick foam forms.", img: getSafeImage("coffee", 6), isSignature: true },
    { category: "Caffetteria", name: "Marocchino", price: "4.00", desc: "A layered shot of espresso, cocoa powder, and milk foam served in a small glass.", img: getSafeImage("coffee", 7), isSignature: true },
    { category: "Caffetteria", name: "Bicerin", price: "6.50", desc: "A historic Piedmontese drink layering hot espresso, drinking chocolate, and heavy cream.", img: getSafeImage("coffee", 8), isSignature: true },
    { category: "Caffetteria", name: "Granita con Brioche", price: "10.00", desc: "The ultimate Sicilian summer breakfast: an icy almond or coffee granita served alongside a warm, buttery brioche bun.", img: getSafeImage("coffee", 9), isSignature: true }
  ]
};
// KRAJ FAJLA: src/DemoData/italianMassiveData.js