import { generateAiImage } from './v8AiVision.js';

const ITALIAN_ALL_ITEMS = [
  ...["Spaghetti Carbonara", "Cacio e Pepe", "Amatriciana", "Pasta alla Gricia", "Spaghetti Aglio e Olio", "Pasta al Pesto Genovese", "Tagliatelle al Ragù Bolognese", "Pappardelle al Cinghiale", "Lasagne alla Bolognese", "Lasagne al Pesto", "Penne all’Arrabbiata", "Pasta alla Norma", "Pasta Puttanesca", "Linguine alle Vongole", "Spaghetti ai Frutti di Mare", "Fettuccine al Tartufo", "Orecchiette con Cime di Rapa", "Trofie al Pesto", "Ravioli Ricotta e Spinaci", "Ravioli al Tartufo", "Tortellini in Brodo", "Tortellini alla Panna", "Cannelloni", "Gnocchi al Pomodoro", "Gnocchi al Gorgonzola", "Gnocchi alla Sorrentina"].map((name, idx) => ({ category: "Pasta", name, price: "18.00", desc: `An exquisite ${name}, meticulously prepared with DOP-certified ingredients, fresh herbs, and cold-pressed Tuscan olive oil.`, img: generateAiImage(name, "premium Italian restaurant"), isSignature: idx === 0 })),
  ...["Pizza Margherita", "Pizza Marinara", "Pizza Napoletana", "Pizza Diavola", "Pizza Capricciosa", "Pizza Quattro Formaggi", "Pizza Quattro Stagioni", "Pizza Prosciutto e Funghi", "Pizza Ortolana", "Pizza Bianca", "Pizza al Tartufo", "Calzone", "Focaccia Genovese", "Focaccia Barese", "Focaccia al Rosmarino"].map((name, idx) => ({ category: "Pizza & Focaccia", name, price: "15.00", desc: `Authentic, stone-baked ${name} with a perfectly blistered crust, rich San Marzano tomato sauce, and fresh artisan mozzarella.`, img: generateAiImage(name, "premium Italian restaurant"), isSignature: false })),
  ...["Risotto alla Milanese", "Risotto ai Funghi Porcini", "Risotto al Tartufo", "Risotto ai Frutti di Mare", "Risotto al Limone", "Risotto alla Zucca", "Risotto al Radicchio", "Risotto al Gorgonzola", "Risi e Bisi", "Arancini Siciliani", "Supplì"].map((name, idx) => ({ category: "Risotto & Rice Dishes", name, price: "22.00", desc: `A culinary masterpiece, this creamy ${name} features slow-simmered Carnaroli rice infused with delicate regional flavors.`, img: generateAiImage(name, "premium Italian restaurant"), isSignature: false })),
  ...["Ossobuco alla Milanese", "Saltimbocca alla Romana", "Cotoletta alla Milanese", "Pollo alla Cacciatora", "Vitello Tonnato", "Brasato al Barolo", "Bistecca alla Fiorentina", "Porchetta", "Polpette al Sugo", "Involtini di Carne", "Spezzatino di Manzo", "Abbacchio alla Romana", "Salsiccia e Peperoni"].map((name, idx) => ({ category: "Meat Dishes", name, price: "32.00", desc: `Incredibly tender ${name}, slow-cooked to perfection and seasoned with a harmonious blend of imported Italian herbs and fine wine.`, img: generateAiImage(name, "premium Italian restaurant"), isSignature: name === "Bistecca alla Fiorentina" })),
  ...["Branzino al Forno", "Orata al Forno", "Fritto Misto di Mare", "Calamari Fritti", "Polpo alla Griglia", "Polpo e Patate", "Seppie al Nero", "Baccalà alla Vicentina", "Baccalà Mantecato", "Zuppa di Pesce", "Cacciucco", "Impepata di Cozze", "Cozze alla Marinara", "Gamberi all’Aglio"].map((name, idx) => ({ category: "Fish & Seafood", name, price: "35.00", desc: `Freshly caught Mediterranean ${name}, elegantly prepared with a touch of lemon, garlic, and golden olive oil.`, img: generateAiImage(name, "premium Italian restaurant"), isSignature: false })),
  ...["Minestrone", "Ribollita", "Pasta e Fagioli", "Pasta e Ceci", "Zuppa Toscana", "Acquacotta", "Stracciatella alla Romana", "Pappa al Pomodoro", "Brodo con Tortellini", "Zuppa di Lenticchie"].map((name, idx) => ({ category: "Soups & Traditional", name, price: "14.00", desc: `A comforting and rustic ${name}, steeped in tradition and made with vibrant, locally sourced seasonal vegetables.`, img: generateAiImage(name, "premium Italian restaurant"), isSignature: false })),
  ...["Bruschetta al Pomodoro", "Bruschetta ai Funghi", "Caprese", "Prosciutto e Melone", "Prosciutto di Parma con Burrata", "Burrata con Pomodorini", "Carpaccio di Manzo", "Carpaccio di Tonno", "Vitello Tonnato", "Crostini Toscani", "Olive Ascolane", "Mozzarella in Carrozza", "Fiori di Zucca Fritti", "Melanzane alla Parmigiana", "Arancini"].map((name, idx) => ({ category: "Appetizers & Antipasti", name, price: "16.00", desc: `The ultimate starter, our ${name} offers a perfect balance of textures and elevated flavors to awaken your palate.`, img: generateAiImage(name, "premium Italian restaurant"), isSignature: false })),
  ...["Parmigiana di Melanzane", "Caponata Siciliana", "Peperonata", "Carciofi alla Romana", "Carciofi alla Giudia", "Verdure Grigliate", "Patate al Rosmarino", "Zucchine alla Scapece", "Fagioli all’Uccelletto", "Insalata Panzanella"].map((name, idx) => ({ category: "Vegetables & Side Dishes", name, price: "12.00", desc: `Beautifully crafted ${name}, celebrating the natural essence and vibrant colors of the Italian countryside.`, img: generateAiImage(name, "premium Italian restaurant"), isSignature: false })),
  ...["Panino con Porchetta", "Panino Caprese", "Panino Prosciutto e Mozzarella", "Piadina Romagnola", "Tramezzini", "Lampredotto", "Panzerotti", "Pizza al Taglio", "Sfincione Siciliano", "Focaccia Ripiena"].map((name, idx) => ({ category: "Sandwiches & Street Food", name, price: "10.00", desc: `Premium artisanal ${name}, combining freshly baked breads with the highest quality cured meats and cheeses.`, img: generateAiImage(name, "premium Italian restaurant"), isSignature: false })),
  ...["Tiramisù", "Panna Cotta", "Cannoli Siciliani", "Cassata Siciliana", "Sfogliatella", "Babà Napoletano", "Zeppole", "Bomboloni", "Crostata", "Torta Caprese", "Torta della Nonna", "Zabaione", "Semifreddo", "Affogato", "Gelato", "Granita Siciliana", "Amaretti", "Cantucci", "Panettone", "Pandoro", "Torrone", "Ricciarelli"].map((name, idx) => ({ category: "Desserts", name, price: "12.00", desc: `A decadent, melt-in-your-mouth ${name}, masterfully crafted to provide the ultimate sweet Italian finale.`, img: generateAiImage(name, "premium Italian restaurant"), isSignature: name === "Tiramisù" }))
];

export const ITALIAN_MASSIVE_MENU = { restaurantName: "Bella Napoli", themeColor: "#eab308", currency: "€", items: ITALIAN_ALL_ITEMS };