import { generateAiImage } from './v8AiVision.js';

const RAW_MEXICAN_ITEMS = [
  ...["Tacos al Pastor", "Tacos de Carne Asada", "Tacos de Birria", "Tacos de Barbacoa", "Tacos de Carnitas", "Tacos de Pescado", "Tacos de Camarón", "Quesabirria", "Quesadillas", "Burritos", "Chimichangas", "Fajitas", "Nachos", "Tostadas", "Gorditas", "Sopes", "Huaraches", "Tlacoyos", "Tamales", "Tortas", "Cemitas", "Molletes", "Elote", "Esquites", "Pambazos", "Flautas", "Taquitos", "Empanadas Mexicanas", "Sincronizadas", "Gringas", "Chalupas", "Papadzules", "Panuchos", "Salbutes", "Tlayudas", "Memelas", "Tacos Dorados"].map((name, idx) => ({ category: "Tacos y Antojitos", name, price: "12.50", desc: `A vibrant and elevated ${name}, slow-cooked with fire-roasted heirloom spices and served with hand-pressed artisanal tortillas.`, img: generateAiImage(name, "authentic premium Mexican"), isSignature: idx === 0 })),
  ...["Birria", "Enchiladas Rojas", "Enchiladas Verdes", "Enchiladas Suizas", "Chiles Rellenos", "Chiles en Nogada", "Mole Poblano", "Mole Negro", "Pollo con Mole", "Cochinita Pibil", "Poc Chuc", "Barbacoa", "Carnitas", "Carne Asada", "Alambre", "Discada", "Pollo Asado", "Pollo Adobado", "Camarones a la Diabla", "Camarones al Ajillo", "Pescado a la Veracruzana", "Aguachile", "Ceviche Mexicano", "Cóctel de Camarones", "Nopales Asados", "Albóndigas Mexicanas", "Picadillo Mexicano", "Carne Guisada", "Costillas en Salsa Verde", "Pollo en Salsa Verde", "Pollo Tinga", "Tinga de Res", "Enfrijoladas", "Entomatadas", "Enmoladas", "Pastel Azteca", "Tamales de Pollo", "Tamales de Cerdo", "Tamales de Elote", "Tamales Oaxaqueños", "Cabrito al Pastor", "Mixiotes", "Cecina", "Carne Adobada", "Puerco en Chile Verde", "Asado de Boda", "Chile Colorado"].map((name, idx) => ({ category: "Platos Fuertes", name, price: "24.00", desc: `Exquisite ${name}, honoring the rich heritage of Mexican culinary arts with deep, complex flavors and premium meats.`, img: generateAiImage(name, "authentic premium Mexican"), isSignature: name === "Mole Poblano" })),
  ...["Pozole Rojo", "Pozole Verde", "Menudo", "Caldo de Res", "Caldo de Pollo", "Sopa de Tortilla", "Sopa de Lima"].map((name, idx) => ({ category: "Sopas y Caldos", name, price: "16.00", desc: `Hearty and comforting ${name}, featuring a deeply aromatic broth slow-simmered for hours with fresh chilies.`, img: generateAiImage(name, "authentic premium Mexican"), isSignature: false })),
  ...["Chilaquiles", "Nopales con Huevo", "Huevos Rancheros", "Huevos a la Mexicana", "Machaca con Huevo", "Migas Mexicanas", "Chorizo con Huevo", "Chorizo con Papas"].map((name, idx) => ({ category: "Desayunos Tradicionales", name, price: "14.50", desc: `The perfect culinary start to your day: farm-fresh ${name} packed with robust and authentic Mexican flavors.`, img: generateAiImage(name, "authentic premium Mexican"), isSignature: false })),
  ...["Guacamole", "Pico de Gallo", "Salsa Roja", "Salsa Verde", "Chile con Queso", "Frijoles Refritos", "Frijoles Charros", "Arroz Mexicano", "Rajas con Crema", "Calabacitas a la Mexicana", "Frijoles Puercos", "Tortillas de Maíz", "Tortillas de Harina", "Totopos"].map((name, idx) => ({ category: "Salsas y Guarniciones", name, price: "6.00", desc: `House-made ${name}, prepared daily with the freshest avocados, ripe tomatoes, and locally sourced chilies.`, img: generateAiImage(name, "authentic premium Mexican"), isSignature: false })),
  ...["Buñuelos Mexicanos", "Churros", "Flan Mexicano", "Tres Leches Cake", "Pastel de Elote", "Arroz con Leche", "Jericalla", "Cajeta", "Conchas", "Pan de Muerto", "Rosca de Reyes", "Capirotada", "Alegrías", "Palanquetas", "Mazapán Mexicano", "Cocadas", "Empanadas Dulces"].map((name, idx) => ({ category: "Postres Dulces", name, price: "9.00", desc: `A masterful sweet ending, this ${name} blends traditional techniques with rich, indulgent caramel and vanilla notes.`, img: generateAiImage(name, "authentic premium Mexican"), isSignature: name === "Churros" }))
];

export const MEXICAN_MASSIVE_MENU = { restaurantName: "La Cantina del Fuego", themeColor: "#22c55e", currency: "$", items: RAW_MEXICAN_ITEMS };