// POČETAK FAJLA: src/DemoData/mexicanMassiveData.js

// 🔥 BAZA SIGURNIH HD SLIKA (BEZ AI HALUCINACIJA I GREŠAKA) 🔥
const SAFE_IMAGE_POOLS = {
  tacos: [
    "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1613514785940-daed07799d9b?auto=format&fit=crop&w=800&q=80"
  ],
  antojitos: [
    "https://images.unsplash.com/photo-1582285514681-30d8804cbff8?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1512805147242-c3e794fc25ed?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?auto=format&fit=crop&w=800&q=80"
  ],
  enchiladas: [
    "https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1618698188165-8baf3d1a8e1e?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1584346067083-d922a76f2f2c?auto=format&fit=crop&w=800&q=80"
  ],
  breakfast: [
    "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80"
  ],
  salsas: [
    "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=80"
  ],
  mains: [
    "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1564834724105-918b73d1b9e0?auto=format&fit=crop&w=800&q=80"
  ],
  soups: [
    "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1604152135912-04a022e23696?auto=format&fit=crop&w=800&q=80"
  ],
  seafood: [
    "https://images.unsplash.com/photo-1599084990807-360e1d4b0433?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1559742811-822873691fc8?auto=format&fit=crop&w=800&q=80"
  ],
  desserts: [
    "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80"
  ],
  drinks: [
    "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1561395049-69684aacf8de?auto=format&fit=crop&w=800&q=80",
    "https://images.unsplash.com/photo-1576092762791-dd9e2220afa1?auto=format&fit=crop&w=800&q=80"
  ]
};

const getSafeImage = (poolName, index) => {
  const pool = SAFE_IMAGE_POOLS[poolName] || SAFE_IMAGE_POOLS.mains;
  return pool[index % pool.length];
};

export const MEXICAN_MASSIVE_MENU = { 
  restaurantName: "La Cantina del Fuego", 
  themeColor: "#22c55e", 
  currency: "$", 
  items: [
    // --- TACOS ---
    { category: "Tacos", name: "Tacos al Pastor", price: "12.50", desc: "Marinated spit-roasted pork with sweet pineapple and onions on a fresh corn tortilla.", img: getSafeImage("tacos", 1), isSignature: true },
    { category: "Tacos", name: "Tacos de Asada", price: "14.00", desc: "Classic tacos packed with juicy grilled beef steak and fresh salsa.", img: getSafeImage("tacos", 2), isSignature: true },
    { category: "Tacos", name: "Tacos de Carnitas", price: "13.00", desc: "Traditional slow-cooked, crispy-seared Mexican pulled pork.", img: getSafeImage("tacos", 3), isSignature: false },
    { category: "Tacos", name: "Tacos de Barbacoa", price: "14.50", desc: "Ultra-tender slow-roasted beef (barbacoa) topped with cilantro and onions.", img: getSafeImage("tacos", 4), isSignature: false },
    { category: "Tacos", name: "Tacos de Birria", price: "15.00", desc: "Famous tacos with meat stewed in a rich, spiced broth, served with a cup of consommé for dipping.", img: getSafeImage("tacos", 5), isSignature: true },
    { category: "Tacos", name: "Tacos de Pollo", price: "11.00", desc: "Simple yet delicious tacos with perfectly seasoned grilled chicken.", img: getSafeImage("tacos", 6), isSignature: false },
    { category: "Tacos", name: "Tacos de Pescado", price: "13.50", desc: "Baja-style fish tacos, fried to a crisp and topped with creamy cabbage slaw.", img: getSafeImage("tacos", 7), isSignature: false },
    { category: "Tacos", name: "Tacos de Camarón", price: "15.50", desc: "Spicy tacos with grilled shrimp and a refreshing lime dressing.", img: getSafeImage("tacos", 8), isSignature: true },
    { category: "Tacos", name: "Tacos de Lengua", price: "16.00", desc: "A Mexican delicacy: tacos featuring incredibly tender beef tongue.", img: getSafeImage("tacos", 9), isSignature: false },
    { category: "Tacos", name: "Tacos de Chorizo", price: "12.00", desc: "Tacos loaded with fiery Mexican pork sausage.", img: getSafeImage("tacos", 10), isSignature: false },
    { category: "Tacos", name: "Tacos de Suadero", price: "13.50", desc: "Savory tacos made from tender and fatty slow-cooked beef.", img: getSafeImage("tacos", 11), isSignature: false },
    { category: "Tacos", name: "Tacos de Cabeza", price: "15.00", desc: "Melt-in-your-mouth tacos made from tender roasted beef head meat.", img: getSafeImage("tacos", 12), isSignature: false },
    { category: "Tacos", name: "Tacos Gobernador", price: "16.50", desc: "Cheesy baked shrimp tacos with vegetables and melted Oaxaca cheese.", img: getSafeImage("tacos", 13), isSignature: true },
    { category: "Tacos", name: "Tacos Dorados", price: "11.50", desc: "Rolled and deep-fried crispy tacos (flautas) filled with chicken or beef.", img: getSafeImage("tacos", 14), isSignature: false },
    { category: "Tacos", name: "Tacos de Canasta", price: "10.00", desc: "'Basket tacos', softly steamed and typically filled with beans and potatoes.", img: getSafeImage("tacos", 15), isSignature: false },
    { category: "Tacos", name: "Tacos Árabes", price: "14.00", desc: "Puebla's Arab-Mexican fusion: spit-roasted pork served in a pita-style tortilla.", img: getSafeImage("tacos", 16), isSignature: true },
    { category: "Tacos", name: "Taco Placero", price: "11.00", desc: "Large tacos loaded with chicharrón (pork rinds), cheese, avocado, and peppers.", img: getSafeImage("tacos", 17), isSignature: false },
    { category: "Tacos", name: "Taco Campechano", price: "14.50", desc: "A glorious mix of crispy chicharrón, longaniza sausage, and asada in a single taco.", img: getSafeImage("tacos", 18), isSignature: true },
    { category: "Tacos", name: "Taco de Tripa", price: "13.00", desc: "Tacos featuring crispy fried beef tripe.", img: getSafeImage("tacos", 19), isSignature: false },
    { category: "Tacos", name: "Taco de Buche", price: "13.50", desc: "Spicy tacos filled with fried pork stomach.", img: getSafeImage("tacos", 20), isSignature: false },
    { category: "Tacos", name: "Taco de Chicharrón", price: "12.00", desc: "Delicious tacos with softened pork rinds stewed in tangy green salsa.", img: getSafeImage("tacos", 21), isSignature: false },
    { category: "Tacos", name: "Taco de Nopal", price: "10.50", desc: "Vegetarian tacos featuring grilled edible cactus leaves.", img: getSafeImage("tacos", 22), isSignature: false },
    { category: "Tacos", name: "Taco de Papa", price: "9.50", desc: "Crispy fried tacos filled with seasoned mashed potatoes.", img: getSafeImage("tacos", 23), isSignature: false },
    { category: "Tacos", name: "Taco de Frijol", price: "9.00", desc: "The simplest tacos filled with smooth black bean puree.", img: getSafeImage("tacos", 24), isSignature: false },
    { category: "Tacos", name: "Taco de Huevo", price: "10.00", desc: "Morning tacos loaded with Mexican-style scrambled eggs.", img: getSafeImage("tacos", 25), isSignature: false },
    { category: "Tacos", name: "Taco de Canasta de Papa", price: "10.00", desc: "Soft basket tacos filled with mashed potatoes.", img: getSafeImage("tacos", 26), isSignature: false },
    { category: "Tacos", name: "Taco de Canasta de Frijol", price: "10.00", desc: "Soft basket tacos filled with black beans.", img: getSafeImage("tacos", 27), isSignature: false },
    { category: "Tacos", name: "Taco de Canasta de Chicharrón", price: "11.00", desc: "Soft basket tacos filled with pork rinds.", img: getSafeImage("tacos", 28), isSignature: false },

    // --- ANTOJITOS (Street Food) ---
    { category: "Antojitos (Street Food)", name: "Quesabirria", price: "16.00", desc: "An extremely juicy fusion of a quesadilla and tacos de birria with melted Oaxacan cheese.", img: getSafeImage("antojitos", 1), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Quesadillas", price: "11.00", desc: "Classic tortillas stuffed with melting Mexican cheese.", img: getSafeImage("antojitos", 2), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Sincronizadas", price: "12.50", desc: "Two wheat tortillas filled with cheese and ham, then grilled to perfection.", img: getSafeImage("antojitos", 3), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Gringas", price: "13.50", desc: "A wheat tortilla quesadilla filled with Al Pastor pork and pineapple.", img: getSafeImage("antojitos", 4), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Burritos", price: "14.00", desc: "Large flour tortilla rolled with meat, rice, and beans.", img: getSafeImage("antojitos", 5), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Burrito de Carne Asada", price: "16.00", desc: "Premium burrito loaded with beef steak, pico de gallo, and avocado.", img: getSafeImage("antojitos", 6), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Burrito de Pollo", price: "13.50", desc: "Burrito packed with Mexican chicken and red rice.", img: getSafeImage("antojitos", 7), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Burrito de Carnitas", price: "14.50", desc: "Burrito stuffed with crispy fried pulled pork.", img: getSafeImage("antojitos", 8), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Chimichangas", price: "15.50", desc: "Deep-fried golden burrito, topped with sour cream and guacamole.", img: getSafeImage("antojitos", 9), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Gorditas", price: "11.00", desc: "Thick, fried cornmeal pockets stuffed with cheese, meat, and salsa.", img: getSafeImage("antojitos", 10), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Gorditas de Chicharrón", price: "12.00", desc: "Gorditas stuffed with pork rinds in sauce.", img: getSafeImage("antojitos", 11), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Gorditas de Maíz", price: "10.50", desc: "Corn gorditas filled with simple and fresh toppings.", img: getSafeImage("antojitos", 12), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Gorditas de Nata", price: "9.00", desc: "Sweet, soft cornmeal flatbreads cooked on a griddle.", img: getSafeImage("antojitos", 13), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Sopes", price: "10.00", desc: "Thick corn tortillas with pinched edges, topped with beans and garnishes.", img: getSafeImage("antojitos", 14), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Huaraches", price: "12.00", desc: "Sandal-shaped masa dough stuffed with beans, topped with cheese, salsa, and meat.", img: getSafeImage("antojitos", 15), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Tlacoyos", price: "11.50", desc: "Elongated, oval pre-Hispanic dish stuffed with cheese or beans.", img: getSafeImage("antojitos", 16), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Tlacoyos de Frijol", price: "11.00", desc: "Oval breads stuffed with black bean paste.", img: getSafeImage("antojitos", 17), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Tlacoyos de Requesón", price: "11.00", desc: "Tlacoyos filled with fresh, crumbly ricotta-style cheese.", img: getSafeImage("antojitos", 18), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Tlacoyos de Chicharrón", price: "12.00", desc: "Tlacoyos loaded with crispy Mexican pork rinds.", img: getSafeImage("antojitos", 19), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Tostadas", price: "9.50", desc: "Crispy baked tortilla layered with rich toppings.", img: getSafeImage("antojitos", 20), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Tostadas de Tinga", price: "11.00", desc: "Tostada topped with shredded chicken and onions in a chipotle sauce.", img: getSafeImage("antojitos", 21), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Tostadas de Ceviche", price: "14.00", desc: "Tostada crowned with perfectly refreshing fresh fish ceviche.", img: getSafeImage("antojitos", 22), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Tostadas de Pollo", price: "10.50", desc: "Tostada topped with shredded chicken and Mexican crema.", img: getSafeImage("antojitos", 23), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Chalupas", price: "11.00", desc: "Small boat-shaped fried corn tortillas topped with meat and salsa.", img: getSafeImage("antojitos", 24), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Memelas", price: "10.00", desc: "Oaxacan specialty of thick corn dough smeared with lard and cheese.", img: getSafeImage("antojitos", 25), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Picaditas", price: "10.50", desc: "Similar to sopes, but with finely chopped peppers and cheese, topped with crema.", img: getSafeImage("antojitos", 26), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Salbutes", price: "12.00", desc: "Yucatan specialty of soft, puffy fried corn dough topped with chicken.", img: getSafeImage("antojitos", 27), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Panuchos", price: "12.50", desc: "Fried corn tortillas stuffed with black beans and topped with meat.", img: getSafeImage("antojitos", 28), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Pambazos", price: "14.00", desc: "Mexican sandwich with bread dipped in red guajillo sauce and fried.", img: getSafeImage("antojitos", 29), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Cemitas", price: "15.00", desc: "Puebla-style sandwich on a sesame seed bun, loaded with breaded meat and avocado.", img: getSafeImage("antojitos", 30), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Tortas", price: "13.00", desc: "The classic, thick, richly stuffed Mexican sandwich.", img: getSafeImage("antojitos", 31), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Torta Ahogada", price: "14.50", desc: "'Drowned sandwich' filled with carnitas and completely submerged in spicy tomato sauce.", img: getSafeImage("antojitos", 32), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Torta de Milanesa", price: "14.00", desc: "Huge sandwich featuring a breaded cutlet (milanesa).", img: getSafeImage("antojitos", 33), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Torta Cubana", price: "16.00", desc: "The king of sandwiches: a mix of all meats, hot dogs, cheese, eggs, and veggies.", img: getSafeImage("antojitos", 34), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Torta de Chorizo", price: "13.50", desc: "Torta filled with Mexican fried sausage.", img: getSafeImage("antojitos", 35), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Torta de Tamal", price: "12.00", desc: "The iconic 'Guajolota' sandwich – a whole cooked tamal placed inside bread.", img: getSafeImage("antojitos", 36), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Elote", price: "6.00", desc: "Boiled Mexican corn on the cob smothered in mayonnaise, cheese, lime, and chili.", img: getSafeImage("antojitos", 37), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Esquites", price: "7.00", desc: "Corn off the cob served in a cup with the same delicious toppings as elote.", img: getSafeImage("antojitos", 38), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Nachos", price: "12.00", desc: "Warm crispy chips topped with melted cheese, jalapeños, and garnishes.", img: getSafeImage("antojitos", 39), isSignature: false },
    { category: "Antojitos (Street Food)", name: "Totopos", price: "5.00", desc: "Homemade, crispy, and thick Mexican tortilla chips.", img: getSafeImage("antojitos", 40), isSignature: false },

    // --- ENCHILADAS ---
    { category: "Enchiladas", name: "Enchiladas Rojas", price: "16.00", desc: "Tortillas stuffed with meat and drenched in a traditional red chili sauce.", img: getSafeImage("enchiladas", 1), isSignature: true },
    { category: "Enchiladas", name: "Enchiladas Verdes", price: "16.00", desc: "Enchiladas bathed in a tangy and fresh green tomatillo sauce.", img: getSafeImage("enchiladas", 2), isSignature: false },
    { category: "Enchiladas", name: "Enchiladas Suizas", price: "17.50", desc: "Creamy and rich chicken enchiladas, topped with abundant cheese and crema.", img: getSafeImage("enchiladas", 3), isSignature: true },
    { category: "Enchiladas", name: "Enchiladas de Mole", price: "18.00", desc: "Mighty enchiladas topped with thick, dark mole poblano sauce made from cacao.", img: getSafeImage("enchiladas", 4), isSignature: true },
    { category: "Enchiladas", name: "Enfrijoladas", price: "14.00", desc: "Enchiladas smothered in a rich black bean puree and sauce.", img: getSafeImage("enchiladas", 5), isSignature: false },
    { category: "Enchiladas", name: "Entomatadas", price: "14.50", desc: "Similar to enchiladas but mild, topped with a cooked tomato sauce without the heat.", img: getSafeImage("enchiladas", 6), isSignature: false },
    { category: "Enchiladas", name: "Enchiladas Potosinas", price: "16.50", desc: "Enchiladas made from chili-infused dough, then stuffed with cheese (San Luis Potosí style).", img: getSafeImage("enchiladas", 7), isSignature: false },
    { category: "Enchiladas", name: "Enchiladas Mineras", price: "17.00", desc: "Miner's enchiladas from Guanajuato topped with potatoes and carrots.", img: getSafeImage("enchiladas", 8), isSignature: false },
    { category: "Enchiladas", name: "Enchiladas Michoacanas", price: "16.50", desc: "Authentic enchiladas topped with spicy red sauce, potatoes, and vegetables.", img: getSafeImage("enchiladas", 9), isSignature: false },
    { category: "Enchiladas", name: "Enchiladas Queretanas", price: "17.00", desc: "Classic Querétaro enchiladas with a generous portion of chicken and cheese.", img: getSafeImage("enchiladas", 10), isSignature: false },
    { category: "Enchiladas", name: "Enchiladas Zacatecanas", price: "17.50", desc: "Zacatecas style enchiladas covered in a rich poblano cream sauce.", img: getSafeImage("enchiladas", 11), isSignature: false },

    // --- TAMALES ---
    { category: "Tamales", name: "Tamales", price: "8.00", desc: "Corn dough wrapped and steamed in a corn husk, filled with meat or beans.", img: getSafeImage("mains", 1), isSignature: false },
    { category: "Tamales", name: "Tamales Rojos", price: "8.50", desc: "Tamales filled with pork in a red chili sauce.", img: getSafeImage("mains", 2), isSignature: false },
    { category: "Tamales", name: "Tamales Verdes", price: "8.50", desc: "Tamales with chicken in a tangy green tomatillo sauce.", img: getSafeImage("mains", 3), isSignature: true },
    { category: "Tamales", name: "Tamales de Mole", price: "9.00", desc: "Chicken in mole sauce hidden inside corn dough.", img: getSafeImage("mains", 4), isSignature: false },
    { category: "Tamales", name: "Tamales Oaxaqueños", price: "10.00", desc: "A special type of tamales steamed in a banana leaf, usually filled with mole.", img: getSafeImage("mains", 5), isSignature: true },
    { category: "Tamales", name: "Corundas", price: "9.50", desc: "Michoacan tamales with a distinctive triangular shape.", img: getSafeImage("mains", 6), isSignature: false },
    { category: "Tamales", name: "Uchepos", price: "8.50", desc: "Sweet tamales made from soft and young sweet corn.", img: getSafeImage("mains", 7), isSignature: false },
    { category: "Tamales", name: "Tamal de Elote", price: "7.50", desc: "Traditional soft and sweet corn tamal.", img: getSafeImage("mains", 8), isSignature: false },
    { category: "Tamales", name: "Tamal de Dulce", price: "8.00", desc: "Pink-colored, distinctively sweet tamal.", img: getSafeImage("mains", 9), isSignature: false },
    { category: "Tamales", name: "Tamal de Rajas", price: "8.50", desc: "Tamal filled with roasted peppers and melting Mexican cheese.", img: getSafeImage("mains", 10), isSignature: false },
    { category: "Tamales", name: "Tamal de Pollo", price: "8.50", desc: "Classic tamal with shredded chicken.", img: getSafeImage("mains", 11), isSignature: false },
    { category: "Tamales", name: "Tamal de Cerdo", price: "8.50", desc: "Rich and fatty tamal filled with slow-cooked pork.", img: getSafeImage("mains", 12), isSignature: false },

    // --- SALSAS & GUARNICIONES (Sides) ---
    { category: "Salsas & Sides", name: "Guacamole", price: "8.00", desc: "Premium mashed avocado with cilantro, onion, lime, and jalapeños.", img: getSafeImage("salsas", 1), isSignature: true },
    { category: "Salsas & Sides", name: "Pico de Gallo", price: "5.00", desc: "Fresh salsa (Salsa Fresca) of chopped tomatoes, onions, cilantro, and lime.", img: getSafeImage("salsas", 2), isSignature: false },
    { category: "Salsas & Sides", name: "Salsa Roja", price: "4.00", desc: "Classic red crushed salsa made from roasted tomatoes and guajillo peppers.", img: getSafeImage("salsas", 3), isSignature: false },
    { category: "Salsas & Sides", name: "Salsa Verde", price: "4.50", desc: "Tangy and fresh green salsa based on tomatillos.", img: getSafeImage("salsas", 4), isSignature: true },
    { category: "Salsas & Sides", name: "Salsa Ranchera", price: "4.50", desc: "A spicy sauce perfect for Huevos Rancheros, cooked in a skillet.", img: getSafeImage("salsas", 5), isSignature: false },
    { category: "Salsas & Sides", name: "Salsa de Molcajete", price: "6.00", desc: "A robust salsa crushed on a traditional volcanic stone.", img: getSafeImage("salsas", 6), isSignature: true },
    { category: "Salsas & Sides", name: "Salsa Macha", price: "7.00", desc: "Earthy, potent Mexican 'chili in oil' salsa full of nuts, garlic, and seeds.", img: getSafeImage("salsas", 7), isSignature: true },
    { category: "Salsas & Sides", name: "Salsa Taquera", price: "4.50", desc: "A thick tomatillo salsa, a must-have with any authentic taco.", img: getSafeImage("salsas", 8), isSignature: false },
    { category: "Salsas & Sides", name: "Chile con Queso", price: "9.00", desc: "A warm dip of mixed cheese and roasted green chilies, perfect with chips.", img: getSafeImage("salsas", 9), isSignature: false },
    { category: "Salsas & Sides", name: "Queso Fundido", price: "11.00", desc: "Mexican melted cheese that bubbles and stretches in a skillet.", img: getSafeImage("salsas", 10), isSignature: true },
    { category: "Salsas & Sides", name: "Queso Fundido con Chorizo", price: "13.50", desc: "Melted cheese enriched with a generous portion of fried Mexican sausage.", img: getSafeImage("salsas", 11), isSignature: true },
    { category: "Salsas & Sides", name: "Frijoles Refritos", price: "5.50", desc: "Traditional, twice-fried creamy Mexican beans.", img: getSafeImage("salsas", 12), isSignature: false },
    { category: "Salsas & Sides", name: "Frijoles Charros", price: "6.50", desc: "'Cowboy beans', cooked with smoked bacon, chorizo, and peppers.", img: getSafeImage("salsas", 13), isSignature: true },
    { category: "Salsas & Sides", name: "Frijoles de la Olla", price: "5.00", desc: "Simple, boiled pinto or black beans in their own broth.", img: getSafeImage("salsas", 14), isSignature: false },
    { category: "Salsas & Sides", name: "Arroz Rojo", price: "4.50", desc: "Classic Mexican red rice simmered in a tomato broth.", img: getSafeImage("salsas", 15), isSignature: false },
    { category: "Salsas & Sides", name: "Arroz Verde", price: "5.00", desc: "Poblano rice with a beautiful green color and flavors of cilantro and peppers.", img: getSafeImage("salsas", 16), isSignature: false },
    { category: "Salsas & Sides", name: "Arroz a la Mexicana", price: "4.50", desc: "Traditional red rice mixed with mixed vegetables.", img: getSafeImage("salsas", 17), isSignature: false },
    { category: "Salsas & Sides", name: "Frijol con Puerco", price: "14.00", desc: "Pork meat slow-cooked with black beans and served over rice.", img: getSafeImage("salsas", 18), isSignature: false },

    // --- DESAYUNOS (Breakfast) ---
    { category: "Desayunos Tradicionales", name: "Chilaquiles Rojos", price: "14.50", desc: "Crispy corn chips simmered until tender in a rich red chili sauce, topped with eggs.", img: getSafeImage("breakfast", 1), isSignature: true },
    { category: "Desayunos Tradicionales", name: "Chilaquiles Verdes", price: "14.50", desc: "Chilaquiles flooded with tangy green sauce, crema, and cheese.", img: getSafeImage("breakfast", 2), isSignature: true },
    { category: "Desayunos Tradicionales", name: "Huevos Rancheros", price: "13.00", desc: "Fried eggs placed on tortillas and covered with spicy salsa ranchera.", img: getSafeImage("breakfast", 3), isSignature: false },
    { category: "Desayunos Tradicionales", name: "Huevos a la Mexicana", price: "12.00", desc: "Scrambled eggs fried with tomatoes, onions, and hot peppers (colors of the Mexican flag).", img: getSafeImage("breakfast", 4), isSignature: false },
    { category: "Desayunos Tradicionales", name: "Huevos Divorciados", price: "13.50", desc: "Two eggs separated by a wall of beans: one in red sauce, the other in green sauce.", img: getSafeImage("breakfast", 5), isSignature: true },
    { category: "Desayunos Tradicionales", name: "Molletes", price: "11.00", desc: "Toasted open-faced sandwiches spread with beans, cheese, and salsa.", img: getSafeImage("breakfast", 6), isSignature: false },

    // --- PLATOS FUERTES (Mains) ---
    { category: "Platos Fuertes", name: "Carne Asada", price: "24.00", desc: "Thin, juicy beef marinated in citrus and grilled to perfection (Arachera style).", img: getSafeImage("mains", 1), isSignature: true },
    { category: "Platos Fuertes", name: "Carne Adobada", price: "23.00", desc: "Meat generously marinated (adobo) in dried chili peppers and vinegar.", img: getSafeImage("mains", 2), isSignature: false },
    { category: "Platos Fuertes", name: "Carne Deshebrada", price: "22.00", desc: "Shredded juicy beef perfect for tacos and tostadas.", img: getSafeImage("mains", 3), isSignature: false },
    { category: "Platos Fuertes", name: "Carnitas", price: "23.50", desc: "Pork simmered in lard (confit) then crisped up. Origin: Michoacán.", img: getSafeImage("mains", 4), isSignature: true },
    { category: "Platos Fuertes", name: "Barbacoa", price: "26.00", desc: "Beef slow-roasted for hours underground wrapped in agave leaves.", img: getSafeImage("mains", 5), isSignature: true },
    { category: "Platos Fuertes", name: "Birria", price: "25.00", desc: "Iconic Mexican spiced meat (broth and stewed meat), a famous Jalisco specialty.", img: getSafeImage("mains", 6), isSignature: true },
    { category: "Platos Fuertes", name: "Birria de Res", price: "25.00", desc: "Rich Birria made from beef.", img: getSafeImage("mains", 7), isSignature: false },
    { category: "Platos Fuertes", name: "Birria de Chivo", price: "27.00", desc: "Authentic, original Birria made from goat meat, exceptionally flavorful.", img: getSafeImage("mains", 8), isSignature: true },
    { category: "Platos Fuertes", name: "Cochinita Pibil", price: "24.00", desc: "Yucatán-style pork marinated in achiote paste (with Seville oranges), roasted in a banana leaf.", img: getSafeImage("mains", 9), isSignature: true },
    { category: "Platos Fuertes", name: "Pollo Pibil", price: "21.00", desc: "The same powerful achiote marinade and banana leaf preparation, but with juicy chicken.", img: getSafeImage("mains", 10), isSignature: false },
    { category: "Platos Fuertes", name: "Tinga de Pollo", price: "19.00", desc: "Shredded chicken simmered to perfection in a sweet-spicy tomato and chipotle sauce.", img: getSafeImage("mains", 11), isSignature: false },
    { category: "Platos Fuertes", name: "Tinga de Res", price: "21.00", desc: "Shredded beef simmered in the signature chipotle sauce.", img: getSafeImage("mains", 12), isSignature: false },
    { category: "Platos Fuertes", name: "Chilorio", price: "23.00", desc: "Northern Mexican dish: Pork slow-cooked with pasilla chili pepper and cumin.", img: getSafeImage("mains", 13), isSignature: true },
    { category: "Platos Fuertes", name: "Discada", price: "26.00", desc: "A mix of grilled meats (beef, sausage, bacon) traditionally cooked on a plow disc.", img: getSafeImage("mains", 14), isSignature: true },
    { category: "Platos Fuertes", name: "Machaca", price: "22.00", desc: "Dried Mexican meat simmered and ready to deliver an umami explosion.", img: getSafeImage("mains", 15), isSignature: false },
    { category: "Platos Fuertes", name: "Cecina", price: "24.00", desc: "Very thinly sliced, salted, and semi-dried meat grilled over fire.", img: getSafeImage("mains", 16), isSignature: false },
    { category: "Platos Fuertes", name: "Tasajo", price: "25.00", desc: "Oaxaca specialty: Thin dried beef steak with an exquisite smoky flavor.", img: getSafeImage("mains", 17), isSignature: true },
    { category: "Platos Fuertes", name: "Chorizo Mexicano", price: "18.00", desc: "Famous fresh pork sausage full of paprika, intensely red in color.", img: getSafeImage("mains", 18), isSignature: false },
    { category: "Platos Fuertes", name: "Longaniza", price: "18.50", desc: "Mexican sausage similar to chorizo, but much longer and with a different spice profile.", img: getSafeImage("mains", 19), isSignature: false },
    { category: "Platos Fuertes", name: "Alambre", price: "22.00", desc: "Fajitas on steroids: Beef, vegetables, melted cheese, and bacon – all fried and combined.", img: getSafeImage("mains", 20), isSignature: true },
    { category: "Platos Fuertes", name: "Alambre de Res", price: "23.00", desc: "Beef Alambre, topped with melted Oaxaca cheese.", img: getSafeImage("mains", 21), isSignature: false },
    { category: "Platos Fuertes", name: "Alambre de Pollo", price: "20.00", desc: "Chicken version of Alambre, with bacon and peppers.", img: getSafeImage("mains", 22), isSignature: false },
    { category: "Platos Fuertes", name: "Mixiotes", price: "26.00", desc: "Meat slowly steamed inside a cactus film (maguey foil), giving it a magical flavor.", img: getSafeImage("mains", 23), isSignature: true },
    { category: "Platos Fuertes", name: "Cabrito", price: "32.00", desc: "Young, spring goat prepared on the grill.", img: getSafeImage("mains", 24), isSignature: true },
    { category: "Platos Fuertes", name: "Cabrito al Pastor", price: "34.00", desc: "Northern Mexican whole roasted goat stretched around an open fire.", img: getSafeImage("mains", 25), isSignature: true },

    // --- POLLO & MOLES ---
    { category: "Platos Fuertes", name: "Pollo Asado", price: "18.00", desc: "Simple half Mexican chicken, grilled with a citrus marinade.", img: getSafeImage("mains", 26), isSignature: false },
    { category: "Platos Fuertes", name: "Pollo Adobado", price: "19.00", desc: "Chicken coated in a thick layer of adobo chili marinade.", img: getSafeImage("mains", 27), isSignature: false },
    { category: "Platos Fuertes", name: "Pollo con Mole", price: "21.00", desc: "Roasted chicken covered in a thick Mexican cacao mole sauce.", img: getSafeImage("mains", 28), isSignature: true },
    { category: "Platos Fuertes", name: "Mole Poblano", price: "22.00", desc: "National dish: an incredibly complex sauce of over 20 ingredients (peppers, cacao, nuts) served over meat.", img: getSafeImage("mains", 29), isSignature: true },
    { category: "Platos Fuertes", name: "Mole Negro", price: "24.00", desc: "The King of Moles from Oaxaca: the darkest and most complex, bittersweet flavor.", img: getSafeImage("mains", 30), isSignature: true },
    { category: "Platos Fuertes", name: "Mole Rojo", price: "21.00", desc: "Red mole, spicier and primarily based on guajillo peppers.", img: getSafeImage("mains", 31), isSignature: false },
    { category: "Platos Fuertes", name: "Mole Verde", price: "21.00", desc: "Green mole made from tomatillos, green chilies, and pumpkin seeds.", img: getSafeImage("mains", 32), isSignature: false },
    { category: "Platos Fuertes", name: "Mole Coloradito", price: "22.00", desc: "Sweet red Oaxacan sauce rich in sesame and almonds.", img: getSafeImage("mains", 33), isSignature: false },
    { category: "Platos Fuertes", name: "Mole Amarillo", price: "22.00", desc: "Yellow mole, without chocolate, focusing on lighter herbs (hoja santa).", img: getSafeImage("mains", 34), isSignature: false },
    { category: "Platos Fuertes", name: "Pipian Rojo", price: "20.00", desc: "Similar to mole, but predominantly colored and flavored by pumpkin seeds and red chili.", img: getSafeImage("mains", 35), isSignature: false },
    { category: "Platos Fuertes", name: "Pipian Verde", price: "20.00", desc: "Green thick sauce made from pepitas (pumpkin seeds) poured over pork or chicken.", img: getSafeImage("mains", 36), isSignature: false },
    { category: "Platos Fuertes", name: "Arroz con Mole", price: "18.00", desc: "Mexican rice topped with rich mole sauce.", img: getSafeImage("mains", 37), isSignature: false },

    // --- CHILES & VERDURAS (Veg / Peppers) ---
    { category: "Vegetarijanski Specijaliteti", name: "Chile Colorado", price: "21.00", desc: "Western Mexican dish: beef or pork cooked for hours in a bright red chili sauce.", img: getSafeImage("mains", 38), isSignature: false },
    { category: "Vegetarijanski Specijaliteti", name: "Chile Verde", price: "21.00", desc: "Pork slow-simmered until it melts in a tomatillo and green pepper sauce.", img: getSafeImage("mains", 39), isSignature: true },
    { category: "Vegetarijanski Specijaliteti", name: "Chile Relleno", price: "18.00", desc: "Poblano pepper deseeded, stuffed with cheese (or meat), battered, and fried.", img: getSafeImage("mains", 40), isSignature: true },
    { category: "Vegetarijanski Specijaliteti", name: "Chiles en Nogada", price: "26.00", desc: "Patriotic dish (colors of Mexico): Pepper stuffed with fruit/meat topped with white walnut sauce (nogada) and red pomegranate.", img: getSafeImage("mains", 41), isSignature: true },
    { category: "Vegetarijanski Specijaliteti", name: "Rajas con Crema", price: "16.00", desc: "Roasted strips of Poblano peppers mixed with onions, Mexican crema, and sweet corn.", img: getSafeImage("mains", 42), isSignature: true },
    { category: "Vegetarijanski Specijaliteti", name: "Calabacitas a la Mexicana", price: "15.00", desc: "Mexican zucchini lightly stewed with tomatoes and corn.", img: getSafeImage("mains", 43), isSignature: false },
    { category: "Vegetarijanski Specijaliteti", name: "Nopales Asados", price: "14.00", desc: "Thornless cactus leaves, grilled and served warm with cheese.", img: getSafeImage("mains", 44), isSignature: false },
    { category: "Vegetarijanski Specijaliteti", name: "Nopales con Huevo", price: "14.50", desc: "Delicious Mexican scrambled eggs fried with cactus leaves.", img: getSafeImage("mains", 45), isSignature: false },
    { category: "Vegetarijanski Specijaliteti", name: "Nopales en Salsa", price: "15.00", desc: "Cactus simmered and combined with salsa verde.", img: getSafeImage("mains", 46), isSignature: false },
    { category: "Vegetarijanski Specijaliteti", name: "Nopales con Carne", price: "18.00", desc: "Rich stew of cactus and pork cubes.", img: getSafeImage("mains", 47), isSignature: false },
    { category: "Vegetarijanski Specijaliteti", name: "Verdolagas con Cerdo", price: "19.00", desc: "Mexican purslane stewed with pork in a delicious green tomatillo sauce.", img: getSafeImage("mains", 48), isSignature: true },
    { category: "Vegetarijanski Specijaliteti", name: "Papas con Chorizo", price: "16.00", desc: "Baked and seasoned potatoes with fiery chorizo sausage.", img: getSafeImage("mains", 49), isSignature: false },

    // --- ALBONDIGAS, BISTEC & MILANESA ---
    { category: "Platos Fuertes", name: "Picadillo Mexicano", price: "18.00", desc: "Sweet and savory Mexican hash of ground meat, raisins, almonds, and potatoes.", img: getSafeImage("mains", 50), isSignature: false },
    { category: "Platos Fuertes", name: "Albóndigas Mexicanas", price: "19.00", desc: "Mexican meatballs simmered in a thin, healing chili broth.", img: getSafeImage("mains", 51), isSignature: true },
    { category: "Platos Fuertes", name: "Albóndigas en Chipotle", price: "20.00", desc: "Meatballs submerged in a smoky and extremely flavorful thick chipotle sauce.", img: getSafeImage("mains", 52), isSignature: true },
    { category: "Platos Fuertes", name: "Bistec a la Mexicana", price: "21.00", desc: "Thin beef steak fried with strips of pepper, onion, and tomato.", img: getSafeImage("mains", 53), isSignature: false },
    { category: "Platos Fuertes", name: "Bistec Ranchero", price: "21.00", desc: "Steak bathed in a rustic ranchero chili sauce.", img: getSafeImage("mains", 54), isSignature: false },
    { category: "Platos Fuertes", name: "Bistec Encebollado", price: "21.00", desc: "Steak covered with a thick layer of sweet, caramelized, and tender onions.", img: getSafeImage("mains", 55), isSignature: false },
    { category: "Platos Fuertes", name: "Milanesa de Res", price: "22.00", desc: "Breaded and thinly fried beef cutlet.", img: getSafeImage("mains", 56), isSignature: false },
    { category: "Platos Fuertes", name: "Milanesa de Pollo", price: "19.00", desc: "Mexican-style breaded chicken cutlet.", img: getSafeImage("mains", 57), isSignature: false },
    { category: "Platos Fuertes", name: "Costillas en Salsa Verde", price: "22.50", desc: "Pork ribs stewed with cactus in green sauce (salsa verde).", img: getSafeImage("mains", 58), isSignature: true },
    { category: "Platos Fuertes", name: "Costillas Adobadas", price: "23.00", desc: "Ribs bathed in adobo chili marinade and roasted crispy.", img: getSafeImage("mains", 59), isSignature: false },
    { category: "Platos Fuertes", name: "Chuletas en Salsa", price: "21.00", desc: "Pork chops cooked until tender inside a tomatillo sauce.", img: getSafeImage("mains", 60), isSignature: false },
    { category: "Platos Fuertes", name: "Puerco en Chile Verde", price: "22.00", desc: "Mexican version of pork stew simmered in spicy-sour green vegetables.", img: getSafeImage("mains", 61), isSignature: false },
    { category: "Platos Fuertes", name: "Puerco en Chile Colorado", price: "22.00", desc: "Same as above, but immersed in a sauce of dried Mexican red peppers.", img: getSafeImage("mains", 62), isSignature: false },

    // --- SOUPS & CALDOS ---
    { category: "Sopas y Caldos", name: "Pozole Rojo", price: "18.00", desc: "National Mexican soup (pozole) with giant kernels of puffed corn (hominy) and meat in a red chili broth.", img: getSafeImage("soups", 1), isSignature: true },
    { category: "Sopas y Caldos", name: "Pozole Verde", price: "18.00", desc: "Pozole soup in a green, tomatillo broth, extremely fresh and aromatic.", img: getSafeImage("soups", 2), isSignature: true },
    { category: "Sopas y Caldos", name: "Pozole Blanco", price: "17.00", desc: "The purest and clearest version of pozole soup, which you season yourself.", img: getSafeImage("soups", 3), isSignature: false },
    { category: "Sopas y Caldos", name: "Menudo", price: "19.00", desc: "Traditional 'day after' (hangover) healing soup: tripe in a red spicy broth.", img: getSafeImage("soups", 4), isSignature: true },
    { category: "Sopas y Caldos", name: "Pancita", price: "19.00", desc: "Another name for Menudo, but the broth leans heavier towards central Mexico style.", img: getSafeImage("soups", 5), isSignature: false },
    { category: "Sopas y Caldos", name: "Caldo de Res", price: "17.00", desc: "Clear and strong beef soup packed with chunky vegetables: corn, zucchini, cabbage, yuca.", img: getSafeImage("soups", 6), isSignature: false },
    { category: "Sopas y Caldos", name: "Caldo de Pollo", price: "15.00", desc: "Classic rustic Mexican chicken soup.", img: getSafeImage("soups", 7), isSignature: false },
    { category: "Sopas y Caldos", name: "Caldo Tlalpeño", price: "16.00", desc: "Special chicken broth from Tlalpan enriched with chickpeas, avocado, cheese, and smoky chipotle pepper.", img: getSafeImage("soups", 8), isSignature: true },
    { category: "Sopas y Caldos", name: "Sopa de Tortilla", price: "14.00", desc: "Creamy and spicy tomato soup with submerged crispy tortilla pieces.", img: getSafeImage("soups", 9), isSignature: true },
    { category: "Sopas y Caldos", name: "Sopa Azteca", price: "14.50", desc: "Traditional, older name for an enriched Sopa de Tortilla variation with crema and avocado.", img: getSafeImage("soups", 10), isSignature: false },
    { category: "Sopas y Caldos", name: "Sopa de Lima", price: "15.00", desc: "Mystical chicken soup from the Yucatán island filled with refreshing local limes.", img: getSafeImage("soups", 11), isSignature: true },
    { category: "Sopas y Caldos", name: "Sopa de Fideo", price: "12.00", desc: "Soup based on thin fried noodles, then simmered in a clear tomato broth.", img: getSafeImage("soups", 12), isSignature: false },
    { category: "Sopas y Caldos", name: "Sopa de Frijol", price: "13.00", desc: "Thick and filling, heavier black bean soup garnished with tortillas and cheese.", img: getSafeImage("soups", 13), isSignature: false },
    { category: "Sopas y Caldos", name: "Sopa de Elote", price: "14.00", desc: "Sweet and savory velvety cream soup of sweet corn with poblano pepper.", img: getSafeImage("soups", 14), isSignature: false },
    { category: "Sopas y Caldos", name: "Sopa de Mariscos", price: "24.00", desc: "Captivating Mexican soup packed with all the gifts of the sea, reddish from a sea of hot peppers.", img: getSafeImage("soups", 15), isSignature: true },
    { category: "Sopas y Caldos", name: "Caldo de Camarón", price: "21.00", desc: "Shrimp soup with a powerful flavor from the shrimp shell broth (often carrots and potatoes are added).", img: getSafeImage("soups", 16), isSignature: false },
    { category: "Sopas y Caldos", name: "Caldo de Pescado", price: "19.00", desc: "Light, transparent white fish soup, always served with a mandatory squeeze of lime.", img: getSafeImage("soups", 17), isSignature: false },
    { category: "Sopas y Caldos", name: "Caldo de Siete Mares", price: "28.00", desc: "'Seven Seas Soup' - an epic Mexican maritime dish overflowing with seven different types of seafood.", img: getSafeImage("soups", 18), isSignature: true },
    { category: "Sopas y Caldos", name: "Birria en Consomé", price: "20.00", desc: "A special cup or bowl full of strong Birria broth, rich in meat and fat.", img: getSafeImage("soups", 19), isSignature: true },
    { category: "Sopas y Caldos", name: "Consomé de Barbacoa", price: "19.00", desc: "Broth from the barbacoa roast - an extremely potent throat clearer with chickpeas.", img: getSafeImage("soups", 20), isSignature: false },

    // --- MARISCOS (Seafood) ---
    { category: "Mariscos", name: "Aguachile", price: "24.00", desc: "'Fire in water' (Aguachile). Raw seafood marinated and cooked in the acidity of lime juice and a fiery hit of fresh chilies.", img: getSafeImage("seafood", 1), isSignature: true },
    { category: "Mariscos", name: "Aguachile Verde", price: "24.00", desc: "The green and classic version of Aguachile packed with green jalapeños/serranos.", img: getSafeImage("seafood", 2), isSignature: false },
    { category: "Mariscos", name: "Aguachile Rojo", price: "24.50", desc: "Blood-red variant of aguachile loaded with chiltepin hot peppers.", img: getSafeImage("seafood", 3), isSignature: true },
    { category: "Mariscos", name: "Ceviche Mexicano", price: "22.00", desc: "Classic refreshing Ceviche topped with plenty of Mexican salsa and avocado.", img: getSafeImage("seafood", 4), isSignature: false },
    { category: "Mariscos", name: "Ceviche de Camarón", price: "23.00", desc: "Ceviche predominantly made of lime-'cooked' shrimp.", img: getSafeImage("seafood", 5), isSignature: false },
    { category: "Mariscos", name: "Ceviche de Pescado", price: "22.00", desc: "Fresh, finely diced white fish soaked in juices with the addition of cilantro.", img: getSafeImage("seafood", 6), isSignature: false },
    { category: "Mariscos", name: "Cóctel de Camarón", price: "20.00", desc: "Mexican shrimp cocktail, mandatorily immersed in a special cold ketchup and avocado salsa 'soup'.", img: getSafeImage("seafood", 7), isSignature: true },
    { category: "Mariscos", name: "Cóctel de Pulpo", price: "23.00", desc: "Cold cocktail full of large and tasty, pre-boiled pieces of octopus.", img: getSafeImage("seafood", 8), isSignature: false },
    { category: "Mariscos", name: "Camarones a la Diabla", price: "26.00", desc: "'Devil shrimp', plunged into a fiery red sauce that is both powerful and unforgettable.", img: getSafeImage("seafood", 9), isSignature: true },
    { category: "Mariscos", name: "Camarones al Mojo de Ajo", price: "25.00", desc: "Aromatic shrimp in a melted butter sauce overwhelmed with garlic and lime.", img: getSafeImage("seafood", 10), isSignature: true },
    { category: "Mariscos", name: "Camarones Rancheros", price: "24.00", desc: "Stewed shrimp mixed in a rustic ranchero salsa with peppers and onions.", img: getSafeImage("seafood", 11), isSignature: false },
    { category: "Mariscos", name: "Camarones a la Mexicana", price: "24.00", desc: "Shrimp stewed in rainbow colors with tomato (red), onion (white), and jalapeño (green).", img: getSafeImage("seafood", 12), isSignature: false },
    { category: "Mariscos", name: "Pescado a la Veracruzana", price: "27.00", desc: "Mexican dish immersed in Spanish influence - a whole fish cooked in a sauce of olives, capers, and mild tomatoes.", img: getSafeImage("seafood", 13), isSignature: true },
    { category: "Mariscos", name: "Pescado Zarandeado", price: "32.00", desc: "Pacific classic - a whole split fish trapped in grates and smoked over a mangrove wood fire.", img: getSafeImage("seafood", 14), isSignature: true },
    { category: "Mariscos", name: "Huachinango a la Veracruzana", price: "35.00", desc: "Premium Pescado Veracruzana made exclusively and authentically from 'Red Snapper' sea fish.", img: getSafeImage("seafood", 15), isSignature: true },
    { category: "Mariscos", name: "Filete de Pescado Empanizado", price: "20.00", desc: "Simple and perfect Mexican breaded fish fillets with mayo-salsa.", img: getSafeImage("seafood", 16), isSignature: false },
    { category: "Mariscos", name: "Pulpo a las Brasas", price: "30.00", desc: "The most powerful octopus, lightly and gently boiled then moved to a direct grill (embers) for a crispy and blackened coating.", img: getSafeImage("seafood", 17), isSignature: true },
    { category: "Mariscos", name: "Empanadas de Camarón", price: "18.00", desc: "Mexican turnovers, sealed and breaded, filled with a shrimp mixture.", img: getSafeImage("seafood", 18), isSignature: false },
    { category: "Mariscos", name: "Empanadas de Queso", price: "14.00", desc: "Fried empanadas filled with flowing oaxaca cheese.", img: getSafeImage("seafood", 19), isSignature: false },
    { category: "Mariscos", name: "Empanadas de Carne", price: "16.00", desc: "Classic empanadas (Spanish-Mexican origin) with a crispy shell and ground meat filling.", img: getSafeImage("seafood", 20), isSignature: false },
    { category: "Mariscos", name: "Arroz con Mariscos", price: "28.00", desc: "Mexican version of paella, overloaded with seafood smothered in yellowish-reddish rice.", img: getSafeImage("seafood", 21), isSignature: true },
    { category: "Mariscos", name: "Molcajete de Mariscos", price: "36.00", desc: "A hot volcanic crater filled with a boiling salsa mass full of seafood.", img: getSafeImage("seafood", 22), isSignature: true },
    { category: "Mariscos", name: "Molcajete Mixto", price: "35.00", desc: "Volcanic bowl (Molcajete) filled with pieces of chicken, shrimp, and grilled asada.", img: getSafeImage("seafood", 23), isSignature: true },
    { category: "Mariscos", name: "Molcajete de Carne", price: "34.00", desc: "Hot stone overflowing with smoky Mexican chorizo, melted thick cheese, and cactus leaf.", img: getSafeImage("seafood", 24), isSignature: true },

    // --- FAJITAS, FLAUTAS, QUESADILLAS ---
    { category: "Platos Fuertes", name: "Fajitas de Res", price: "24.00", desc: "Sizzling slices of roasted beef fried over peppers in an ultra-hot skillet.", img: getSafeImage("mains", 63), isSignature: true },
    { category: "Platos Fuertes", name: "Fajitas de Pollo", price: "21.00", desc: "Sizzling chicken with onions roasted in Tex-Mex spirit for DIY tortilla wrapping.", img: getSafeImage("mains", 64), isSignature: false },
    { category: "Platos Fuertes", name: "Fajitas Mixtas", price: "26.00", desc: "Beef, chicken, and shrimp – all smoking together on hot cast iron.", img: getSafeImage("mains", 65), isSignature: true },
    { category: "Platos Fuertes", name: "Flautas de Pollo", price: "18.00", desc: "'Flutes' – tightly rolled double chicken tacos deep-fried in oil for extra crunch.", img: getSafeImage("mains", 66), isSignature: true },
    { category: "Platos Fuertes", name: "Flautas de Res", price: "19.00", desc: "Pre-crisped battered beef fritters submerged under a mass of green lettuce and crema.", img: getSafeImage("mains", 67), isSignature: false },
    { category: "Platos Fuertes", name: "Flautas de Papa", price: "17.00", desc: "Flutes generously filled with mildly spicy mashed potatoes.", img: getSafeImage("mains", 68), isSignature: false },
    { category: "Platos Fuertes", name: "Taquitos Dorados", price: "16.00", desc: "Small 'Golden Tacos' with incredible crumbly crunchiness under an avalanche of avocado and crema.", img: getSafeImage("mains", 69), isSignature: true },
    { category: "Vegetarijanski Specijaliteti", name: "Quesadillas de Flor de Calabaza", price: "18.00", desc: "Quesadilla hiding a squash blossom – the most prized, delicate delicacy of the Mexican people.", img: getSafeImage("mains", 70), isSignature: true },
    { category: "Vegetarijanski Specijaliteti", name: "Quesadillas de Huitlacoche", price: "22.00", desc: "Quesadilla filled with black treasure (huitlacoche), also known as Mexican truffle, for perfect umami.", img: getSafeImage("mains", 71), isSignature: true },
    { category: "Vegetarijanski Specijaliteti", name: "Quesadillas de Chicharrón", price: "17.00", desc: "Non-vegetarian quesadilla bomb rich in cooked pork rinds.", img: getSafeImage("mains", 72), isSignature: false },
    { category: "Vegetarijanski Specijaliteti", name: "Quesadillas de Hongos", price: "16.00", desc: "The taste of mushrooms united and melted with hot yellow cheese in a tortilla.", img: getSafeImage("mains", 73), isSignature: false },
    { category: "Vegetarijanski Specijaliteti", name: "Huitlacoche", price: "24.00", desc: "A pure portion of authentic 'corn smut', delivering an exquisite truffle-like flavor.", img: getSafeImage("mains", 74), isSignature: true },
    { category: "Vegetarijanski Specijaliteti", name: "Flor de Calabaza", price: "19.00", desc: "Pure stewed squash blossom with an aroma that evokes the ancestral land.", img: getSafeImage("mains", 75), isSignature: false },
    { category: "Platos Fuertes", name: "Chicharrón en Salsa Verde", price: "18.00", desc: "Large pork rinds overwhelmed by green tomatillo sauce until they soften into a spongy texture.", img: getSafeImage("mains", 76), isSignature: true },
    { category: "Platos Fuertes", name: "Chicharrón en Salsa Roja", price: "18.00", desc: "Similar softened spongy pork rinds submerged in a red spicy tomato-chili sauce.", img: getSafeImage("mains", 77), isSignature: false },
    { category: "Platos Fuertes", name: "Chicharrón Prensado", price: "19.00", desc: "Cubed and solid pressed pork skin scraps of incredible strength – perfect as a filling.", img: getSafeImage("mains", 78), isSignature: true },

    // --- SALADS & MORE SIDES ---
    { category: "Salsas & Sides", name: "Ensalada de Nopales", price: "12.00", desc: "Refreshing and mucilaginous salad of medicinal boiled cactus leaves with tomatoes and onions.", img: getSafeImage("salsas", 19), isSignature: true },
    { category: "Salsas & Sides", name: "Ensalada Mexicana", price: "10.00", desc: "Simple local street salad dominated by black, green, and red (white color from tangy chopped cheese).", img: getSafeImage("salsas", 20), isSignature: false },
    { category: "Salsas & Sides", name: "Escabeche de Verduras", price: "8.00", desc: "Fiery spicy and sour vegetables preserved in vinegar from a jar, eaten before main meals.", img: getSafeImage("salsas", 21), isSignature: false },
    { category: "Salsas & Sides", name: "Cactus Salad", price: "13.00", desc: "A variant of a cactus (nopal) base served on radish leaves with lime.", img: getSafeImage("salsas", 22), isSignature: false },
    { category: "Salsas & Sides", name: "Chiles Toreados", price: "6.00", desc: "For true fanatics – whole jalapeño or serrano peppers fried to the point of blackening, extremely and painfully spicy.", img: getSafeImage("salsas", 23), isSignature: true },
    { category: "Salsas & Sides", name: "Jalapeños en Escabeche", price: "7.00", desc: "Sour Mexican pickled jalapeños with carrots.", img: getSafeImage("salsas", 24), isSignature: false },
    { category: "Salsas & Sides", name: "Tortillas de Maíz", price: "4.00", desc: "The core and pillar of Mexican civilization – warm hills of traditional freshly ground corn tortillas.", img: getSafeImage("salsas", 25), isSignature: true },
    { category: "Salsas & Sides", name: "Tortillas de Harina", price: "4.00", desc: "Soft and stretchy flour tortillas imported through Northern and Tex-Mex influence.", img: getSafeImage("salsas", 26), isSignature: false },

    // --- REGIONAL SPECIALTIES ---
    { category: "Platos Fuertes", name: "Tlayudas", price: "24.00", desc: "The absolute Oaxacan giant: a pizza-shaped massive grilled corn tortilla thickly covered with pork lard spread, beans, and Oaxaca cheese, sprinkled with all kinds of meat.", img: getSafeImage("mains", 79), isSignature: true },
    { category: "Platos Fuertes", name: "Tlayuda Oaxaqueña", price: "26.00", desc: "Traditional original and huge Oaxacan beast-tlayuda on the grill.", img: getSafeImage("mains", 80), isSignature: true },
    { category: "Platos Fuertes", name: "Garnachas", price: "14.00", desc: "Puffy small fried corn dish topped with sauce and meat (Yucatan specialty).", img: getSafeImage("mains", 81), isSignature: false },
    { category: "Platos Fuertes", name: "Empalmes", price: "16.00", desc: "Monterey Northern double-handed fried sandwich created by putting together two tortillas with spicy mashed beans inside.", img: getSafeImage("mains", 82), isSignature: false },
    { category: "Platos Fuertes", name: "Papadzules", price: "18.00", desc: "Mayan masterpiece: Rolled corn tortillas with small hard-boiled eggs under a moist layer of pumpkin seed sauce.", img: getSafeImage("mains", 83), isSignature: true },
    { category: "Platos Fuertes", name: "Poc Chuc", price: "24.00", desc: "Exquisite, sour Yucatecan pork swimming in Seville-sour orange and fried until it cracks.", img: getSafeImage("mains", 84), isSignature: true },
    { category: "Platos Fuertes", name: "Relleno Negro", price: "26.00", desc: "A unique, almost black turkey soup from Yucatan darkened with burnt, completely incinerated chilies down to the blackness of ash.", img: getSafeImage("mains", 85), isSignature: true },
    { category: "Platos Fuertes", name: "Queso Relleno", price: "28.00", desc: "Absurd Yucatán genius: a whole hollowed Dutch Edam cheese stuffed with meat in the middle, slowly boiled.", img: getSafeImage("mains", 86), isSignature: true },
    { category: "Sopas y Caldos", name: "Sopa de Lima Yucateca", price: "16.00", desc: "Classic citrusy and crispy Yucatan soup with lime.", img: getSafeImage("soups", 21), isSignature: false },
    { category: "Platos Fuertes", name: "Pan de Cazón", price: "24.00", desc: "Coastal Mexican lasagna: a stack of tortillas and sauce layered with small boiled shark. Campeche specialty.", img: getSafeImage("mains", 87), isSignature: true },
    { category: "Postres Dulces", name: "Marquesitas", price: "10.00", desc: "Sweet and crispy pancake from Yucatan rolled like a cone, stuffed with hard Dutch Edam cheese with the addition of sweet hazelnut or nutella.", img: getSafeImage("desserts", 22), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Kibis Yucatecos", price: "12.00", desc: "Lebanese-Mexican intersection: Yucatecan version of kibbeh balls of fried ground meat and bulgur stuffed with jalapeños.", img: getSafeImage("antojitos", 41), isSignature: true },
    { category: "Antojitos (Street Food)", name: "Pescadillas", price: "14.00", desc: "Fish quesadillas from the southern Mexican coasts deep-fried in oil to perfect crunchiness.", img: getSafeImage("antojitos", 42), isSignature: false },
    { category: "Salsas & Sides", name: "Chileatole", price: "9.00", desc: "Salty, hot topping combining spicy masa (dough) pepper and epazote.", img: getSafeImage("salsas", 27), isSignature: false },
    { category: "Postres Dulces", name: "Atole de Elote", price: "8.00", desc: "Deliciously sweet satisfying thick hot creamy drink-soup of ground pure corn.", img: getSafeImage("desserts", 23), isSignature: false },
    { category: "Platos Fuertes", name: "Pastel Azteca", price: "22.00", desc: "'Mexican Lasagna' - an overly rich casserole of Mexican ingredients (corn tortillas, poblanos and cheese, and lots of chicken/meat).", img: getSafeImage("mains", 88), isSignature: true },
    { category: "Platos Fuertes", name: "Budín de Tortilla", price: "20.00", desc: "Almost similar to Pastel Azteca but more often soaked in mole forming a mighty baked bread-pudding of corn tortillas.", img: getSafeImage("mains", 89), isSignature: false },
    { category: "Platos Fuertes", name: "Pescado Tikin Xic", price: "32.00", desc: "Mayan coastal throne – Fish split open, painted with achiote powder, fueled by orange and wrapped in palm or banana leaves and roasted over wood.", img: getSafeImage("mains", 90), isSignature: true },
    { category: "Platos Fuertes", name: "Pollo en Escabeche", price: "24.00", desc: "Clear but incredibly strong Yucatan sour-dried salted and peppered lightly beaten boiled hen.", img: getSafeImage("mains", 91), isSignature: false },
    { category: "Vegetarijanski Specijaliteti", name: "Quelites", price: "14.00", desc: "One of the oldest American dishes – mild herbs (wild greens) lightly stewed in rustic pork lard and chili.", img: getSafeImage("mains", 92), isSignature: true },
    { category: "Vegetarijanski Specijaliteti", name: "Romeritos", price: "18.00", desc: "National winter passion during the holidays (Posadas) – mild fried rosemary-like shoots stewed deep in mole sauce.", img: getSafeImage("mains", 93), isSignature: true },
    { category: "Vegetarijanski Specijaliteti", name: "Romeritos con Mole", price: "21.00", desc: "Premium holiday edition – fasting Romeritos folded with the best Mexican fried dried shrimp.", img: getSafeImage("mains", 94), isSignature: true },
    { category: "Mariscos", name: "Bacalao a la Mexicana", price: "28.00", desc: "Traditional dried Mexican/European cod soaked for days then cooked with tomatoes, olives, and Vizcaina influence for Christmas.", img: getSafeImage("seafood", 25), isSignature: true },
    { category: "Vegetarijanski Specijaliteti", name: "Huauzontles", price: "22.00", desc: "For pre-Cortez spirits - thick stalks of ancient amaranth dipped in a fatty and moist cheese-egg batter and lightly baked.", img: getSafeImage("mains", 95), isSignature: true },
    { category: "Mariscos", name: "Tortitas de Camarón", price: "18.00", desc: "Mexican coastal minced cutlets prepared on an incredible ground and crushed mixture of smoked dried shrimp.", img: getSafeImage("seafood", 26), isSignature: false },
    { category: "Vegetarijanski Specijaliteti", name: "Tortitas de Papa", price: "14.00", desc: "Mexican round street patties rich in mashed potatoes simmered to a crunchy crust inside.", img: getSafeImage("mains", 96), isSignature: false },
    { category: "Vegetarijanski Specijaliteti", name: "Tortitas de Elote", price: "15.00", desc: "Small round fluffy medallions mixed with eggs and roasted Mexican sweet corn.", img: getSafeImage("mains", 97), isSignature: false },
    { category: "Platos Fuertes", name: "Tortitas de Carne", price: "16.00", desc: "Broadly formed crispy beef fritters rolled out, breaded before frying in the oven.", img: getSafeImage("mains", 98), isSignature: false },

    // --- DESSERTS (Postres) ---
    { category: "Postres Dulces", name: "Dulce de Leche", price: "9.00", desc: "Thick sweet of incredible caramel tone from prolonged boiling of condensed and sweet cow's milk.", img: getSafeImage("desserts", 24), isSignature: false },
    { category: "Postres Dulces", name: "Cajeta", price: "11.00", desc: "The main difference from Dulce de Leche, the original Mexican Cajeta gets a rich lightly-roasted caramel flavor exclusively by long heating of precious goat's milk.", img: getSafeImage("desserts", 25), isSignature: true },
    { category: "Postres Dulces", name: "Flan Napolitano", price: "12.00", desc: "Creamy and velvety topping under a shiny toasted honey/caramel top. An icon of every Sunday lunch.", img: getSafeImage("desserts", 26), isSignature: true },
    { category: "Postres Dulces", name: "Arroz con Leche", price: "8.00", desc: "Pudding/Mexican rice pudding stuffed with thick long-boiled rice on fiery and abundant cinnamon.", img: getSafeImage("desserts", 27), isSignature: false },
    { category: "Postres Dulces", name: "Pastel de Tres Leches", price: "14.00", desc: "Magnificent, spongy airy biscuit sponge cake soaked to destruction with 3 levels of milk (evaporated, condensed, and heavy fatty liquid sweet milk).", img: getSafeImage("desserts", 28), isSignature: true },
    { category: "Postres Dulces", name: "Chocoflan", price: "15.00", desc: "Mexican and so-called 'No Way/Impossible' cake that bakes chocolate on the bottom and a shiny Flan on top, swapping places under temperature.", img: getSafeImage("desserts", 29), isSignature: true },
    { category: "Postres Dulces", name: "Jericalla", price: "10.00", desc: "A relative of Flan born and bred exclusively in Guadalajara with an extreme note of vanilla and overheated to a bitter burnt black bottom and edge.", img: getSafeImage("desserts", 30), isSignature: true },
    { category: "Postres Dulces", name: "Capirotada", price: "11.00", desc: "Easter and holiday Mexican bread pudding that combines salty, strongly pickled with sugar cane - inside you will find tomatoes, nuts, and piloncillo.", img: getSafeImage("desserts", 31), isSignature: true },
    { category: "Postres Dulces", name: "Buñuelos Mexicanos", price: "8.00", desc: "Thin and raw disc-crust deeply dipped in a hot fryer and drenched in an abundance of various crumbs and sugar.", img: getSafeImage("desserts", 32), isSignature: false },
    { category: "Postres Dulces", name: "Churros", price: "7.00", desc: "Extremely stretchy sweet cane deep-fried usually coated with pure brown and very hot cinnamon sugar flavor.", img: getSafeImage("desserts", 33), isSignature: true },
    { category: "Postres Dulces", name: "Pan de Muerto", price: "9.00", desc: "The most important Mexican religious funerary festive and delicious soft pastry sprinkled with lemon blossom and crossed 'bones' on top.", img: getSafeImage("desserts", 34), isSignature: true },
    { category: "Postres Dulces", name: "Rosca de Reyes", price: "12.00", desc: "Epiphany Mexican sweet ring crowned with candied green and red strips of fruit.", img: getSafeImage("desserts", 35), isSignature: false },
    { category: "Postres Dulces", name: "Conchas", price: "6.00", desc: "Favorite everyday morning 'Bimbo' pan dulce dough and Mexican bread in the shape of a seashell with a cracked sweet crust.", img: getSafeImage("desserts", 36), isSignature: true },
    { category: "Postres Dulces", name: "Orejas", price: "5.00", desc: "Mexican puff pastry 'Ears', better known in Europe as elephant ears, fried and smooth sugar dough in the shape of a heart.", img: getSafeImage("desserts", 37), isSignature: false },
    { category: "Postres Dulces", name: "Cuernitos", price: "5.50", desc: "Mexican version of the French croissant, but firmer, with more vanilla and fewer fragile airy butter layers.", img: getSafeImage("desserts", 38), isSignature: false },
    { category: "Postres Dulces", name: "Empanadas Dulces", price: "8.00", desc: "Closed soft pillows in which cooks, melts, and boils satisfying dulce de leche and pineapple marmalade.", img: getSafeImage("desserts", 39), isSignature: false },
    { category: "Postres Dulces", name: "Coyotas", price: "10.00", desc: "Northern sweet pancake filled with dark hard Mexican raw piloncillo sugar adored in Sonora.", img: getSafeImage("desserts", 40), isSignature: true },
    { category: "Postres Dulces", name: "Coricos", price: "7.00", desc: "Round corn biscuits from the Pacific region.", img: getSafeImage("desserts", 41), isSignature: false },
    { category: "Postres Dulces", name: "Garibaldis", price: "8.00", desc: "Special biscuit cakes that got a refined and soaked finish, completely sprinkled with white topping and orange dots.", img: getSafeImage("desserts", 42), isSignature: true },
    { category: "Postres Dulces", name: "Polvorones Mexicanos", price: "6.00", desc: "Very fragile dry tri-color biscuits that literally break at the slightest touch sprinkled with strong powder.", img: getSafeImage("desserts", 43), isSignature: false },
    { category: "Postres Dulces", name: "Marranitos", price: "7.00", desc: "Gingerbread cookies that mandatorily accompany a handful of ginger cut with molds of small soft pigs.", img: getSafeImage("desserts", 44), isSignature: true },
    { category: "Postres Dulces", name: "Muéganos", price: "9.00", desc: "Large coated satisfying and sweet caramel ring, drenched in Mexican toasted breads.", img: getSafeImage("desserts", 45), isSignature: false },
    { category: "Postres Dulces", name: "Alegrías", price: "5.00", desc: "Ancient Aztec sweet presses of 'Happiness', bars of amaranth seeds tightly glued with honey and nuts.", img: getSafeImage("desserts", 46), isSignature: true },
    { category: "Postres Dulces", name: "Palanquetas", price: "6.00", desc: "Strongly toasted bars/snacks of pressed hazelnut/peanut submerged in hard dark sugar.", img: getSafeImage("desserts", 47), isSignature: false },
    { category: "Postres Dulces", name: "Cocadas", price: "6.50", desc: "Sweet Mexican donuts with yellow polished baked lines created only by mixing grated white coconut milk and sugar.", img: getSafeImage("desserts", 48), isSignature: false },
    { category: "Postres Dulces", name: "Mazapán de Cacahuate", price: "4.00", desc: "Mexican, totally crumbly marzipan that, unlike the European one, predominantly holds powerful peanut powder.", img: getSafeImage("desserts", 49), isSignature: true },
    { category: "Postres Dulces", name: "Dulce de Tamarindo", price: "4.50", desc: "Balls of Mexican candy with an incredibly and uniquely sour tone.", img: getSafeImage("desserts", 50), isSignature: false },
    { category: "Postres Dulces", name: "Ate de Guayaba", price: "8.00", desc: "Thick block of Mexican gelatin from guava and quince. Most gladly paired with cuts of sea cheese.", img: getSafeImage("desserts", 51), isSignature: true },
    { category: "Postres Dulces", name: "Ate de Membrillo", price: "8.00", desc: "Firm and powerful thick red paste-treat made from pure quince.", img: getSafeImage("desserts", 52), isSignature: false },
    { category: "Postres Dulces", name: "Camotes Poblanos", price: "7.00", desc: "Sweet Puebla press and paste of sweet potato orange potato streaked and melted with the essence of pineapple and strawberry.", img: getSafeImage("desserts", 53), isSignature: true },
    { category: "Postres Dulces", name: "Glorias", price: "9.00", desc: "Exclusive sweet caramel in red cellophane foil, from Monterrey, abundant with walnuts, jam, and cow's milk.", img: getSafeImage("desserts", 54), isSignature: true },
    { category: "Postres Dulces", name: "Jamoncillo", price: "6.00", desc: "Over-rich soft bars and cubes that visually resemble two-tone nougat with various extracts.", img: getSafeImage("desserts", 55), isSignature: false },
    { category: "Postres Dulces", name: "Cajeta de Celaya", price: "12.00", desc: "The King of Cajeta, sweet wooden Mexican spoons coated with the original Celayan jam of goat's milk.", img: getSafeImage("desserts", 56), isSignature: true },
    { category: "Postres Dulces", name: "Nieves Mexicanas", price: "5.00", desc: "Simple watery fresh summer ice cream manually pressed with Mexican fruit.", img: getSafeImage("desserts", 57), isSignature: false },
    { category: "Postres Dulces", name: "Paletas Mexicanas", price: "4.50", desc: "Huge Mexican popsicle sticks of frozen fresh pieces of lime/fruit.", img: getSafeImage("desserts", 58), isSignature: false },
    { category: "Postres Dulces", name: "Raspados", price: "6.00", desc: "Fiery Mexican syrup and shaved broken and crushed rough pure city and street ice.", img: getSafeImage("desserts", 59), isSignature: false },
    { category: "Postres Dulces", name: "Mangonada", price: "8.00", desc: "Fiery-sweet ice cream of frozen yellow mango flooded with thick, sticky bright-red and sour tamarind and chamoy topping.", img: getSafeImage("desserts", 60), isSignature: true },
    { category: "Postres Dulces", name: "Chamoyada", price: "8.00", desc: "Similar to the above Mangonada only filled with watery ice wrapped in fiery and bloody sour pepper along the edges.", img: getSafeImage("desserts", 61), isSignature: true },
    { category: "Postres Dulces", name: "Fresas con Crema", price: "9.00", desc: "A bowl from which flow Mexican rich heavy creams full of thick cuts of fresh strawberries.", img: getSafeImage("desserts", 62), isSignature: false },
    { category: "Postres Dulces", name: "Plátanos Fritos", price: "7.00", desc: "Elongated tropical baked and softened bananas topped with liquid condensed yellow milk and sprinkled with a touch of cinnamon.", img: getSafeImage("desserts", 63), isSignature: true },
    { category: "Postres Dulces", name: "Elote Dulce", price: "8.00", desc: "Plate/Pudding extracted from the center of corn mixed with fatty sour buttery sauces and deep inside sweetened with cane sugar.", img: getSafeImage("desserts", 64), isSignature: false },

    // --- DRINKS (Bebidas y Aguas Frescas) ---
    { category: "Bebidas y Aguas Frescas", name: "Chocolate Mexicano", price: "9.00", desc: "Rough ground unroasted solid homemade Mexican cacao brought to life by a wooden molinillo mill for extraction, full of cinnamon and thick black foam.", img: getSafeImage("drinks", 1), isSignature: true },
    { category: "Bebidas y Aguas Frescas", name: "Café de Olla", price: "7.00", desc: "Mexican clay coffee: ground and served inside an old stone jug where raw sweet earthy piloncillo foam simmers alongside it with bark and cinnamon sticks.", img: getSafeImage("drinks", 2), isSignature: true },
    { category: "Bebidas y Aguas Frescas", name: "Atole", price: "6.00", desc: "A highly popular warm and thick liquid early-morning Mexican sweet breakfast cooked in a soup of roasted corn (masa).", img: getSafeImage("drinks", 3), isSignature: false },
    { category: "Bebidas y Aguas Frescas", name: "Champurrado", price: "8.00", desc: "Thicker, older, and stronger brother of the classic Atole - this soup-drink is intertwined with rich dark melted bars of authentic Mexican chocolate.", img: getSafeImage("drinks", 4), isSignature: true },
    { category: "Bebidas y Aguas Frescas", name: "Horchata", price: "5.00", desc: "Thick sweet drink ('water') made predominantly by pouring the purest rice generously stamped with white and powdery powerful Mexican cinnamon.", img: getSafeImage("drinks", 5), isSignature: true },
    { category: "Bebidas y Aguas Frescas", name: "Agua de Jamaica", price: "4.50", desc: "Absolute and incredibly sweet bloody and sour transparent fruit drink of dark and highly refreshing juice and Hibiscus flowers.", img: getSafeImage("drinks", 6), isSignature: true },
    { category: "Bebidas y Aguas Frescas", name: "Agua de Tamarindo", price: "4.50", desc: "Darker, thick street transparent water, a murky powerful liquid squeezed from ripe tamarind - with a strong and healing acidity.", img: getSafeImage("drinks", 7), isSignature: false },
    { category: "Bebidas y Aguas Frescas", name: "Agua de Limón", price: "4.00", desc: "Agua Fresca colored and made by squeezing characteristically small round sour ripe tiny green Mexican limes with seeds whose oil from the peel bursts with refreshing bitterness, served with large chunks of raw street ice.", img: getSafeImage("drinks", 8), isSignature: false },
    { category: "Bebidas y Aguas Frescas", name: "Agua de Sandía", price: "5.00", desc: "Light Agua Fresca made by blending the heart of a juicy and fresh red watermelon, sweetened with cane sugar.", img: getSafeImage("drinks", 9), isSignature: false },
    { category: "Bebidas y Aguas Frescas", name: "Agua de Melón", price: "5.00", desc: "Another variant of refreshing summer Agua Fresca water overflowing with the liquid pureed flesh of sweet and sticky domestic melon.", img: getSafeImage("drinks", 10), isSignature: false },
    { category: "Bebidas y Aguas Frescas", name: "Agua de Piña", price: "4.50", desc: "Clear and tartly fresh pineapple water made without any industrial additives, highly refreshing.", img: getSafeImage("drinks", 11), isSignature: false },
    { category: "Bebidas y Aguas Frescas", name: "Agua de Pepino", price: "4.50", desc: "Cross-sour street, ice-green, and powerfully hydrating mixture of ground sea cucumbers, often accompanied by mild cuts of limes for added depth and balance in warm and stifling summer Mexican nights and tropical mornings.", img: getSafeImage("drinks", 12), isSignature: false },
    { category: "Bebidas y Aguas Frescas", name: "Agua de Chía", price: "5.00", desc: "Omnipresent pre-Hispanic exquisite mixture and purifying transparent lime liquid filled to the brim with small chia seeds - packed with health.", img: getSafeImage("drinks", 13), isSignature: true },
    { category: "Bebidas y Aguas Frescas", name: "Tepache", price: "7.00", desc: "Fiery street orange and mild and subtly low-alcoholic fermented sweet juice, simmered from rotten, cut, and submerged whole Mexican uncleaned and peeled ripe pineapple and brown hardened round sugar.", img: getSafeImage("drinks", 14), isSignature: true },
    { category: "Bebidas y Aguas Frescas", name: "Tascalate", price: "8.00", desc: "Orange and beautiful indigenous ancient drink from the Chiapas region born by mixing crushed cacao beans and crushed old corn in a transparent cold base.", img: getSafeImage("drinks", 15), isSignature: true },
    { category: "Bebidas y Aguas Frescas", name: "Tejate", price: "9.00", desc: "The pride of the city of Oaxaca - thick white foam covers an overly rich soup of drink uniting street masters of crushing cacao seeds, flowers, and corn, creating a magical drink called the sparkling 'milk of the gods' with exceptional visual tones.", img: getSafeImage("drinks", 16), isSignature: true }
  ]
};
// KRAJ FAJLA: src/DemoData/mexicanMassiveData.js