// POČETAK FAJLA: V8PromptData.js

export const vaultIdeas = [
  "", // 0 - Prazno polje za placeholder

  // ==========================================
  // 🟢 STARTER TIER IDEAS (1 - 50)
  // Premium teksture, makro detalji i čista estetika
  // ==========================================
  "Macro photography of frozen liquid nitrogen expanding over dark volcanic basalt rock",
  "Close-up of interlocking geometric gold gears in a flawless, unbranded mechanical timepiece",
  "An abstract flow of iridescent metallic paint swirling underwater against a pure black background",
  "A minimalist luxury podium made of raw concrete, illuminated by a single warm spotlight",
  "Extreme macro shot of a cracked diamond, internal light refracting into vivid prism colors",
  "A futuristic aerodynamic carbon-fiber surface reflecting cold blue studio lights",
  "A monolithic slab of polished obsidian standing alone in a misty, empty white desert",
  "Close-up of blooming bismuth crystals showing incredible geometric stairs and rainbow hues",
  "Slow-motion capture of a perfect spherical drop of liquid mercury falling onto brushed steel",
  "An abstract, glowing neon-cyan geometric shape floating in a completely dark room",
  "Macro texture of a luxury damascus steel blade glowing with residual heat from a forge",
  "A pristine, empty hyper-modern museum interior made entirely of white marble and glass",
  "Close-up of ferrofluid spikes reacting to a strong magnetic field under harsh rim lighting",
  "A perfect sphere of solid glass resting on a dark slate table, refracting a distant sunset",
  "Macro view of a single frozen dewdrop on a microscopic carbon-fiber thread",
  "A brutalist concrete staircase leading infinitely into a pitch-black void",
  "An abstract composition of layered, translucent acoustic foam wedges in an anechoic chamber",
  "A perfectly smooth, unbranded matte-black motorcycle helmet visor reflecting an LED light strip",
  "Macro shot of burning incense smoke creating complex, hypnotic fluid dynamics in mid-air",
  "A glowing, ethereal energy core suspended inside a sterile, dark vacuum containment unit",
  "Close up of highly polished rose-gold geometric shapes resting on a bed of dark sand",
  "A futuristic, unmarked aerodynamic drone wing slicing through thick volumetric fog",
  "Macro photography of crushed velvet fabric, extremely shallow depth of field, moody red lighting",
  "An abstract architectural facade made of undulating titanium panels reflecting the sky",
  "A glowing, perfectly symmetrical crystal floating above a pedestal in an ancient, dark temple ruin",
  "Close-up of molten glass being shaped, intense orange glow, dark workshop atmosphere",
  "A surreal landscape of perfectly smooth, giant metallic spheres resting on a mirrored salt flat",
  "Macro detail of a high-tech synthetic muscle fiber contracting under blue LED light",
  "An empty, ultra-luxury high-speed train cabin interior looking out at a dark tunnel",
  "A macro shot of a single drop of rich golden oil hitting a pool of pitch-black liquid",
  "Abstract flow of crushed dry ice evaporating into dense white fog on a dark reflective surface",
  "A brutalist architectural monument towering over a dense, dark pine forest at twilight",
  "Close-up of a flawlessly engineered titanium piston, studio lighting emphasizing metallic grain",
  "A massive, empty subterranean server farm room submerged in a shallow layer of clear water",
  "Macro texture of compressed aerodynamic mesh used in high-performance concept vehicles",
  "A surreal, glowing holographic ring floating precisely in the center of an empty desert",
  "Close-up of dark obsidian volcanic glass shattering into perfect geometric shards, frozen in time",
  "A minimalist architectural corridor illuminated only by thin, glowing white floor strips",
  "Macro photography of an intricate crystalline matrix forming inside a freezing liquid solution",
  "A futuristic, unmarked jet thruster glowing with intense blue plasma heat",
  "Abstract composition of floating white marble pillars suspended in a dark, atmospheric void",
  "Close-up of a perfectly round, glowing red ember resting on a block of compressed charcoal",
  "A pristine, empty infinity pool edge dropping off into a thick sea of white clouds",
  "Macro detail of interlocking carbon nanotubes, extreme optical sharpness, clinical lighting",
  "An abstract, smooth fluid simulation of heavy liquid gold pouring over a matte black sphere",
  "A high-tech, glowing blue fiber-optic cable cleanly severed, exposing the internal glass core",
  "A massive, unbranded acoustic isolation door in a subterranean bunker, slowly opening",
  "Close-up of a flawless cut ruby resting on a dark velvet surface, intense focused light beam",
  "An abstract architectural concept of interlocking triangular concrete blocks casting deep shadows",
  "Macro shot of a high-frequency sound wave vibrating a pool of dark, viscous liquid",

  // ==========================================
  // 🟡 PRO TIER IDEAS (51 - 150)
  // Napredno osvetljenje, arhitektura, sci-fi apstrakcije
  // ==========================================
  "A massive, unbranded concept hypercar chassis carved entirely out of solid black marble, cinematic studio lighting",
  "An extreme macro shot of a complex quantum microchip layout, intricate gold wiring glowing on a silicon wafer",
  "Abstract architecture of a spiraling tower made of glowing translucent resin, extending into a foggy night sky",
  "A perfect, unbranded matte-white robotic prosthetic arm resting on a dark surgical steel table",
  "Macro photography of microscopic rust patterns on a decommissioned spaceship hull, vivid orange and blue contrast",
  "A futuristic, empty megacity intersection lit by giant glowing neon-magenta holographic street signs",
  "Close-up of an aerodynamic, unbranded racing wheel rim, perfectly reflecting a grid of overhead LED light panels",
  "A surreal interior of a room where the floor, walls, and ceiling are all made of flawless mirror-polished black glass",
  "Macro shot of a highly complex mechanical iris opening, layered steel blades moving in perfect synchronization",
  "An unbranded, high-tech cryogenic stasis pod interior, empty and glowing with a cold, sterile white light",
  "Abstract fluid simulation of thick, glossy black oil and metallic silver paint mixing dynamically in zero gravity",
  "A massive, brutalist dam structure holding back a glowing, bioluminescent turquoise ocean at night",
  "Close-up of an ancient, alien artifact made of an unknown, shifting iridescent metal, resting on a pedestal",
  "A pristine, empty futuristic aerospace hangar with a glossy white floor reflecting dramatic geometric skylights",
  "Macro photography of a high-power laser beam precisely cutting through a thick slab of industrial tungsten",
  "A surreal landscape featuring floating, monolithic chunks of cracked concrete hovering over a glowing magma river",
  "Close-up of a high-end luxury watch dial completely stripped of branding, showing only flawless guilloché patterns",
  "An empty, ultra-luxury penthouse bathroom featuring a massive rough-hewn stone bathtub looking out at a dark cityscape",
  "Macro detail of an acoustic anechoic chamber wall, deep shadows hiding within the sound-absorbing foam spikes",
  "A futuristic, glowing blue energy shield deflecting an invisible impact, sparking with intense plasma discharge",
  "An abstract composition of hundreds of thin, glowing red fiber-optic strands suspended in a pitch-black void",
  "A massive, abandoned brutalist library interior, empty shelves, rays of dusty sunlight piercing the gloom",
  "Close-up of a perfectly engineered unbranded motorcycle exhaust pipe, showcasing rainbow titanium heat discoloration",
  "A surreal, infinite corridor of glowing white neon archways reflecting on a highly polished wet black floor",
  "Macro photography of an intricate snowflake melting precisely at the tip of a heated platinum needle",
  "An unbranded, sleek dark-matter energy reactor core spinning rapidly and emitting intense purple radiation",
  "Abstract architecture of a massive, inverted glass pyramid suspended over a dark, turbulent ocean",
  "Close-up of a thick layer of translucent aerogel insulation glowing from an intense internal heat source",
  "A pristine, empty high-tech laboratory clean-room bathed in harsh, shadowless, shadowless ultraviolet sterilization light",
  "Macro detail of a high-tension steel suspension cable snapping, individual wire strands whipping violently outward",
  "A futuristic, unmarked aerodynamic jet engine intake fan spinning at high speed, sleek metallic reflections",
  "An abstract landscape of towering, jagged crystalline structures glowing faintly against a deep starry nebula",
  "Close-up of a flawlessly smooth, unbranded luxury perfume bottle made of solid black glass catching a single rim light",
  "A massive, empty subterranean missile silo interior, moody atmospheric perspective, thick volumetric fog",
  "Macro photography of a highly reactive chemical mixture producing dynamic, expanding colorful fractal patterns",
  "A surreal, floating architectural concept of a minimalist concrete pavilion drifting above a sea of clouds",
  "Close-up of an unbranded, high-end mechanical keyboard switch, perfectly isolated on a stark white background",
  "An empty, ultra-luxury private jet cabin interior looking out at the curvature of the Earth from the stratosphere",
  "Macro detail of a complex, unbranded artificial intelligence neural network node, glowing with data transmission pulses",
  "A futuristic, glowing cyan energy grid expanding across a dark, metallic planetary surface",
  "An abstract composition of massive, polished dark-wood acoustic panels curving organically in a grand concert hall",
  "Close-up of an unbranded, aerodynamic carbon-fiber bicycle frame joint, showcasing the perfect woven texture",
  "A surreal, empty geometric room where a single, intensely bright beam of sunlight hits a perfectly square pool of water",
  "Macro photography of a high-speed projectile shattering a pane of bulletproof glass, capturing the spiderweb fracture pattern",
  "An unbranded, high-tech orbital space station docking ring, cold metallic textures, stark lighting from a distant sun",
  "Abstract fluid simulation of highly viscous liquid chrome wrapping around an invisible magnetic core",
  "A massive, brutalist concrete wind tunnel testing facility, massive fan blades resting in silence, deep perspective",
  "Close-up of an ancient, glowing magical rune carved deeply into a slab of rough volcanic rock",
  "A pristine, empty futuristic greenhouse biome on Mars, glowing pink grow-lights illuminating strange alien flora",
  "Macro detail of a high-frequency vibrating speaker cone launching microscopic dust particles into the air",
  "A futuristic, unbranded robotic exoskeleton joint, precise hydraulic cylinders and braided steel cables",
  "An abstract landscape of endless, perfectly smooth sand dunes composed entirely of crushed black glass",
  "Close-up of an unbranded, high-end camera sensor exposed to direct light, reflecting complex micro-lens arrays",
  "A massive, empty subterranean train station built inside a natural crystal cavern, glowing with internal luminescence",
  "Macro photography of a perfectly spherical drop of liquid nitrogen floating above a super-heated copper plate",
  "A surreal architectural concept of a completely transparent glass bridge spanning across two towering mountain peaks",
  "Close-up of a flawlessly engineered, unbranded aerospace-grade titanium bolt resting on technical blueprints",
  "An empty, ultra-luxury minimalist wine cellar interior, walls lined with glowing, unbranded dark glass bottles",
  "Macro detail of a complex, unbranded synthetic retina, glowing softly with artificial bioluminescence",
  "A futuristic, glowing magenta energy pulse traveling down a massive array of dark industrial power cables",
  "An abstract composition of hundreds of polished steel spheres suspended in mid-air, refracting a single light source",
  "Close-up of an unbranded, high-performance disc brake rotor glowing cherry-red from extreme friction heat",
  "A surreal, infinite array of perfectly aligned white geometric columns stretching to the horizon on a flat dark plain",
  "Macro photography of an intricate frost pattern rapidly freezing across a heated sheet of dark tempered glass",
  "An unbranded, high-tech quantum computing chandelier hanging in an empty, dark subterranean data center",
  "Abstract fluid simulation of thick, glowing neon-cyan liquid erupting from a fractured obsidian surface",
  "A massive, brutalist concrete dam spillway releasing a torrent of perfectly smooth, glassy water",
  "Close-up of an ancient, alien monolithic structure, surface covered in shifting, unreadable geometric patterns",
  "A pristine, empty futuristic observation deck overlooking a massive, glowing spiral galaxy",
  "Macro detail of a high-tension carbon-fiber bowstring snapping, capturing the microscopic fraying of the fibers",
  "A futuristic, unmarked aerodynamic stealth bomber wing slicing through a high-altitude stratospheric cloud layer",
  "An abstract landscape of towering, perfectly smooth metallic obelisks piercing through a thick layer of red smog",
  "Close-up of a flawlessly smooth, unbranded luxury cosmetic compact made of brushed rose-gold and white marble",
  "A massive, empty subterranean seed vault interior, rows of glowing cryogenic containment units stretching to infinity",
  "Macro photography of a highly reactive plasma arc dancing across the surface of a strong neodymium magnet",
  "A surreal, floating architectural concept of a minimalist glass cube resting entirely on a single point of balance",
  "Close-up of an unbranded, high-end audiophile vacuum tube amplifier glowing with warm amber light",
  "An empty, ultra-luxury high-speed yacht interior looking out at a perfectly calm, mirror-like nighttime ocean",
  "Macro detail of a complex, unbranded micro-mechanical drone wing, incredibly intricate folding structures",
  "A futuristic, glowing yellow energy shield absorbing an intense kinetic impact, rippling with concentric wave patterns",
  "An abstract composition of massive, brutalist concrete arches intersecting at impossible, Escher-like angles",
  "Close-up of an unbranded, aerodynamic carbon-fiber prosthetic sprinting blade, capturing the weave and tension",
  "A surreal, empty geometric room where the walls are made entirely of flowing, digital static noise",
  "Macro photography of a high-speed laser pulse striking a single atom of heavy water, intense microscopic flash",
  "An unbranded, high-tech deep-sea exploration submersible, cold metallic textures, lit by massive underwater spotlights",
  "Abstract fluid simulation of highly viscous liquid bismuth forming incredible stair-step structures in mid-air",
  "A massive, brutalist concrete cooling tower interior, massive geometric fan blades, deep atmospheric perspective",
  "Close-up of an ancient, glowing crystal matrix embedded deeply into a slab of rough meteorite rock",
  "A pristine, empty futuristic lunar habitat dome, glowing UV grow-lights illuminating a dark alien soil bed",
  "Macro detail of a high-frequency vibrating tuning fork shattering a perfectly thin sheet of ice",
  "A futuristic, unbranded robotic assembly line arm, precise pneumatic actuators and sleek white armor plating",
  "An abstract landscape of endless, perfectly smooth geometric canyons composed entirely of dark polished basalt",
  "Close-up of an unbranded, high-end microphone diaphragm exposed to direct light, reflecting complex metallic meshes",
  "A massive, empty subterranean water reservoir built inside an ancient aqueduct, glowing with underwater luminescence",
  "Macro photography of a perfectly spherical drop of liquid oxygen floating above a super-cooled ceramic plate",
  "A surreal architectural concept of a completely transparent glass elevator descending into a glowing active volcano",
  "Close-up of a flawlessly engineered, unbranded surgical-grade scalpel blade resting on dark sterile cloth",
  "An empty, ultra-luxury minimalist bank vault interior, walls lined with glowing, unbranded titanium safety deposit boxes",
  "Macro detail of a complex, unbranded synthetic nerve cluster, glowing softly with artificial electrical impulses",
  "A futuristic, glowing orange energy grid expanding across a dark, metallic asteroid surface",

  // ==========================================
  // 🔴 ENTERPRISE TIER IDEAS (151 - 250+)
  // Apsolutni "God-Tier" - Masterpiece apstrakcije, naučna fantastika i ultimativni minimalizam
  // ==========================================
  "Ultra-close macro of a supercar exhaust spitting blue flame at night, heat distortion waves rippling the background, highly detailed exhaust bluing, shot on 85mm f/1.2, zero text, unbranded",
  "A flawless, unbranded futuristic transit shelter made of sleek matte-black titanium and curved glass, illuminated by striking warm cinematic tungsten rim-lighting, zero human presence",
  "A massive, empty brutalist subterranean metro station with flooded mirror-like marble floors, bathed in volumetric god-rays and cinematic heavy fog, pure architectural mastery",
  "An unreleased forensic capture of a flawless, levitating conceptual aerogel matrix infused with glowing gold veins, resting over a dark brushed basalt pedestal",
  "A pristine, ultra-luxury high-tech maglev train platform accented with glowing cyan energy strips, submerged in a moody high-contrast atmosphere with anamorphic lens flares",
  "A massive, unbranded monolithic structural engine block made of polished obsidian and glowing raw platinum, suspended in a sterile, dust-free industrial vacuum chamber",
  "An abstract, high-fashion concept featuring a mannequin bust entirely encased in a massive block of translucent, cracked ice, subsurface light scattering",
  "Cinematic macro of an unbranded, heavily armored robotic joint mechanism, volumetric lighting slicing through hydraulic vapor, intense metallic reflection",
  "A 1970s Formula 1 car tire violently sliding through a gravel corner, mud clumps frozen in mid-air, anamorphic lens flares, no logos, unbranded aesthetic",
  "Macro shot of a perfect droplet of liquid gold splashing onto a matte black surface, reflecting a distant, unseen explosion, extreme dynamic range",
  "A luxury dive watch dial stripped of all branding, resting on black volcanic sand underwater, perfectly round air bubbles clinging to the sapphire crystal",
  "Architectural rendering of a minimalist glass pavilion suspended by high-tension cables over a roaring waterfall, caustic light patterns reflecting onto raw concrete ceilings",
  "An abstract culinary concept featuring liquid nitrogen smoke pouring over a flawless, unbranded gold-leaf sphere, dark moody lighting, commercial advertising grade",
  "Cinematic tracking shot of an unbranded, sleek aerodynamic motorcycle fairing speeding through a neon-lit tunnel, intense motion blur on the walls",
  "Macro photography of a matchhead the exact millisecond it ignites, incredible detail of the sulfur cracking and fire bursting, perfectly isolated on black",
  "An avant-garde sculptural piece made entirely of layered, sharp black obsidian shards, stark white studio background, high-contrast rim lighting",
  "A high-tech, unbranded dark-matter energy reactor core spinning rapidly, emitting intense purple radiation and warping the immediate atmosphere",
  "An underground server node, multiple glowing monolithic racks reflecting on a flooded black mirror floor, shallow depth of field, cyberpunk aesthetic without neon clichés",
  "Close-up of a high-end fountain pen nib dispensing metallic gold ink onto rough watercolor paper, extreme sharpness, no branding visible",
  "A sleek, unbranded concept hypercar chassis parked in an abandoned brutalist cathedral, light rays piercing through broken stained glass, heavy atmospheric dust",
  "A massive, empty subterranean seed vault interior, rows of glowing cryogenic containment units stretching to infinity, clinical white lighting",
  "A drone shot flying directly down a narrow canyon river, emerald green waters cutting through perfectly smooth, geometric black basalt walls",
  "Close-up of an astronaut's unbranded, reflective gold visor reflecting a massive exploding supernova, intense warm lighting illuminating the suit's fabric textures",
  "A luxury grand complication watch mechanism in motion, intricate gold gears and rubies perfectly lit, focus stacking macro technique, zero logos",
  "An abstract fashion editorial concept featuring tattered, floating haute couture silk fabric in a desolate, dark ash desert, harsh directional sunlight",
  "A cinematic wide shot of a massive, unbranded off-road tire kicking up a huge plume of black sand, isolated on a stark white background",
  "Macro view of a flawlessly engineered, unbranded camera sensor exposed to direct light, reflecting complex micro-lens arrays and rainbow interference patterns",
  "A modern minimalist dining room, harsh geometric sunlight casting distinct architectural shadows across a raw, massive solid wood table",
  "A perfectly spherical drop of liquid oxygen floating above a super-cooled ceramic plate, clinical lighting, pure scientific observation",
  "An abstract portrait concept of a face constructed entirely from shifting, glowing neon-cyan geometric wireframes, pure digital aesthetic",
  "A sleek electric speedboat hull slicing through bioluminescent water at midnight, glowing blue wake against total darkness, no branding",
  "Macro photography of a highly reactive chemical mixture producing dynamic, expanding colorful fractal patterns, extreme optical sharpness",
  "A surreal, infinite array of perfectly aligned white geometric columns stretching to the horizon on a flat dark plain, heavy fog obscuring the top",
  "Commercial shot of a matte black, unbranded smartphone resting on a bed of dark obsidian stones, screen displaying a vibrant fluid simulation",
  "An unbranded, high-performance disc brake rotor glowing cherry-red from extreme friction heat, carbon dust flying, dynamic studio shot",
  "Close-up of an ancient leather-bound book being opened, dust motes dancing in a beam of warm library light, no text visible on the pages",
  "A massive, brutalist concrete dam spillway releasing a torrent of perfectly smooth, glassy water, epic scale, dizzying downward perspective",
  "A luxury perfume bottle shattering on a marble floor, liquid and glass fragments frozen mid-explosion, unbranded, commercial advertising quality",
  "A surreal architectural concept of a completely transparent glass elevator descending into a glowing, active volcanic caldera",
  "A futuristic, unmarked aerodynamic stealth bomber wing slicing through a high-altitude stratospheric cloud layer, photorealistic aviation rendering",
  "Macro detail of a high-tension carbon-fiber bowstring snapping, capturing the microscopic fraying of the fibers, extreme high-speed capture",
  "An underground fighting ring concept, empty cage, gritty high-contrast lighting, blood droplets suspended in mid-air under a harsh spotlight",
  "A sleek minimalist kitchen featuring a massive black marble island, illuminated by a single thin LED strip, moody luxury interior, pristine condition",
  "An abstract composition of flowing, translucent holographic fabric billowing in a wind tunnel, dynamic commercial capture, no human presence",
  "A cinematic shot of a dense, dark pine forest at twilight, volumetric fog rolling through the trees, cold blue atmospheric tones",
  "Close-up of a bartender using a blowtorch to smoke an unbranded crystal cocktail glass, intense orange flames lighting up the dark bar background",
  "A drone perspective looking straight down at a lone, unbranded red canoe floating perfectly still on a pitch-black deep forest lake",
  "Macro shot of a vinyl record being scratched, immense detail of the stylus carving through the groove, raw analog texture, no label visible",
  "A high-end luxury SUV suspension system absorbing a massive impact, water splashing dynamically, commercial automotive photography, zero branding",
  "An abstract portrait concept of a futuristic geisha mask made of polished white porcelain and glowing red neon lines, illuminated by soft colored gel lights",
  "A cinematic wide shot of an abandoned amusement park slowly being reclaimed by overgrown glowing bioluminescent flora, eerie fog, melancholic mood",
  "Commercial photography of a premium, unbranded whiskey bottle encased in solid ice, condensation dripping, perfect studio lighting",
  "An abstract action shot of a concrete wall shattering outward, motion blur conveying extreme impact, gritty urban street lighting, debris suspended",
  "Macro detail of a high-frequency vibrating speaker cone launching microscopic gold dust particles into the air, acoustic energy visualized",
  "An architectural masterpiece featuring a cantilevered pool extending over a dense jungle canopy, viewed from above, perfectly calm glowing water",
  "A classic 1950s car grille and headlight reflecting a neon-lit retro diner, wet pavement reflections, cinematic Americana, stripped of all logos",
  "Close-up of an unbranded, high-end microphone diaphragm exposed to direct light, reflecting complex metallic meshes and intricate wiring",
  "A futuristic cityscape built entirely within a massive cavern, glowing geometric windows cutting through the subterranean darkness, cyberpunk scale",
  "A luxury sports watch mechanism suspended in mid-air, exploding into its hundreds of microscopic components, commercial 3D render style, zero text",
  "A cinematic shot of a glowing orange energy shield absorbing an intense kinetic impact, rippling with concentric wave patterns, deep space background",
  "Macro detail of a fountain pen nib dispensing metallic gold ink onto rough watercolor paper, extreme sharpness, no branding visible",
  "An abstract composition of hundreds of polished steel spheres suspended in mid-air, refracting a single intense blue light source",
  "A commercial shot of a sleek electric supercar drifting silently across a pristine white salt flat, kicking up salt crystals, completely unbranded",
  "A cinematic wide shot of a massive, glowing crystalline tree standing perfectly mirrored in a shallow flooded plain, moody overcast lighting",
  "Close-up of an unbranded, aerodynamic carbon-fiber sprinting blade prosthetic, capturing the weave and tension, dramatically lit against black",
  "An abstract fluid simulation of highly viscous liquid bismuth forming incredible stair-step structures in mid-air, vivid iridescent colors",
  "Macro photography of an intricate frost pattern rapidly freezing across a heated sheet of dark tempered glass, thermal contrast visualized",
  "A modern luxury bathroom featuring a massive skylight, rain pouring heavily against the glass, warm interior lighting reflecting off a black stone tub",
  "An abstract fashion concept featuring a massive, bright yellow haute couture gown billowing in an abandoned subway tunnel, zero human presence",
  "A cinematic drone shot flying through a fireworks display, colorful explosions bursting incredibly close to the lens, deep depth of field",
  "Commercial photography of a premium iced coffee splashing into an unbranded glass, slow motion liquid physics, dark atmospheric background",
  "A massive, empty subterranean train station built inside a natural crystal cavern, glowing with internal blue luminescence, epic architectural scale",
  "A lone snowboard carved from glowing ice, leaving a fresh line down an untouched mountain peak, massive powder spray, bright sunny day",
  "Macro detail of an intricate, unbranded artificial intelligence neural network node, glowing with complex data transmission pulses",
  "A high-end product shoot featuring a sleek black carbon-fiber archery bow drawn back, high-contrast studio lighting, immense tension visualized",
  "A cinematic tracking shot of a classic muscle car tire burning out, thick white tire smoke illuminated by red tail lights, zero logos or branding",
  "Close-up of a painter's palette covered in vibrant, thick acrylics, raw creative energy visualized through texture and color mixing",
  "A luxury mountain resort featuring floor-to-ceiling windows, glowing warmly against a backdrop of a massive blizzard at night, empty and pristine",
  "A commercial shot of a high-tech, unbranded gaming mouse resting on an illuminated wireless charging pad, sleek dark aesthetic, laser scanning effect",
  "A cinematic shot of an ethereal red fabric billowing underwater like smoke, perfectly suspended in a weightless deep blue environment",
  "Macro photography of a high-speed laser pulse striking a single atom of heavy water, intense microscopic flash, pure physical science observation",
  "An abstract architectural concept of a completely transparent glass bridge spanning across two towering, jagged mountain peaks, dizzying perspective"
];
// KRAJ FAJLA: V8PromptData.js